# Lecture 4 — Tutorial Examples for Python Foundations II

**Website pages:** Tutorials 2.8–2.14  
[Open in Google Colab](https://colab.research.google.com/github/asmrabbi/E26_TAN7_Scripting_CPH/blob/main/notebooks/lecture_04/L04_Tutorial_2_8_to_2_14_Examples.ipynb) · [Course repository](https://github.com/asmrabbi/E26_TAN7_Scripting_CPH)

## Goal

Run or inspect every Python code example shown in Tutorials 2.8–2.14 from one numbered Lecture 4 notebook.

## Setup

These tutorials use Python 3 and its standard library only. No third-party package, dataset, virtual environment or `requirements.txt` installation is required. In Colab, choose **Runtime → Run all**; locally, open this file in Jupyter or PyCharm with Python 3.

## Steps

Follow the website pages in order. Runnable examples execute below; deliberate errors, partial fragments and interactive examples remain visible as fully commented code and are labelled so that Run all stays safe.

## Tutorial 2.8

### Example 2.8.1 — 4.1 What is a Boolean value?

**Status:** Runnable — audited independently.

```python
True  # Runs this documented step in the solution.
False  # Runs this documented step in the solution.
```

In [1]:
True  # Runs this documented step in the solution.
False  # Runs this documented step in the solution.

### Example 2.8.2 — 4.1 What is a Boolean value?

**Status:** Runnable — audited independently.

```python
record_complete = True  # Stores the value needed by later steps.
needs_review = False  # Stores the value needed by later steps.

print(record_complete)  # Displays a labelled result for inspection.
print(needs_review)  # Displays a labelled result for inspection.
```

In [2]:
record_complete = True  # Stores the value needed by later steps.
needs_review = False  # Stores the value needed by later steps.

print(record_complete)  # Displays a labelled result for inspection.
print(needs_review)  # Displays a labelled result for inspection.

True
False


### Example 2.8.3 — Line-by-line explanation

**Status:** Runnable — audited independently.

```python
record_complete = True  # Stores the value needed by later steps.
```

In [3]:
record_complete = True  # Stores the value needed by later steps.

### Example 2.8.4 — Line-by-line explanation

**Status:** Runnable — audited independently.

```python
needs_review = False  # Stores the value needed by later steps.
```

In [4]:
needs_review = False  # Stores the value needed by later steps.

### Example 2.8.5 — Line-by-line explanation

**Status:** Diagnostic — NameError: name 'record_complete' is not defined.

```python
print(record_complete)  # Displays a labelled result for inspection.
```

In [5]:
example_status = "Example 2.8.5: diagnostic — NameError: name 'record_complete' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.5: diagnostic — NameError: name 'record_complete' is not defined


### Example 2.8.6 — Example 1: Comparing a number

**Status:** Runnable — audited independently.

```python
engagement = 125  # Stores the value needed by later steps.

print(engagement > 100)  # Displays a labelled result for inspection.
print(engagement == 125)  # Displays a labelled result for inspection.
print(engagement < 50)  # Displays a labelled result for inspection.
```

In [6]:
engagement = 125  # Stores the value needed by later steps.

print(engagement > 100)  # Displays a labelled result for inspection.
print(engagement == 125)  # Displays a labelled result for inspection.
print(engagement < 50)  # Displays a labelled result for inspection.

True
True
False


### Example 2.8.7 — 4.3 Assignment and equality are different

**Status:** Runnable — audited independently.

```python
engagement = 125  # Stores the value needed by later steps.
```

In [7]:
engagement = 125  # Stores the value needed by later steps.

### Example 2.8.8 — 4.3 Assignment and equality are different

**Status:** Diagnostic — NameError: name 'engagement' is not defined.

```python
engagement == 125  # Runs this documented step in the solution.
```

In [8]:
example_status = "Example 2.8.8: diagnostic — NameError: name 'engagement' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.8: diagnostic — NameError: name 'engagement' is not defined


### Example 2.8.9 — Deliberate error

**Status:** Diagnostic — deliberate or partial syntax (invalid syntax. Maybe you meant '==' or ':=' instead of '='?).

```python
engagement = 125  # Stores the value needed by later steps.

if engagement = 125:  # Starts a branch when this condition is true.
    print("The value is 125")  # Displays a labelled result for inspection.
```

In [9]:
example_status = "Example 2.8.9: diagnostic — deliberate or partial syntax (invalid syntax. Maybe you meant '==' or ':=' instead of '='?)"  # Runs this documented step in the solution.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.9: diagnostic — deliberate or partial syntax (invalid syntax. Maybe you meant '==' or ':=' instead of '='?)


### Example 2.8.10 — Repair

**Status:** Runnable — audited independently.

```python
engagement = 125  # Stores the value needed by later steps.

if engagement == 125:  # Starts a branch when this condition is true.
    print("The value is 125")  # Displays a labelled result for inspection.
```

In [10]:
engagement = 125  # Stores the value needed by later steps.

if engagement == 125:  # Starts a branch when this condition is true.
    print("The value is 125")  # Displays a labelled result for inspection.

The value is 125


### Example 2.8.11 — 4.4 Comparing strings

**Status:** Runnable — audited independently.

```python
actor_type = "Municipality"  # Stores the value needed by later steps.

print(actor_type == "Municipality")  # Displays a labelled result for inspection.
print(actor_type == "Business")  # Displays a labelled result for inspection.
print(actor_type != "Citizen")  # Displays a labelled result for inspection.
```

In [11]:
actor_type = "Municipality"  # Stores the value needed by later steps.

print(actor_type == "Municipality")  # Displays a labelled result for inspection.
print(actor_type == "Business")  # Displays a labelled result for inspection.
print(actor_type != "Citizen")  # Displays a labelled result for inspection.

True
False
True


### Example 2.8.12 — 4.4 Comparing strings

**Status:** Runnable — audited independently.

```python
topic = "Cycling"  # Stores the value needed by later steps.

print(topic == "Cycling")  # Displays a labelled result for inspection.
print(topic == "cycling")  # Displays a labelled result for inspection.
```

In [12]:
topic = "Cycling"  # Stores the value needed by later steps.

print(topic == "Cycling")  # Displays a labelled result for inspection.
print(topic == "cycling")  # Displays a labelled result for inspection.

True
False


### Example 2.8.13 — 4.5 Storing the result of a comparison

**Status:** Runnable — audited independently.

```python
missing_values = 14  # Stores the value needed by later steps.
too_many_missing = missing_values > 10  # Stores the value needed by later steps.

print(too_many_missing)  # Displays a labelled result for inspection.
```

In [13]:
missing_values = 14  # Stores the value needed by later steps.
too_many_missing = missing_values > 10  # Stores the value needed by later steps.

print(too_many_missing)  # Displays a labelled result for inspection.

True


### Example 2.8.14 — Explanation

**Status:** Diagnostic — NameError: name 'missing_values' is not defined.

```python
missing_values > 10  # Runs this documented step in the solution.
```

In [14]:
example_status = "Example 2.8.14: diagnostic — NameError: name 'missing_values' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.14: diagnostic — NameError: name 'missing_values' is not defined


### Example 2.8.15 — Explanation

**Status:** Diagnostic — NameError: name 'too_many_missing' is not defined.

```python
too_many_missing  # Runs this documented step in the solution.
```

In [15]:
example_status = "Example 2.8.15: diagnostic — NameError: name 'too_many_missing' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.15: diagnostic — NameError: name 'too_many_missing' is not defined


### Example 2.8.16 — Explanation

**Status:** Diagnostic — NameError: name 'missing_values' is not defined.

```python
if missing_values > 10:  # Starts a branch when this condition is true.
    print("Review the data")  # Displays a labelled result for inspection.
```

In [16]:
example_status = "Example 2.8.16: diagnostic — NameError: name 'missing_values' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.16: diagnostic — NameError: name 'missing_values' is not defined


### Example 2.8.17 — Explanation

**Status:** Diagnostic — NameError: name 'missing_values' is not defined.

```python
too_many_missing = missing_values > 10  # Stores the value needed by later steps.

if too_many_missing:  # Starts a branch when this condition is true.
    print("Review the data")  # Displays a labelled result for inspection.
```

In [17]:
example_status = "Example 2.8.17: diagnostic — NameError: name 'missing_values' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.17: diagnostic — NameError: name 'missing_values' is not defined


### Example 2.8.18 — Practice checkpoint 1

**Status:** Runnable — audited independently.

```python
records = 75  # Stores the value needed by later steps.
minimum_required = 100  # Stores the value needed by later steps.
enough_records = records >= minimum_required  # Runs this documented step in the solution.

print(enough_records)  # Displays a labelled result for inspection.
```

In [18]:
records = 75  # Stores the value needed by later steps.
minimum_required = 100  # Stores the value needed by later steps.
enough_records = records >= minimum_required  # Runs this documented step in the solution.

print(enough_records)  # Displays a labelled result for inspection.

False


### Example 2.8.19 — 5.1 A one-way decision

**Status:** Runnable — audited independently.

```python
missing_values = 14  # Stores the value needed by later steps.

if missing_values > 10:  # Starts a branch when this condition is true.
    print("Review the missing data")  # Displays a labelled result for inspection.
```

In [19]:
missing_values = 14  # Stores the value needed by later steps.

if missing_values > 10:  # Starts a branch when this condition is true.
    print("Review the missing data")  # Displays a labelled result for inspection.

Review the missing data


### Example 2.8.20 — Structure

**Status:** Diagnostic — NameError: name 'condition' is not defined.

```python
if condition:  # Starts a branch when this condition is true.
    code_to_run  # Runs this documented step in the solution.
```

In [20]:
example_status = "Example 2.8.20: diagnostic — NameError: name 'condition' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.20: diagnostic — NameError: name 'condition' is not defined


### Example 2.8.21 — 5.2 When the condition is false

**Status:** Runnable — audited independently.

```python
missing_values = 4  # Stores the value needed by later steps.

if missing_values > 10:  # Starts a branch when this condition is true.
    print("Review the missing data")  # Displays a labelled result for inspection.

print("Check complete")  # Displays a labelled result for inspection.
```

In [21]:
missing_values = 4  # Stores the value needed by later steps.

if missing_values > 10:  # Starts a branch when this condition is true.
    print("Review the missing data")  # Displays a labelled result for inspection.

print("Check complete")  # Displays a labelled result for inspection.

Check complete


### Example 2.8.22 — 5.3 Indentation is part of Python syntax

**Status:** Runnable — audited independently.

```python
engagement = 150  # Stores the value needed by later steps.

if engagement > 100:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
    print("Include this record in the high-engagement review")  # Displays a labelled result for inspection.

print("Finished")  # Displays a labelled result for inspection.
```

In [22]:
engagement = 150  # Stores the value needed by later steps.

if engagement > 100:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
    print("Include this record in the high-engagement review")  # Displays a labelled result for inspection.

print("Finished")  # Displays a labelled result for inspection.

High engagement
Include this record in the high-engagement review
Finished


### Example 2.8.23 — 5.3 Indentation is part of Python syntax

**Status:** Diagnostic — deliberate or partial syntax (expected an indented block after 'if' statement on line 3).

```python
engagement = 150  # Stores the value needed by later steps.

if engagement > 100:  # Starts a branch when this condition is true.
print("High engagement")  # Displays a labelled result for inspection.
```

In [23]:
example_status = "Example 2.8.23: diagnostic — deliberate or partial syntax (expected an indented block after 'if' statement on line 3)"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.23: diagnostic — deliberate or partial syntax (expected an indented block after 'if' statement on line 3)


### Example 2.8.24 — Repair

**Status:** Runnable — audited independently.

```python
engagement = 150  # Stores the value needed by later steps.

if engagement > 100:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
```

In [24]:
engagement = 150  # Stores the value needed by later steps.

if engagement > 100:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.

High engagement


### Example 2.8.25 — 5.4 Multiple lines inside one `if` block

**Status:** Runnable — audited independently.

```python
engagement = 220  # Stores the value needed by later steps.
actor_type = "Citizen Group"  # Stores the value needed by later steps.

if engagement > 200:  # Starts a branch when this condition is true.
    print("Priority record")  # Displays a labelled result for inspection.
    print("Actor type:", actor_type)  # Displays a labelled result for inspection.
    print("Engagement:", engagement)  # Displays a labelled result for inspection.

print("Assessment complete")  # Displays a labelled result for inspection.
```

In [25]:
engagement = 220  # Stores the value needed by later steps.
actor_type = "Citizen Group"  # Stores the value needed by later steps.

if engagement > 200:  # Starts a branch when this condition is true.
    print("Priority record")  # Displays a labelled result for inspection.
    print("Actor type:", actor_type)  # Displays a labelled result for inspection.
    print("Engagement:", engagement)  # Displays a labelled result for inspection.

print("Assessment complete")  # Displays a labelled result for inspection.

Priority record
Actor type: Citizen Group
Engagement: 220
Assessment complete


### Example 2.8.26 — 5.5 A condition using a string

**Status:** Runnable — audited independently.

```python
position = "Support"  # Stores the value needed by later steps.

if position == "Support":  # Starts a branch when this condition is true.
    print("This record supports the proposal")  # Displays a labelled result for inspection.
```

In [26]:
position = "Support"  # Stores the value needed by later steps.

if position == "Support":  # Starts a branch when this condition is true.
    print("This record supports the proposal")  # Displays a labelled result for inspection.

This record supports the proposal


### Example 2.8.27 — Common mistake

**Status:** Runnable — audited independently.

```python
position = "Support"  # Stores the value needed by later steps.

if position == "support":  # Starts a branch when this condition is true.
    print("This record supports the proposal")  # Displays a labelled result for inspection.
```

In [27]:
position = "Support"  # Stores the value needed by later steps.

if position == "support":  # Starts a branch when this condition is true.
    print("This record supports the proposal")  # Displays a labelled result for inspection.

### Example 2.8.28 — Common mistake

**Status:** Runnable — audited independently.

```python
position = "Support"  # Stores the value needed by later steps.

if position.lower() == "support":  # Starts a branch when this condition is true.
    print("This record supports the proposal")  # Displays a labelled result for inspection.
```

In [28]:
position = "Support"  # Stores the value needed by later steps.

if position.lower() == "support":  # Starts a branch when this condition is true.
    print("This record supports the proposal")  # Displays a labelled result for inspection.

This record supports the proposal


### Example 2.8.29 — Practice checkpoint 2

**Status:** Diagnostic — NameError: name '__________________' is not defined.

```python
duplicate_rows = 7  # Stores the value needed by later steps.

if __________________:  # Starts a branch when this condition is true.
    print("Duplicates must be reviewed")  # Displays a labelled result for inspection.
```

In [29]:
example_status = "Example 2.8.29: diagnostic — NameError: name '__________________' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.29: diagnostic — NameError: name '__________________' is not defined


### Example 2.8.30 — Practice checkpoint 2

**Status:** Runnable — audited independently.

```python
duplicate_rows = 7  # Stores the value needed by later steps.

if duplicate_rows > 0:  # Starts a branch when this condition is true.
    print("Duplicates must be reviewed")  # Displays a labelled result for inspection.
```

In [30]:
duplicate_rows = 7  # Stores the value needed by later steps.

if duplicate_rows > 0:  # Starts a branch when this condition is true.
    print("Duplicates must be reviewed")  # Displays a labelled result for inspection.

Duplicates must be reviewed


### Example 2.8.31 — 6.1 Basic example

**Status:** Runnable — audited independently.

```python
missing_values = 14  # Stores the value needed by later steps.

if missing_values > 10:  # Starts a branch when this condition is true.
    print("Review the dataset")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Continue to initial analysis")  # Displays a labelled result for inspection.
```

In [31]:
missing_values = 14  # Stores the value needed by later steps.

if missing_values > 10:  # Starts a branch when this condition is true.
    print("Review the dataset")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Continue to initial analysis")  # Displays a labelled result for inspection.

Review the dataset


### Example 2.8.32 — 6.2 Understanding the flow

**Status:** Diagnostic — NameError: name 'condition' is not defined.

```python
if condition:  # Starts a branch when this condition is true.
    action_when_true  # Runs this documented step in the solution.
else:  # Starts the fallback branch.
    action_when_false  # Runs this documented step in the solution.
```

In [32]:
example_status = "Example 2.8.32: diagnostic — NameError: name 'condition' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.32: diagnostic — NameError: name 'condition' is not defined


### Example 2.8.33 — 6.3 Example with user input

**Status:** Manual — interactive input.

```python
answer = input("Is the source verified? Type yes or no: ")  # Stores the value needed by later steps.

if answer == "yes":  # Starts a branch when this condition is true.
    print("The record may continue to analysis")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("The source must be reviewed")  # Displays a labelled result for inspection.
```

In [33]:
example_status = 'Example 2.8.33: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.33: manual — interactive input


### Example 2.8.34 — Problem with this version

**Status:** Manual — interactive input.

```python
answer = input("Is the source verified? Type yes or no: ")  # Stores the value needed by later steps.
answer = answer.strip().lower()  # Stores the value needed by later steps.

if answer == "yes":  # Starts a branch when this condition is true.
    print("The record may continue to analysis")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("The source must be reviewed")  # Displays a labelled result for inspection.
```

In [34]:
example_status = 'Example 2.8.34: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.34: manual — interactive input


### Example 2.8.35 — 6.4 Deliberate break-and-repair activity

**Status:** Diagnostic — deliberate or partial syntax (expected ':').

```python
engagement = 80  # Stores the value needed by later steps.

if engagement >= 100  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
else  # Runs this documented step in the solution.
    print("Normal engagement")  # Displays a labelled result for inspection.
```

In [35]:
example_status = "Example 2.8.35: diagnostic — deliberate or partial syntax (expected ':')"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.35: diagnostic — deliberate or partial syntax (expected ':')


### Example 2.8.36 — 6.4 Deliberate break-and-repair activity

**Status:** Runnable — audited independently.

```python
engagement = 80  # Stores the value needed by later steps.

if engagement >= 100:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Normal engagement")  # Displays a labelled result for inspection.
```

In [36]:
engagement = 80  # Stores the value needed by later steps.

if engagement >= 100:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Normal engagement")  # Displays a labelled result for inspection.

Normal engagement


### Example 2.8.37 — 7.1 Classifying engagement

**Status:** Runnable — audited independently.

```python
engagement = 125  # Stores the value needed by later steps.

if engagement >= 200:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
elif engagement >= 100:  # Checks another condition after earlier branches were false.
    print("Medium engagement")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Low engagement")  # Displays a labelled result for inspection.
```

In [37]:
engagement = 125  # Stores the value needed by later steps.

if engagement >= 200:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
elif engagement >= 100:  # Checks another condition after earlier branches were false.
    print("Medium engagement")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Low engagement")  # Displays a labelled result for inspection.

Medium engagement


### Example 2.8.38 — 7.2 Order matters

**Status:** Runnable — audited independently.

```python
engagement = 250  # Stores the value needed by later steps.

if engagement >= 100:  # Starts a branch when this condition is true.
    print("Medium or high engagement")  # Displays a labelled result for inspection.
elif engagement >= 200:  # Checks another condition after earlier branches were false.
    print("High engagement")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Low engagement")  # Displays a labelled result for inspection.
```

In [38]:
engagement = 250  # Stores the value needed by later steps.

if engagement >= 100:  # Starts a branch when this condition is true.
    print("Medium or high engagement")  # Displays a labelled result for inspection.
elif engagement >= 200:  # Checks another condition after earlier branches were false.
    print("High engagement")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Low engagement")  # Displays a labelled result for inspection.

Medium or high engagement


### Example 2.8.39 — 7.2 Order matters

**Status:** Runnable — audited independently.

```python
engagement = 250  # Stores the value needed by later steps.

if engagement >= 200:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
elif engagement >= 100:  # Checks another condition after earlier branches were false.
    print("Medium engagement")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Low engagement")  # Displays a labelled result for inspection.
```

In [39]:
engagement = 250  # Stores the value needed by later steps.

if engagement >= 200:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
elif engagement >= 100:  # Checks another condition after earlier branches were false.
    print("Medium engagement")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Low engagement")  # Displays a labelled result for inspection.

High engagement


### Example 2.8.40 — 7.3 A more detailed classification

**Status:** Runnable — audited independently.

```python
missing_percentage = 18  # Stores the value needed by later steps.

if missing_percentage == 0:  # Starts a branch when this condition is true.
    status = "No missing values"  # Stores the value needed by later steps.
elif missing_percentage <= 5:  # Checks another condition after earlier branches were false.
    status = "Minor missingness"  # Stores the value needed by later steps.
elif missing_percentage <= 15:  # Checks another condition after earlier branches were false.
    status = "Moderate missingness"  # Stores the value needed by later steps.
else:  # Starts the fallback branch.
    status = "Substantial missingness"  # Stores the value needed by later steps.

print(status)  # Displays a labelled result for inspection.
```

In [40]:
missing_percentage = 18  # Stores the value needed by later steps.

if missing_percentage == 0:  # Starts a branch when this condition is true.
    status = "No missing values"  # Stores the value needed by later steps.
elif missing_percentage <= 5:  # Checks another condition after earlier branches were false.
    status = "Minor missingness"  # Stores the value needed by later steps.
elif missing_percentage <= 15:  # Checks another condition after earlier branches were false.
    status = "Moderate missingness"  # Stores the value needed by later steps.
else:  # Starts the fallback branch.
    status = "Substantial missingness"  # Stores the value needed by later steps.

print(status)  # Displays a labelled result for inspection.

Substantial missingness


### Example 2.8.41 — Why assign the result to a variable?

**Status:** Diagnostic — NameError: name 'status' is not defined.

```python
print("Data-quality status:", status)  # Displays a labelled result for inspection.
```

In [41]:
example_status = "Example 2.8.41: diagnostic — NameError: name 'status' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.41: diagnostic — NameError: name 'status' is not defined


### Example 2.8.42 — Why assign the result to a variable?

**Status:** Diagnostic — NameError: name 'status' is not defined.

```python
if status == "Substantial missingness":  # Starts a branch when this condition is true.
    print("Human review required")  # Displays a labelled result for inspection.
```

In [42]:
example_status = "Example 2.8.42: diagnostic — NameError: name 'status' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.8.42: diagnostic — NameError: name 'status' is not defined


### Example 2.8.43 — 7.4 Boundary testing

**Status:** Runnable — audited independently.

```python
missing_percentage = 0  # Stores the value needed by later steps.
missing_percentage = 1  # Stores the value needed by later steps.
missing_percentage = 5  # Stores the value needed by later steps.
missing_percentage = 6  # Stores the value needed by later steps.
missing_percentage = 15  # Stores the value needed by later steps.
missing_percentage = 16  # Stores the value needed by later steps.
```

In [43]:
missing_percentage = 0  # Stores the value needed by later steps.
missing_percentage = 1  # Stores the value needed by later steps.
missing_percentage = 5  # Stores the value needed by later steps.
missing_percentage = 6  # Stores the value needed by later steps.
missing_percentage = 15  # Stores the value needed by later steps.
missing_percentage = 16  # Stores the value needed by later steps.

### Example 2.8.44 — 7.4 Boundary testing

**Status:** Runnable — audited independently.

```python
score = 70  # Stores the value needed by later steps.

if score > 70:  # Starts a branch when this condition is true.
    print("High")  # Displays a labelled result for inspection.
elif score < 70:  # Checks another condition after earlier branches were false.
    print("Low")  # Displays a labelled result for inspection.
```

In [44]:
score = 70  # Stores the value needed by later steps.

if score > 70:  # Starts a branch when this condition is true.
    print("High")  # Displays a labelled result for inspection.
elif score < 70:  # Checks another condition after earlier branches were false.
    print("Low")  # Displays a labelled result for inspection.

### Example 2.8.45 — 7.4 Boundary testing

**Status:** Runnable — audited independently.

```python
score = 70  # Stores the value needed by later steps.

if score >= 70:  # Starts a branch when this condition is true.
    print("High")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Low")  # Displays a labelled result for inspection.
```

In [45]:
score = 70  # Stores the value needed by later steps.

if score >= 70:  # Starts a branch when this condition is true.
    print("High")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Low")  # Displays a labelled result for inspection.

High


### Example 2.8.46 — Practice checkpoint 3

**Status:** Runnable — audited independently.

```python
number_of_records = 145  # Stores the value needed by later steps.

# Write your decision below
```

In [46]:
number_of_records = 145  # Stores the value needed by later steps.

# Write your decision below

### Example 2.8.47 — Practice checkpoint 3

**Status:** Runnable — audited independently.

```python
number_of_records = 145  # Stores the value needed by later steps.

if number_of_records >= 200:  # Starts a branch when this condition is true.
    print("Large dataset")  # Displays a labelled result for inspection.
elif number_of_records >= 100:  # Checks another condition after earlier branches were false.
    print("Medium dataset")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Small dataset")  # Displays a labelled result for inspection.
```

In [47]:
number_of_records = 145  # Stores the value needed by later steps.

if number_of_records >= 200:  # Starts a branch when this condition is true.
    print("Large dataset")  # Displays a labelled result for inspection.
elif number_of_records >= 100:  # Checks another condition after earlier branches were false.
    print("Medium dataset")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Small dataset")  # Displays a labelled result for inspection.

Medium dataset


## Tutorial 2.9

### Example 2.9.1 — 8.1 `and`

**Status:** Runnable — audited independently.

```python
missing_values = 4  # Stores the value needed by later steps.
duplicate_rows = 0  # Stores the value needed by later steps.

if missing_values <= 5 and duplicate_rows == 0:  # Starts a branch when this condition is true.
    print("The dataset passes the initial check")  # Displays a labelled result for inspection.
```

In [48]:
missing_values = 4  # Stores the value needed by later steps.
duplicate_rows = 0  # Stores the value needed by later steps.

if missing_values <= 5 and duplicate_rows == 0:  # Starts a branch when this condition is true.
    print("The dataset passes the initial check")  # Displays a labelled result for inspection.

The dataset passes the initial check


### Example 2.9.2 — 8.2 `or`

**Status:** Runnable — audited independently.

```python
missing_values = 3  # Stores the value needed by later steps.
duplicate_rows = 7  # Stores the value needed by later steps.

if missing_values > 10 or duplicate_rows > 0:  # Starts a branch when this condition is true.
    print("Review is required")  # Displays a labelled result for inspection.
```

In [49]:
missing_values = 3  # Stores the value needed by later steps.
duplicate_rows = 7  # Stores the value needed by later steps.

if missing_values > 10 or duplicate_rows > 0:  # Starts a branch when this condition is true.
    print("Review is required")  # Displays a labelled result for inspection.

Review is required


### Example 2.9.3 — 8.3 `not`

**Status:** Runnable — audited independently.

```python
source_verified = False  # Stores the value needed by later steps.

if not source_verified:  # Starts a branch when this condition is true.
    print("Do not use the record without review")  # Displays a labelled result for inspection.
```

In [50]:
source_verified = False  # Stores the value needed by later steps.

if not source_verified:  # Starts a branch when this condition is true.
    print("Do not use the record without review")  # Displays a labelled result for inspection.

Do not use the record without review


### Example 2.9.4 — 8.4 A combined example

**Status:** Runnable — audited independently.

```python
actor_type = "Citizen Group"  # Stores the value needed by later steps.
engagement = 240  # Stores the value needed by later steps.
source_verified = True  # Stores the value needed by later steps.

if actor_type == "Citizen Group" and engagement >= 200 and source_verified:  # Starts a branch when this condition is true.
    print("Include in the high-engagement citizen-group review")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Use the standard review process")  # Displays a labelled result for inspection.
```

In [51]:
actor_type = "Citizen Group"  # Stores the value needed by later steps.
engagement = 240  # Stores the value needed by later steps.
source_verified = True  # Stores the value needed by later steps.

if actor_type == "Citizen Group" and engagement >= 200 and source_verified:  # Starts a branch when this condition is true.
    print("Include in the high-engagement citizen-group review")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Use the standard review process")  # Displays a labelled result for inspection.

Include in the high-engagement citizen-group review


### Example 2.9.5 — 8.5 Parentheses for clarity

**Status:** Diagnostic — NameError: name 'topic' is not defined.

```python
if topic == "Cycling" or topic == "Public Transport" and engagement > 100:  # Starts a branch when this condition is true.
    print("Selected")  # Displays a labelled result for inspection.
```

In [52]:
example_status = "Example 2.9.5: diagnostic — NameError: name 'topic' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.9.5: diagnostic — NameError: name 'topic' is not defined


### Example 2.9.6 — 8.5 Parentheses for clarity

**Status:** Diagnostic — NameError: name 'topic' is not defined.

```python
if (topic == "Cycling" or topic == "Public Transport") and engagement > 100:  # Starts a branch when this condition is true.
    print("Selected")  # Displays a labelled result for inspection.
```

In [53]:
example_status = "Example 2.9.6: diagnostic — NameError: name 'topic' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.9.6: diagnostic — NameError: name 'topic' is not defined


### Example 2.9.7 — 8.6 Common mistake: repeating the variable incorrectly

**Status:** Runnable — audited independently.

```python
topic = "Cycling"  # Stores the value needed by later steps.

if topic == "Cycling" or "Public Transport":  # Starts a branch when this condition is true.
    print("Selected topic")  # Displays a labelled result for inspection.
```

In [54]:
topic = "Cycling"  # Stores the value needed by later steps.

if topic == "Cycling" or "Public Transport":  # Starts a branch when this condition is true.
    print("Selected topic")  # Displays a labelled result for inspection.

Selected topic


### Example 2.9.8 — 8.6 Common mistake: repeating the variable incorrectly

**Status:** Runnable — audited independently.

```python
topic = "Cycling"  # Stores the value needed by later steps.

if topic == "Cycling" or topic == "Public Transport":  # Starts a branch when this condition is true.
    print("Selected topic")  # Displays a labelled result for inspection.
```

In [55]:
topic = "Cycling"  # Stores the value needed by later steps.

if topic == "Cycling" or topic == "Public Transport":  # Starts a branch when this condition is true.
    print("Selected topic")  # Displays a labelled result for inspection.

Selected topic


### Example 2.9.9 — 8.6 Common mistake: repeating the variable incorrectly

**Status:** Diagnostic — NameError: name 'topic' is not defined.

```python
if topic in ["Cycling", "Public Transport"]:  # Starts a branch when this condition is true.
    print("Selected topic")  # Displays a labelled result for inspection.
```

In [56]:
example_status = "Example 2.9.9: diagnostic — NameError: name 'topic' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.9.9: diagnostic — NameError: name 'topic' is not defined


### Example 2.9.10 — Practice checkpoint 4

**Status:** Runnable — audited independently.

```python
engagement = 180  # Stores the value needed by later steps.
actor_type = "NGO"  # Stores the value needed by later steps.

if engagement >= 150 and (actor_type == "Citizen Group" or actor_type == "NGO"):  # Starts a branch when this condition is true.
    print("Priority review")  # Displays a labelled result for inspection.
```

In [57]:
engagement = 180  # Stores the value needed by later steps.
actor_type = "NGO"  # Stores the value needed by later steps.

if engagement >= 150 and (actor_type == "Citizen Group" or actor_type == "NGO"):  # Starts a branch when this condition is true.
    print("Priority review")  # Displays a labelled result for inspection.

Priority review


### Example 2.9.11 — 9.1 Basic nested example

**Status:** Runnable — audited independently.

```python
source_verified = True  # Stores the value needed by later steps.
engagement = 230  # Stores the value needed by later steps.

if source_verified:  # Starts a branch when this condition is true.
    print("Source check passed")  # Displays a labelled result for inspection.

    if engagement >= 200:  # Starts a branch when this condition is true.
        print("High-engagement verified record")  # Displays a labelled result for inspection.
```

In [58]:
source_verified = True  # Stores the value needed by later steps.
engagement = 230  # Stores the value needed by later steps.

if source_verified:  # Starts a branch when this condition is true.
    print("Source check passed")  # Displays a labelled result for inspection.

    if engagement >= 200:  # Starts a branch when this condition is true.
        print("High-engagement verified record")  # Displays a labelled result for inspection.

Source check passed
High-engagement verified record


### Example 2.9.12 — 9.2 Nested decision with alternatives

**Status:** Runnable — audited independently.

```python
source_verified = True  # Stores the value needed by later steps.
engagement = 80  # Stores the value needed by later steps.

if source_verified:  # Starts a branch when this condition is true.
    if engagement >= 200:  # Starts a branch when this condition is true.
        print("High-engagement verified record")  # Displays a labelled result for inspection.
    else:  # Starts the fallback branch.
        print("Verified record with normal engagement")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Source review required")  # Displays a labelled result for inspection.
```

In [59]:
source_verified = True  # Stores the value needed by later steps.
engagement = 80  # Stores the value needed by later steps.

if source_verified:  # Starts a branch when this condition is true.
    if engagement >= 200:  # Starts a branch when this condition is true.
        print("High-engagement verified record")  # Displays a labelled result for inspection.
    else:  # Starts the fallback branch.
        print("Verified record with normal engagement")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Source review required")  # Displays a labelled result for inspection.

Verified record with normal engagement


### Example 2.9.13 — 9.3 Avoid unnecessary nesting

**Status:** Diagnostic — NameError: name 'source_verified' is not defined.

```python
if source_verified:  # Starts a branch when this condition is true.
    if engagement >= 200:  # Starts a branch when this condition is true.
        print("Selected")  # Displays a labelled result for inspection.
```

In [60]:
example_status = "Example 2.9.13: diagnostic — NameError: name 'source_verified' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.9.13: diagnostic — NameError: name 'source_verified' is not defined


### Example 2.9.14 — 9.3 Avoid unnecessary nesting

**Status:** Diagnostic — NameError: name 'source_verified' is not defined.

```python
if source_verified and engagement >= 200:  # Starts a branch when this condition is true.
    print("Selected")  # Displays a labelled result for inspection.
```

In [61]:
example_status = "Example 2.9.14: diagnostic — NameError: name 'source_verified' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.9.14: diagnostic — NameError: name 'source_verified' is not defined


## Tutorial 2.10

### Example 2.10.1 — 10.1 Why conversion is necessary

**Status:** Manual — interactive input.

```python
engagement = input("Enter the engagement value: ")  # Stores the value needed by later steps.

print(type(engagement))  # Displays a labelled result for inspection.
```

In [62]:
example_status = 'Example 2.10.1: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.1: manual — interactive input


### Example 2.10.2 — 10.1 Why conversion is necessary

**Status:** Manual — interactive input.

```python
engagement = input("Enter the engagement value: ")  # Stores the value needed by later steps.

if engagement > 100:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
```

In [63]:
example_status = 'Example 2.10.2: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.2: manual — interactive input


### Example 2.10.3 — 10.1 Why conversion is necessary

**Status:** Manual — interactive input.

```python
engagement = input("Enter the engagement value: ")  # Stores the value needed by later steps.
engagement = int(engagement)  # Stores the value needed by later steps.

if engagement > 100:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
```

In [64]:
example_status = 'Example 2.10.3: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.3: manual — interactive input


### Example 2.10.4 — 10.2 Conversion in one line

**Status:** Manual — interactive input.

```python
engagement = int(input("Enter the engagement value: "))  # Stores the value needed by later steps.

if engagement > 100:  # Starts a branch when this condition is true.
    print("High engagement")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Normal engagement")  # Displays a labelled result for inspection.
```

In [65]:
example_status = 'Example 2.10.4: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.4: manual — interactive input


### Example 2.10.5 — 10.3 Input assumptions

**Status:** Manual — interactive input.

```python
age = int(input("Enter age: "))  # Stores the value needed by later steps.
```

In [66]:
example_status = 'Example 2.10.5: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.5: manual — interactive input


### Example 2.10.6 — 11.1 Why error handling matters

**Status:** Manual — interactive input.

```python
engagement = int(input("Enter engagement: "))  # Stores the value needed by later steps.
print("Recorded:", engagement)  # Displays a labelled result for inspection.
```

In [67]:
example_status = 'Example 2.10.6: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.6: manual — interactive input


### Example 2.10.7 — 11.1 Why error handling matters

**Status:** Manual — interactive input.

```python
try:  # Starts a protected conversion or calculation block.
    engagement = int(input("Enter engagement: "))  # Stores the value needed by later steps.
    print("Recorded:", engagement)  # Displays a labelled result for inspection.
except:  # Runs this documented step in the solution.
    print("Error: enter a whole number")  # Displays a labelled result for inspection.
```

In [68]:
example_status = 'Example 2.10.7: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.7: manual — interactive input


### Example 2.10.8 — 11.2 Understanding the structure

**Status:** Diagnostic — NameError: name 'code_to_run_if_an_error_occurs' is not defined.

```python
try:  # Starts a protected conversion or calculation block.
    code_that_might_fail  # Runs this documented step in the solution.
except:  # Runs this documented step in the solution.
    code_to_run_if_an_error_occurs  # Runs this documented step in the solution.
```

In [69]:
example_status = "Example 2.10.8: diagnostic — NameError: name 'code_to_run_if_an_error_occurs' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.8: diagnostic — NameError: name 'code_to_run_if_an_error_occurs' is not defined


### Example 2.10.9 — 11.3 Catching a specific error

**Status:** Manual — interactive input.

```python
try:  # Starts a protected conversion or calculation block.
    engagement = int(input("Enter engagement: "))  # Stores the value needed by later steps.
    print("Recorded:", engagement)  # Displays a labelled result for inspection.
except ValueError:  # Handles the stated expected error.
    print("Error: enter a whole number")  # Displays a labelled result for inspection.
```

In [70]:
example_status = 'Example 2.10.9: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.9: manual — interactive input


### Example 2.10.10 — 11.4 Adding a decision after valid input

**Status:** Manual — interactive input.

```python
try:  # Starts a protected conversion or calculation block.
    engagement = int(input("Enter engagement: "))  # Stores the value needed by later steps.

    if engagement >= 200:  # Starts a branch when this condition is true.
        print("High engagement")  # Displays a labelled result for inspection.
    elif engagement >= 100:  # Checks another condition after earlier branches were false.
        print("Medium engagement")  # Displays a labelled result for inspection.
    else:  # Starts the fallback branch.
        print("Low engagement")  # Displays a labelled result for inspection.

except ValueError:  # Handles the stated expected error.
    print("The engagement value must be a whole number")  # Displays a labelled result for inspection.
```

In [71]:
example_status = 'Example 2.10.10: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.10: manual — interactive input


### Example 2.10.11 — 11.5 Valid type but invalid range

**Status:** Manual — interactive input.

```python
try:  # Starts a protected conversion or calculation block.
    percentage = float(input("Enter missing-data percentage: "))  # Stores the value needed by later steps.

    if percentage < 0 or percentage > 100:  # Starts a branch when this condition is true.
        print("Error: percentage must be between 0 and 100")  # Displays a labelled result for inspection.
    elif percentage > 15:  # Checks another condition after earlier branches were false.
        print("Substantial missingness")  # Displays a labelled result for inspection.
    else:  # Starts the fallback branch.
        print("Missingness is within the initial review threshold")  # Displays a labelled result for inspection.

except ValueError:  # Handles the stated expected error.
    print("Error: enter a numeric value")  # Displays a labelled result for inspection.
```

In [72]:
example_status = 'Example 2.10.11: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.11: manual — interactive input


### Example 2.10.12 — 11.6 Avoid a completely empty `except`

**Status:** Diagnostic — deliberate or partial syntax (invalid syntax).

```python
except:  # Runs this documented step in the solution.
    print("Something went wrong")  # Displays a labelled result for inspection.
```

In [73]:
example_status = 'Example 2.10.12: diagnostic — deliberate or partial syntax (invalid syntax)'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.12: diagnostic — deliberate or partial syntax (invalid syntax)


### Example 2.10.13 — 11.6 Avoid a completely empty `except`

**Status:** Diagnostic — deliberate or partial syntax (invalid syntax).

```python
except ValueError:  # Handles the stated expected error.
    print("Enter a numeric value")  # Displays a labelled result for inspection.
```

In [74]:
example_status = 'Example 2.10.13: diagnostic — deliberate or partial syntax (invalid syntax)'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.13: diagnostic — deliberate or partial syntax (invalid syntax)


### Example 2.10.14 — Practice checkpoint 5

**Status:** Manual — interactive input.

```python
number_of_records = int(input("Enter number of records: "))  # Stores the value needed by later steps.

if number_of_records >= 100:  # Starts a branch when this condition is true.
    print("Suitable for the planned exercise")  # Displays a labelled result for inspection.
else:  # Starts the fallback branch.
    print("Small dataset")  # Displays a labelled result for inspection.
```

In [75]:
example_status = 'Example 2.10.14: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.14: manual — interactive input


### Example 2.10.15 — Practice checkpoint 5

**Status:** Manual — interactive input.

```python
try:  # Starts a protected conversion or calculation block.
    number_of_records = int(input("Enter number of records: "))  # Stores the value needed by later steps.

    if number_of_records >= 100:  # Starts a branch when this condition is true.
        print("Suitable for the planned exercise")  # Displays a labelled result for inspection.
    else:  # Starts the fallback branch.
        print("Small dataset")  # Displays a labelled result for inspection.

except ValueError:  # Handles the stated expected error.
    print("Enter a whole number")  # Displays a labelled result for inspection.
```

In [76]:
example_status = 'Example 2.10.15: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.10.15: manual — interactive input


## Tutorial 2.11

### Example 2.11.1 — Lists: ordered values

**Status:** Runnable — audited independently.

```python
campuses = ["Aalborg", "Copenhagen"]  # Stores the value needed by later steps.
campuses.append("Online")  # Runs this documented step in the solution.

print(campuses[0])  # Displays a labelled result for inspection.
print(len(campuses))  # Displays a labelled result for inspection.
print(campuses)  # Displays a labelled result for inspection.
```

In [77]:
campuses = ["Aalborg", "Copenhagen"]  # Stores the value needed by later steps.
campuses.append("Online")  # Runs this documented step in the solution.

print(campuses[0])  # Displays a labelled result for inspection.
print(len(campuses))  # Displays a labelled result for inspection.
print(campuses)  # Displays a labelled result for inspection.

Aalborg
3
['Aalborg', 'Copenhagen', 'Online']


### Example 2.11.2 — Dictionaries: labelled values

**Status:** Runnable — audited independently.

```python
registration = {  # Starts a multi-line collection or expression.
    "participant_id": "CPH-014",  # Runs this documented step in the solution.
    "campus": "Copenhagen",  # Runs this documented step in the solution.
    "attending": True,  # Runs this documented step in the solution.
}  # Closes the collection or expression started above.

print(registration["campus"])  # Displays a labelled result for inspection.
registration["group"] = 3  # Stores the value needed by later steps.
print(registration)  # Displays a labelled result for inspection.
```

In [78]:
registration = {  # Starts a multi-line collection or expression.
    "participant_id": "CPH-014",  # Runs this documented step in the solution.
    "campus": "Copenhagen",  # Runs this documented step in the solution.
    "attending": True,  # Runs this documented step in the solution.
}  # Closes the collection or expression started above.

print(registration["campus"])  # Displays a labelled result for inspection.
registration["group"] = 3  # Stores the value needed by later steps.
print(registration)  # Displays a labelled result for inspection.

Copenhagen
{'participant_id': 'CPH-014', 'campus': 'Copenhagen', 'attending': True, 'group': 3}


### Example 2.11.3 — Sets: unique values

**Status:** Runnable — audited independently.

```python
submitted_ids = ["A12", "B07", "A12", "C03"]  # Stores the value needed by later steps.
unique_ids = set(submitted_ids)  # Stores the value needed by later steps.

print(unique_ids)  # Displays a labelled result for inspection.
print(len(unique_ids))  # Displays a labelled result for inspection.
```

In [79]:
submitted_ids = ["A12", "B07", "A12", "C03"]  # Stores the value needed by later steps.
unique_ids = set(submitted_ids)  # Stores the value needed by later steps.

print(unique_ids)  # Displays a labelled result for inspection.
print(len(unique_ids))  # Displays a labelled result for inspection.

{'C03', 'B07', 'A12'}
3


### Example 2.11.4 — A list of dictionaries: records ready for later file work

**Status:** Runnable — audited independently.

```python
observations = [  # Starts a multi-line collection or expression.
    {"record_id": 1, "category": "Bus", "minutes": 12},  # Runs this documented step in the solution.
    {"record_id": 2, "category": "Cycle", "minutes": 8},  # Runs this documented step in the solution.
]  # Closes the collection or expression started above.

for observation in observations:  # Repeats the indented steps for each item.
    print(observation["record_id"], observation["category"], observation["minutes"])  # Displays a labelled result for inspection.
```

In [80]:
observations = [  # Starts a multi-line collection or expression.
    {"record_id": 1, "category": "Bus", "minutes": 12},  # Runs this documented step in the solution.
    {"record_id": 2, "category": "Cycle", "minutes": 8},  # Runs this documented step in the solution.
]  # Closes the collection or expression started above.

for observation in observations:  # Repeats the indented steps for each item.
    print(observation["record_id"], observation["category"], observation["minutes"])  # Displays a labelled result for inspection.

1 Bus 12
2 Cycle 8


### Example 2.11.5 — 13.1 A simple definite loop

**Status:** Runnable — audited independently.

```python
for number in [1, 2, 3]:  # Repeats the indented steps for each item.
    print(number)  # Displays a labelled result for inspection.
```

In [81]:
for number in [1, 2, 3]:  # Repeats the indented steps for each item.
    print(number)  # Displays a labelled result for inspection.

1
2
3


### Example 2.11.6 — Explanation

**Status:** Diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 1).

```python
for number in [1, 2, 3]:  # Repeats the indented steps for each item.
```

In [82]:
example_status = "Example 2.11.6: diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 1)"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.11.6: diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 1)


### Example 2.11.7 — 13.2 Looping through strings

**Status:** Runnable — audited independently.

```python
topics = ["Cycling", "Public Transport", "Accessibility"]  # Stores the value needed by later steps.

for topic in topics:  # Repeats the indented steps for each item.
    print("Current topic:", topic)  # Displays a labelled result for inspection.
```

In [83]:
topics = ["Cycling", "Public Transport", "Accessibility"]  # Stores the value needed by later steps.

for topic in topics:  # Repeats the indented steps for each item.
    print("Current topic:", topic)  # Displays a labelled result for inspection.

Current topic: Cycling
Current topic: Public Transport
Current topic: Accessibility


### Example 2.11.8 — 13.3 The code after the loop

**Status:** Runnable — audited independently.

```python
topics = ["Cycling", "Public Transport", "Accessibility"]  # Stores the value needed by later steps.

for topic in topics:  # Repeats the indented steps for each item.
    print(topic)  # Displays a labelled result for inspection.

print("All topics processed")  # Displays a labelled result for inspection.
```

In [84]:
topics = ["Cycling", "Public Transport", "Accessibility"]  # Stores the value needed by later steps.

for topic in topics:  # Repeats the indented steps for each item.
    print(topic)  # Displays a labelled result for inspection.

print("All topics processed")  # Displays a labelled result for inspection.

Cycling
Public Transport
Accessibility
All topics processed


### Example 2.11.9 — 13.4 Using `range()`

**Status:** Runnable — audited independently.

```python
for number in range(5):  # Repeats the indented steps for each item.
    print(number)  # Displays a labelled result for inspection.
```

In [85]:
for number in range(5):  # Repeats the indented steps for each item.
    print(number)  # Displays a labelled result for inspection.

0
1
2
3
4


### Example 2.11.10 — 13.5 Starting and stopping a range

**Status:** Runnable — audited independently.

```python
for number in range(1, 6):  # Repeats the indented steps for each item.
    print(number)  # Displays a labelled result for inspection.
```

In [86]:
for number in range(1, 6):  # Repeats the indented steps for each item.
    print(number)  # Displays a labelled result for inspection.

1
2
3
4
5


### Example 2.11.11 — 13.6 Adding a step

**Status:** Runnable — audited independently.

```python
for number in range(0, 11, 2):  # Repeats the indented steps for each item.
    print(number)  # Displays a labelled result for inspection.
```

In [87]:
for number in range(0, 11, 2):  # Repeats the indented steps for each item.
    print(number)  # Displays a labelled result for inspection.

0
2
4
6
8
10


### Example 2.11.12 — 13.7 Repeating a message

**Status:** Runnable — audited independently.

```python
for repetition in range(3):  # Repeats the indented steps for each item.
    print("Check the dataset")  # Displays a labelled result for inspection.
```

In [88]:
for repetition in range(3):  # Repeats the indented steps for each item.
    print("Check the dataset")  # Displays a labelled result for inspection.

Check the dataset
Check the dataset
Check the dataset


### Example 2.11.13 — 13.7 Repeating a message

**Status:** Runnable — audited independently.

```python
for _ in range(3):  # Repeats the indented steps for each item.
    print("Check the dataset")  # Displays a labelled result for inspection.
```

In [89]:
for _ in range(3):  # Repeats the indented steps for each item.
    print("Check the dataset")  # Displays a labelled result for inspection.

Check the dataset
Check the dataset
Check the dataset


### Example 2.11.14 — 13.8 Conditions inside a loop

**Status:** Runnable — audited independently.

```python
engagement_values = [35, 120, 240, 80]  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    if engagement >= 200:  # Starts a branch when this condition is true.
        print(engagement, "is high")  # Displays a labelled result for inspection.
    elif engagement >= 100:  # Checks another condition after earlier branches were false.
        print(engagement, "is medium")  # Displays a labelled result for inspection.
    else:  # Starts the fallback branch.
        print(engagement, "is low")  # Displays a labelled result for inspection.
```

In [90]:
engagement_values = [35, 120, 240, 80]  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    if engagement >= 200:  # Starts a branch when this condition is true.
        print(engagement, "is high")  # Displays a labelled result for inspection.
    elif engagement >= 100:  # Checks another condition after earlier branches were false.
        print(engagement, "is medium")  # Displays a labelled result for inspection.
    else:  # Starts the fallback branch.
        print(engagement, "is low")  # Displays a labelled result for inspection.

35 is low
120 is medium
240 is high
80 is low


### Example 2.11.15 — 13.9 Counting values that meet a condition

**Status:** Runnable — audited independently.

```python
engagement_values = [35, 120, 240, 80, 310]  # Stores the value needed by later steps.
high_count = 0  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    if engagement >= 200:  # Starts a branch when this condition is true.
        high_count = high_count + 1  # Stores the value needed by later steps.

print("High-engagement records:", high_count)  # Displays a labelled result for inspection.
```

In [91]:
engagement_values = [35, 120, 240, 80, 310]  # Stores the value needed by later steps.
high_count = 0  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    if engagement >= 200:  # Starts a branch when this condition is true.
        high_count = high_count + 1  # Stores the value needed by later steps.

print("High-engagement records:", high_count)  # Displays a labelled result for inspection.

High-engagement records: 2


### Example 2.11.16 — Step-by-step explanation

**Status:** Runnable — audited independently.

```python
high_count = 0  # Stores the value needed by later steps.
```

In [92]:
high_count = 0  # Stores the value needed by later steps.

### Example 2.11.17 — Step-by-step explanation

**Status:** Diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 1).

```python
for engagement in engagement_values:  # Repeats the indented steps for each item.
```

In [93]:
example_status = "Example 2.11.17: diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 1)"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.11.17: diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 1)


### Example 2.11.18 — Step-by-step explanation

**Status:** Diagnostic — deliberate or partial syntax (expected an indented block after 'if' statement on line 1).

```python
if engagement >= 200:  # Starts a branch when this condition is true.
```

In [94]:
example_status = "Example 2.11.18: diagnostic — deliberate or partial syntax (expected an indented block after 'if' statement on line 1)"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.11.18: diagnostic — deliberate or partial syntax (expected an indented block after 'if' statement on line 1)


### Example 2.11.19 — Step-by-step explanation

**Status:** Diagnostic — NameError: name 'high_count' is not defined.

```python
high_count = high_count + 1  # Stores the value needed by later steps.
```

In [95]:
example_status = "Example 2.11.19: diagnostic — NameError: name 'high_count' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.11.19: diagnostic — NameError: name 'high_count' is not defined


### Example 2.11.20 — Step-by-step explanation

**Status:** Diagnostic — NameError: name 'high_count' is not defined.

```python
high_count += 1  # Stores the value needed by later steps.
```

In [96]:
example_status = "Example 2.11.20: diagnostic — NameError: name 'high_count' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.11.20: diagnostic — NameError: name 'high_count' is not defined


### Example 2.11.21 — 13.10 Accumulating a total

**Status:** Runnable — audited independently.

```python
engagement_values = [35, 120, 240, 80]  # Stores the value needed by later steps.
total_engagement = 0  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    total_engagement = total_engagement + engagement  # Stores the value needed by later steps.

print("Total engagement:", total_engagement)  # Displays a labelled result for inspection.
```

In [97]:
engagement_values = [35, 120, 240, 80]  # Stores the value needed by later steps.
total_engagement = 0  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    total_engagement = total_engagement + engagement  # Stores the value needed by later steps.

print("Total engagement:", total_engagement)  # Displays a labelled result for inspection.

Total engagement: 475


### Example 2.11.22 — 13.10 Accumulating a total

**Status:** Diagnostic — NameError: name 'total_engagement' is not defined.

```python
average_engagement = total_engagement / len(engagement_values)  # Stores the value needed by later steps.
print("Average engagement:", average_engagement)  # Displays a labelled result for inspection.
```

In [98]:
example_status = "Example 2.11.22: diagnostic — NameError: name 'total_engagement' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.11.22: diagnostic — NameError: name 'total_engagement' is not defined


### Example 2.11.23 — 13.11 Deliberate indentation error

**Status:** Diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 3).

```python
topics = ["Cycling", "Accessibility"]  # Stores the value needed by later steps.

for topic in topics:  # Repeats the indented steps for each item.
print(topic)  # Displays a labelled result for inspection.
```

In [99]:
example_status = "Example 2.11.23: diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 3)"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.11.23: diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 3)


### Example 2.11.24 — 13.11 Deliberate indentation error

**Status:** Runnable — audited independently.

```python
topics = ["Cycling", "Accessibility"]  # Stores the value needed by later steps.

for topic in topics:  # Repeats the indented steps for each item.
    print(topic)  # Displays a labelled result for inspection.
```

In [100]:
topics = ["Cycling", "Accessibility"]  # Stores the value needed by later steps.

for topic in topics:  # Repeats the indented steps for each item.
    print(topic)  # Displays a labelled result for inspection.

Cycling
Accessibility


### Example 2.11.25 — Practice checkpoint 6

**Status:** Runnable — audited independently.

```python
topics = ["Cycling", "Parking", "Accessibility"]  # Stores the value needed by later steps.
```

In [101]:
topics = ["Cycling", "Parking", "Accessibility"]  # Stores the value needed by later steps.

### Example 2.11.26 — Practice checkpoint 6

**Status:** Runnable — audited independently.

```python
topics = ["Cycling", "Parking", "Accessibility"]  # Stores the value needed by later steps.

for topic in topics:  # Repeats the indented steps for each item.
    print("Topic under review:", topic)  # Displays a labelled result for inspection.
```

In [102]:
topics = ["Cycling", "Parking", "Accessibility"]  # Stores the value needed by later steps.

for topic in topics:  # Repeats the indented steps for each item.
    print("Topic under review:", topic)  # Displays a labelled result for inspection.

Topic under review: Cycling
Topic under review: Parking
Topic under review: Accessibility


## Tutorial 2.12

### Example 2.12.1 — 14.1 Countdown example

**Status:** Manual — condition-controlled loop to run deliberately.

```python
number = 5  # Stores the value needed by later steps.

while number > 0:  # Repeats the indented steps while the condition remains true.
    print(number)  # Displays a labelled result for inspection.
    number = number - 1  # Stores the value needed by later steps.

print("Finished")  # Displays a labelled result for inspection.
```

In [103]:
example_status = 'Example 2.12.1: manual — condition-controlled loop to run deliberately'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.12.1: manual — condition-controlled loop to run deliberately


### Example 2.12.2 — Three essential parts

**Status:** Runnable — audited independently.

```python
number = 5  # Stores the value needed by later steps.
```

In [104]:
number = 5  # Stores the value needed by later steps.

### Example 2.12.3 — Three essential parts

**Status:** Diagnostic — deliberate or partial syntax (expected an indented block after 'while' statement on line 1).

```python
while number > 0:  # Repeats the indented steps while the condition remains true.
```

In [105]:
example_status = "Example 2.12.3: diagnostic — deliberate or partial syntax (expected an indented block after 'while' statement on line 1)"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.12.3: diagnostic — deliberate or partial syntax (expected an indented block after 'while' statement on line 1)


### Example 2.12.4 — Three essential parts

**Status:** Diagnostic — NameError: name 'number' is not defined.

```python
number = number - 1  # Stores the value needed by later steps.
```

In [106]:
example_status = "Example 2.12.4: diagnostic — NameError: name 'number' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.12.4: diagnostic — NameError: name 'number' is not defined


### Example 2.12.5 — 14.2 An infinite loop

**Status:** Manual — condition-controlled loop to run deliberately.

```python
number = 5  # Stores the value needed by later steps.

while number > 0:  # Repeats the indented steps while the condition remains true.
    print(number)  # Displays a labelled result for inspection.
```

In [107]:
example_status = 'Example 2.12.5: manual — condition-controlled loop to run deliberately'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.12.5: manual — condition-controlled loop to run deliberately


### Example 2.12.6 — Repair

**Status:** Manual — condition-controlled loop to run deliberately.

```python
number = 5  # Stores the value needed by later steps.

while number > 0:  # Repeats the indented steps while the condition remains true.
    print(number)  # Displays a labelled result for inspection.
    number = number - 1  # Stores the value needed by later steps.
```

In [108]:
example_status = 'Example 2.12.6: manual — condition-controlled loop to run deliberately'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.12.6: manual — condition-controlled loop to run deliberately


### Example 2.12.7 — 14.3 A loop that never starts

**Status:** Manual — condition-controlled loop to run deliberately.

```python
number = 0  # Stores the value needed by later steps.

while number > 0:  # Repeats the indented steps while the condition remains true.
    print(number)  # Displays a labelled result for inspection.

print("Finished")  # Displays a labelled result for inspection.
```

In [109]:
example_status = 'Example 2.12.7: manual — condition-controlled loop to run deliberately'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.12.7: manual — condition-controlled loop to run deliberately


### Example 2.12.8 — 14.4 Repeating until valid input

**Status:** Manual — interactive input.

```python
valid_input = False  # Stores the value needed by later steps.

while not valid_input:  # Repeats the indented steps while the condition remains true.
    answer = input("Type yes or no: ").strip().lower()  # Stores the value needed by later steps.

    if answer == "yes" or answer == "no":  # Starts a branch when this condition is true.
        valid_input = True  # Stores the value needed by later steps.
    else:  # Starts the fallback branch.
        print("Please type exactly yes or no")  # Displays a labelled result for inspection.

print("Accepted:", answer)  # Displays a labelled result for inspection.
```

In [110]:
example_status = 'Example 2.12.8: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.12.8: manual — interactive input


### Example 2.12.9 — 14.5 `for` or `while`?

**Status:** Diagnostic — NameError: name 'topics' is not defined.

```python
for topic in topics:  # Repeats the indented steps for each item.
    print(topic)  # Displays a labelled result for inspection.
```

In [111]:
example_status = "Example 2.12.9: diagnostic — NameError: name 'topics' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.12.9: diagnostic — NameError: name 'topics' is not defined


### Example 2.12.10 — 14.5 `for` or `while`?

**Status:** Manual — condition-controlled loop to run deliberately.

```python
while not valid_input:  # Repeats the indented steps while the condition remains true.
    ...  # Runs this documented step in the solution.
```

In [112]:
example_status = 'Example 2.12.10: manual — condition-controlled loop to run deliberately'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.12.10: manual — condition-controlled loop to run deliberately


### Example 2.12.11 — 15.1 `break`

**Status:** Runnable — audited independently.

```python
topics = ["Cycling", "Accessibility", "STOP", "Parking"]  # Stores the value needed by later steps.

for topic in topics:  # Repeats the indented steps for each item.
    if topic == "STOP":  # Starts a branch when this condition is true.
        break  # Stops the nearest loop after its exit condition is met.

    print(topic)  # Displays a labelled result for inspection.

print("Loop ended")  # Displays a labelled result for inspection.
```

In [113]:
topics = ["Cycling", "Accessibility", "STOP", "Parking"]  # Stores the value needed by later steps.

for topic in topics:  # Repeats the indented steps for each item.
    if topic == "STOP":  # Starts a branch when this condition is true.
        break  # Stops the nearest loop after its exit condition is met.

    print(topic)  # Displays a labelled result for inspection.

print("Loop ended")  # Displays a labelled result for inspection.

Cycling
Accessibility
Loop ended


### Example 2.12.12 — 15.2 `continue`

**Status:** Runnable — audited independently.

```python
values = [120, None, 75, 240]  # Stores the value needed by later steps.

for value in values:  # Repeats the indented steps for each item.
    if value is None:  # Starts a branch when this condition is true.
        continue  # Moves safely to the next loop iteration.

    print("Valid value:", value)  # Displays a labelled result for inspection.
```

In [114]:
values = [120, None, 75, 240]  # Stores the value needed by later steps.

for value in values:  # Repeats the indented steps for each item.
    if value is None:  # Starts a branch when this condition is true.
        continue  # Moves safely to the next loop iteration.

    print("Valid value:", value)  # Displays a labelled result for inspection.

Valid value: 120
Valid value: 75
Valid value: 240


## Tutorial 2.13

### Example 2.13.1 — 16.1 Defining and calling a function

**Status:** Runnable — audited independently.

```python
def show_welcome():  # Defines a reusable function with explicit inputs.
    print("Welcome to the data-quality checker")  # Displays a labelled result for inspection.

show_welcome()  # Runs this documented step in the solution.
```

In [115]:
def show_welcome():  # Defines a reusable function with explicit inputs.
    print("Welcome to the data-quality checker")  # Displays a labelled result for inspection.

show_welcome()  # Runs this documented step in the solution.

Welcome to the data-quality checker


### Example 2.13.2 — Explanation

**Status:** Diagnostic — deliberate or partial syntax (expected an indented block after function definition on line 1).

```python
def show_welcome():  # Defines a reusable function with explicit inputs.
```

In [116]:
example_status = 'Example 2.13.2: diagnostic — deliberate or partial syntax (expected an indented block after function definition on line 1)'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.2: diagnostic — deliberate or partial syntax (expected an indented block after function definition on line 1)


### Example 2.13.3 — Explanation

**Status:** Diagnostic — deliberate or partial syntax (unexpected indent).

```python
    print("Welcome to the data-quality checker")  # Displays a labelled result for inspection.
```

In [117]:
example_status = 'Example 2.13.3: diagnostic — deliberate or partial syntax (unexpected indent)'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.3: diagnostic — deliberate or partial syntax (unexpected indent)


### Example 2.13.4 — Explanation

**Status:** Diagnostic — NameError: name 'show_welcome' is not defined.

```python
show_welcome()  # Runs this documented step in the solution.
```

In [118]:
example_status = "Example 2.13.4: diagnostic — NameError: name 'show_welcome' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.4: diagnostic — NameError: name 'show_welcome' is not defined


### Example 2.13.5 — 16.2 Meaningful function names

**Status:** Diagnostic — NameError: name 'calculate_percentage' is not defined.

```python
calculate_percentage()  # Runs this documented step in the solution.
classify_engagement()  # Runs this documented step in the solution.
check_missing_values()  # Runs this documented step in the solution.
show_summary()  # Runs this documented step in the solution.
```

In [119]:
example_status = "Example 2.13.5: diagnostic — NameError: name 'calculate_percentage' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.5: diagnostic — NameError: name 'calculate_percentage' is not defined


### Example 2.13.6 — 16.2 Meaningful function names

**Status:** Diagnostic — NameError: name 'do_it' is not defined.

```python
do_it()  # Runs this documented step in the solution.
thing()  # Runs this documented step in the solution.
f1()  # Runs this documented step in the solution.
xyz()  # Runs this documented step in the solution.
```

In [120]:
example_status = "Example 2.13.6: diagnostic — NameError: name 'do_it' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.6: diagnostic — NameError: name 'do_it' is not defined


### Example 2.13.7 — 16.3 Parameters and arguments

**Status:** Runnable — audited independently.

```python
def greet_actor(actor_name):  # Defines a reusable function with explicit inputs.
    print("Record submitted by:", actor_name)  # Displays a labelled result for inspection.

greet_actor("Green Streets Association")  # Runs this documented step in the solution.
greet_actor("Local Business Council")  # Runs this documented step in the solution.
```

In [121]:
def greet_actor(actor_name):  # Defines a reusable function with explicit inputs.
    print("Record submitted by:", actor_name)  # Displays a labelled result for inspection.

greet_actor("Green Streets Association")  # Runs this documented step in the solution.
greet_actor("Local Business Council")  # Runs this documented step in the solution.

Record submitted by: Green Streets Association
Record submitted by: Local Business Council


### Example 2.13.8 — Terminology

**Status:** Diagnostic — deliberate or partial syntax (expected an indented block after function definition on line 1).

```python
def greet_actor(actor_name):  # Defines a reusable function with explicit inputs.
```

In [122]:
example_status = 'Example 2.13.8: diagnostic — deliberate or partial syntax (expected an indented block after function definition on line 1)'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.8: diagnostic — deliberate or partial syntax (expected an indented block after function definition on line 1)


### Example 2.13.9 — Terminology

**Status:** Diagnostic — NameError: name 'greet_actor' is not defined.

```python
greet_actor("Green Streets Association")  # Runs this documented step in the solution.
```

In [123]:
example_status = "Example 2.13.9: diagnostic — NameError: name 'greet_actor' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.9: diagnostic — NameError: name 'greet_actor' is not defined


### Example 2.13.10 — 16.4 Multiple parameters

**Status:** Runnable — audited independently.

```python
def show_record(actor_name, topic, engagement):  # Defines a reusable function with explicit inputs.
    print("Actor:", actor_name)  # Displays a labelled result for inspection.
    print("Topic:", topic)  # Displays a labelled result for inspection.
    print("Engagement:", engagement)  # Displays a labelled result for inspection.

show_record("Cycling Alliance", "Cycling", 245)  # Runs this documented step in the solution.
```

In [124]:
def show_record(actor_name, topic, engagement):  # Defines a reusable function with explicit inputs.
    print("Actor:", actor_name)  # Displays a labelled result for inspection.
    print("Topic:", topic)  # Displays a labelled result for inspection.
    print("Engagement:", engagement)  # Displays a labelled result for inspection.

show_record("Cycling Alliance", "Cycling", 245)  # Runs this documented step in the solution.

Actor: Cycling Alliance
Topic: Cycling
Engagement: 245


### Example 2.13.11 — 16.5 Returning a value

**Status:** Runnable — audited independently.

```python
def calculate_missing_percentage(missing_values, total_values):  # Defines a reusable function with explicit inputs.
    percentage = missing_values / total_values * 100  # Stores the value needed by later steps.
    return percentage  # Returns the result to the calling code.

result = calculate_missing_percentage(18, 200)  # Stores the value needed by later steps.
print(result)  # Displays a labelled result for inspection.
```

In [125]:
def calculate_missing_percentage(missing_values, total_values):  # Defines a reusable function with explicit inputs.
    percentage = missing_values / total_values * 100  # Stores the value needed by later steps.
    return percentage  # Returns the result to the calling code.

result = calculate_missing_percentage(18, 200)  # Stores the value needed by later steps.
print(result)  # Displays a labelled result for inspection.

9.0


### Example 2.13.12 — Explanation

**Status:** Diagnostic — SyntaxError: 'return' outside function.

```python
return percentage  # Returns the result to the calling code.
```

In [126]:
example_status = "Example 2.13.12: diagnostic — SyntaxError: 'return' outside function"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.12: diagnostic — SyntaxError: 'return' outside function


### Example 2.13.13 — Explanation

**Status:** Diagnostic — NameError: name 'calculate_missing_percentage' is not defined.

```python
result = calculate_missing_percentage(18, 200)  # Stores the value needed by later steps.
```

In [127]:
example_status = "Example 2.13.13: diagnostic — NameError: name 'calculate_missing_percentage' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.13: diagnostic — NameError: name 'calculate_missing_percentage' is not defined


### Example 2.13.14 — 16.6 `print()` and `return` are not the same

**Status:** Runnable — audited independently.

```python
def calculate_total(a, b):  # Defines a reusable function with explicit inputs.
    print(a + b)  # Displays a labelled result for inspection.
```

In [128]:
def calculate_total(a, b):  # Defines a reusable function with explicit inputs.
    print(a + b)  # Displays a labelled result for inspection.

### Example 2.13.15 — 16.6 `print()` and `return` are not the same

**Status:** Runnable — audited independently.

```python
def calculate_total(a, b):  # Defines a reusable function with explicit inputs.
    return a + b  # Returns the result to the calling code.
```

In [129]:
def calculate_total(a, b):  # Defines a reusable function with explicit inputs.
    return a + b  # Returns the result to the calling code.

### Example 2.13.16 — 16.6 `print()` and `return` are not the same

**Status:** Diagnostic — NameError: name 'calculate_total' is not defined.

```python
total = calculate_total(5, 7)  # Stores the value needed by later steps.
average = total / 2  # Stores the value needed by later steps.

print(average)  # Displays a labelled result for inspection.
```

In [130]:
example_status = "Example 2.13.16: diagnostic — NameError: name 'calculate_total' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.16: diagnostic — NameError: name 'calculate_total' is not defined


### Example 2.13.17 — 16.7 A function with conditional logic

**Status:** Runnable — audited independently.

```python
def classify_engagement(engagement):  # Defines a reusable function with explicit inputs.
    if engagement >= 200:  # Starts a branch when this condition is true.
        return "High"  # Returns the result to the calling code.
    elif engagement >= 100:  # Checks another condition after earlier branches were false.
        return "Medium"  # Returns the result to the calling code.
    else:  # Starts the fallback branch.
        return "Low"  # Returns the result to the calling code.

print(classify_engagement(240))  # Displays a labelled result for inspection.
print(classify_engagement(130))  # Displays a labelled result for inspection.
print(classify_engagement(45))  # Displays a labelled result for inspection.
```

In [131]:
def classify_engagement(engagement):  # Defines a reusable function with explicit inputs.
    if engagement >= 200:  # Starts a branch when this condition is true.
        return "High"  # Returns the result to the calling code.
    elif engagement >= 100:  # Checks another condition after earlier branches were false.
        return "Medium"  # Returns the result to the calling code.
    else:  # Starts the fallback branch.
        return "Low"  # Returns the result to the calling code.

print(classify_engagement(240))  # Displays a labelled result for inspection.
print(classify_engagement(130))  # Displays a labelled result for inspection.
print(classify_engagement(45))  # Displays a labelled result for inspection.

High
Medium
Low


### Example 2.13.18 — 16.8 A function with validation

**Status:** Runnable — audited independently.

```python
def classify_percentage(percentage):  # Defines a reusable function with explicit inputs.
    if percentage < 0 or percentage > 100:  # Starts a branch when this condition is true.
        return "Invalid percentage"  # Returns the result to the calling code.
    elif percentage > 15:  # Checks another condition after earlier branches were false.
        return "Substantial missingness"  # Returns the result to the calling code.
    elif percentage > 5:  # Checks another condition after earlier branches were false.
        return "Moderate missingness"  # Returns the result to the calling code.
    else:  # Starts the fallback branch.
        return "Minor missingness"  # Returns the result to the calling code.

print(classify_percentage(18))  # Displays a labelled result for inspection.
print(classify_percentage(4))  # Displays a labelled result for inspection.
print(classify_percentage(120))  # Displays a labelled result for inspection.
```

In [132]:
def classify_percentage(percentage):  # Defines a reusable function with explicit inputs.
    if percentage < 0 or percentage > 100:  # Starts a branch when this condition is true.
        return "Invalid percentage"  # Returns the result to the calling code.
    elif percentage > 15:  # Checks another condition after earlier branches were false.
        return "Substantial missingness"  # Returns the result to the calling code.
    elif percentage > 5:  # Checks another condition after earlier branches were false.
        return "Moderate missingness"  # Returns the result to the calling code.
    else:  # Starts the fallback branch.
        return "Minor missingness"  # Returns the result to the calling code.

print(classify_percentage(18))  # Displays a labelled result for inspection.
print(classify_percentage(4))  # Displays a labelled result for inspection.
print(classify_percentage(120))  # Displays a labelled result for inspection.

Substantial missingness
Minor missingness
Invalid percentage


### Example 2.13.19 — 16.9 Local and global variables

**Status:** Runnable — audited independently.

```python
status = "Global status"  # Stores the value needed by later steps.

def show_status():  # Defines a reusable function with explicit inputs.
    status = "Local status"  # Stores the value needed by later steps.
    print(status)  # Displays a labelled result for inspection.

show_status()  # Runs this documented step in the solution.
print(status)  # Displays a labelled result for inspection.
```

In [133]:
status = "Global status"  # Stores the value needed by later steps.

def show_status():  # Defines a reusable function with explicit inputs.
    status = "Local status"  # Stores the value needed by later steps.
    print(status)  # Displays a labelled result for inspection.

show_status()  # Runs this documented step in the solution.
print(status)  # Displays a labelled result for inspection.

Local status
Global status


### Example 2.13.20 — Error 1: Function not called

**Status:** Runnable — audited independently.

```python
def show_message():  # Defines a reusable function with explicit inputs.
    print("Hello")  # Displays a labelled result for inspection.
```

In [134]:
def show_message():  # Defines a reusable function with explicit inputs.
    print("Hello")  # Displays a labelled result for inspection.

### Example 2.13.21 — Error 1: Function not called

**Status:** Runnable — audited independently.

```python
def show_message():  # Defines a reusable function with explicit inputs.
    print("Hello")  # Displays a labelled result for inspection.

show_message()  # Runs this documented step in the solution.
```

In [135]:
def show_message():  # Defines a reusable function with explicit inputs.
    print("Hello")  # Displays a labelled result for inspection.

show_message()  # Runs this documented step in the solution.

Hello


### Example 2.13.22 — Error 2: Missing argument

**Status:** Diagnostic — TypeError: greet() missing 1 required positional argument: 'name'.

```python
def greet(name):  # Defines a reusable function with explicit inputs.
    print("Hello", name)  # Displays a labelled result for inspection.

greet()  # Runs this documented step in the solution.
```

In [136]:
example_status = "Example 2.13.22: diagnostic — TypeError: greet() missing 1 required positional argument: 'name'"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.22: diagnostic — TypeError: greet() missing 1 required positional argument: 'name'


### Example 2.13.23 — Error 2: Missing argument

**Status:** Diagnostic — NameError: name 'greet' is not defined.

```python
greet("Amina")  # Runs this documented step in the solution.
```

In [137]:
example_status = "Example 2.13.23: diagnostic — NameError: name 'greet' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.23: diagnostic — NameError: name 'greet' is not defined


### Example 2.13.24 — Error 3: Incorrect indentation

**Status:** Diagnostic — deliberate or partial syntax (expected an indented block after function definition on line 1).

```python
def greet(name):  # Defines a reusable function with explicit inputs.
print("Hello", name)  # Displays a labelled result for inspection.
```

In [138]:
example_status = 'Example 2.13.24: diagnostic — deliberate or partial syntax (expected an indented block after function definition on line 1)'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.13.24: diagnostic — deliberate or partial syntax (expected an indented block after function definition on line 1)


### Example 2.13.25 — Error 3: Incorrect indentation

**Status:** Runnable — audited independently.

```python
def greet(name):  # Defines a reusable function with explicit inputs.
    print("Hello", name)  # Displays a labelled result for inspection.
```

In [139]:
def greet(name):  # Defines a reusable function with explicit inputs.
    print("Hello", name)  # Displays a labelled result for inspection.

### Example 2.13.26 — Practice checkpoint 7

**Status:** Runnable — audited independently.

```python
def calculate_completion_rate(complete_records, total_records):  # Defines a reusable function with explicit inputs.
    rate = complete_records / total_records * 100  # Stores the value needed by later steps.
    return rate  # Returns the result to the calling code.

result = calculate_completion_rate(180, 200)  # Stores the value needed by later steps.
print(result)  # Displays a labelled result for inspection.
```

In [140]:
def calculate_completion_rate(complete_records, total_records):  # Defines a reusable function with explicit inputs.
    rate = complete_records / total_records * 100  # Stores the value needed by later steps.
    return rate  # Returns the result to the calling code.

result = calculate_completion_rate(180, 200)  # Stores the value needed by later steps.
print(result)  # Displays a labelled result for inspection.

90.0


### Example 2.13.27 — 17.1 Apply one function to several values

**Status:** Runnable — audited independently.

```python
def classify_engagement(engagement):  # Defines a reusable function with explicit inputs.
    if engagement >= 200:  # Starts a branch when this condition is true.
        return "High"  # Returns the result to the calling code.
    elif engagement >= 100:  # Checks another condition after earlier branches were false.
        return "Medium"  # Returns the result to the calling code.
    else:  # Starts the fallback branch.
        return "Low"  # Returns the result to the calling code.

engagement_values = [35, 120, 240, 80]  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    category = classify_engagement(engagement)  # Stores the value needed by later steps.
    print(engagement, "->", category)  # Displays a labelled result for inspection.
```

In [141]:
def classify_engagement(engagement):  # Defines a reusable function with explicit inputs.
    if engagement >= 200:  # Starts a branch when this condition is true.
        return "High"  # Returns the result to the calling code.
    elif engagement >= 100:  # Checks another condition after earlier branches were false.
        return "Medium"  # Returns the result to the calling code.
    else:  # Starts the fallback branch.
        return "Low"  # Returns the result to the calling code.

engagement_values = [35, 120, 240, 80]  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    category = classify_engagement(engagement)  # Stores the value needed by later steps.
    print(engagement, "->", category)  # Displays a labelled result for inspection.

35 -> Low
120 -> Medium
240 -> High
80 -> Low


### Example 2.13.28 — 17.2 Count function results

**Status:** Runnable — audited independently.

```python
def classify_engagement(engagement):  # Defines a reusable function with explicit inputs.
    if engagement >= 200:  # Starts a branch when this condition is true.
        return "High"  # Returns the result to the calling code.
    elif engagement >= 100:  # Checks another condition after earlier branches were false.
        return "Medium"  # Returns the result to the calling code.
    else:  # Starts the fallback branch.
        return "Low"  # Returns the result to the calling code.

engagement_values = [35, 120, 240, 80, 310]  # Stores the value needed by later steps.
high_count = 0  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    category = classify_engagement(engagement)  # Stores the value needed by later steps.

    if category == "High":  # Starts a branch when this condition is true.
        high_count = high_count + 1  # Stores the value needed by later steps.

print("High-engagement count:", high_count)  # Displays a labelled result for inspection.
```

In [142]:
def classify_engagement(engagement):  # Defines a reusable function with explicit inputs.
    if engagement >= 200:  # Starts a branch when this condition is true.
        return "High"  # Returns the result to the calling code.
    elif engagement >= 100:  # Checks another condition after earlier branches were false.
        return "Medium"  # Returns the result to the calling code.
    else:  # Starts the fallback branch.
        return "Low"  # Returns the result to the calling code.

engagement_values = [35, 120, 240, 80, 310]  # Stores the value needed by later steps.
high_count = 0  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    category = classify_engagement(engagement)  # Stores the value needed by later steps.

    if category == "High":  # Starts a branch when this condition is true.
        high_count = high_count + 1  # Stores the value needed by later steps.

print("High-engagement count:", high_count)  # Displays a labelled result for inspection.

High-engagement count: 2


### Example 2.13.29 — 17.3 More advanced example: produce a simple report

**Status:** Runnable — audited independently.

```python
def classify_engagement(engagement):  # Defines a reusable function with explicit inputs.
    if engagement >= 200:  # Starts a branch when this condition is true.
        return "High"  # Returns the result to the calling code.
    elif engagement >= 100:  # Checks another condition after earlier branches were false.
        return "Medium"  # Returns the result to the calling code.
    else:  # Starts the fallback branch.
        return "Low"  # Returns the result to the calling code.


engagement_values = [35, 120, 240, 80, 310]  # Stores the value needed by later steps.

high_count = 0  # Stores the value needed by later steps.
medium_count = 0  # Stores the value needed by later steps.
low_count = 0  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    category = classify_engagement(engagement)  # Stores the value needed by later steps.

    if category == "High":  # Starts a branch when this condition is true.
        high_count = high_count + 1  # Stores the value needed by later steps.
    elif category == "Medium":  # Checks another condition after earlier branches were false.
        medium_count = medium_count + 1  # Stores the value needed by later steps.
    else:  # Starts the fallback branch.
        low_count = low_count + 1  # Stores the value needed by later steps.

print("Engagement report")  # Displays a labelled result for inspection.
print("-----------------")  # Displays a labelled result for inspection.
print("High:", high_count)  # Displays a labelled result for inspection.
print("Medium:", medium_count)  # Displays a labelled result for inspection.
print("Low:", low_count)  # Displays a labelled result for inspection.
```

In [143]:
def classify_engagement(engagement):  # Defines a reusable function with explicit inputs.
    if engagement >= 200:  # Starts a branch when this condition is true.
        return "High"  # Returns the result to the calling code.
    elif engagement >= 100:  # Checks another condition after earlier branches were false.
        return "Medium"  # Returns the result to the calling code.
    else:  # Starts the fallback branch.
        return "Low"  # Returns the result to the calling code.


engagement_values = [35, 120, 240, 80, 310]  # Stores the value needed by later steps.

high_count = 0  # Stores the value needed by later steps.
medium_count = 0  # Stores the value needed by later steps.
low_count = 0  # Stores the value needed by later steps.

for engagement in engagement_values:  # Repeats the indented steps for each item.
    category = classify_engagement(engagement)  # Stores the value needed by later steps.

    if category == "High":  # Starts a branch when this condition is true.
        high_count = high_count + 1  # Stores the value needed by later steps.
    elif category == "Medium":  # Checks another condition after earlier branches were false.
        medium_count = medium_count + 1  # Stores the value needed by later steps.
    else:  # Starts the fallback branch.
        low_count = low_count + 1  # Stores the value needed by later steps.

print("Engagement report")  # Displays a labelled result for inspection.
print("-----------------")  # Displays a labelled result for inspection.
print("High:", high_count)  # Displays a labelled result for inspection.
print("Medium:", medium_count)  # Displays a labelled result for inspection.
print("Low:", low_count)  # Displays a labelled result for inspection.

Engagement report
-----------------
High: 2
Medium: 1
Low: 2


## Tutorial 2.14

### Example 2.14.1 — 18.1 Importing a standard module

**Status:** Runnable — audited independently.

```python
import math  # Imports the named standard-library tool for this step.

result = math.sqrt(16)  # Stores the value needed by later steps.
print(result)  # Displays a labelled result for inspection.
```

In [144]:
import math  # Imports the named standard-library tool for this step.

result = math.sqrt(16)  # Stores the value needed by later steps.
print(result)  # Displays a labelled result for inspection.

4.0


### Example 2.14.2 — Explanation

**Status:** Runnable — audited independently.

```python
import math  # Imports the named standard-library tool for this step.
```

In [145]:
import math  # Imports the named standard-library tool for this step.

### Example 2.14.3 — Explanation

**Status:** Diagnostic — NameError: name 'math' is not defined. Did you forget to import 'math'?.

```python
math.sqrt(16)  # Runs this documented step in the solution.
```

In [146]:
example_status = "Example 2.14.3: diagnostic — NameError: name 'math' is not defined. Did you forget to import 'math'?"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.3: diagnostic — NameError: name 'math' is not defined. Did you forget to import 'math'?


### Example 2.14.4 — 18.2 Importing one item

**Status:** Runnable — audited independently.

```python
from math import sqrt  # Imports the named standard-library tool for this step.

result = sqrt(25)  # Stores the value needed by later steps.
print(result)  # Displays a labelled result for inspection.
```

In [147]:
from math import sqrt  # Imports the named standard-library tool for this step.

result = sqrt(25)  # Stores the value needed by later steps.
print(result)  # Displays a labelled result for inspection.

5.0


### Example 2.14.5 — 18.2 Importing one item

**Status:** Diagnostic — deliberate import or function error.

```python
math.sqrt()  # Runs this documented step in the solution.
```

In [148]:
example_status = 'Example 2.14.5: diagnostic — deliberate import or function error'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.5: diagnostic — deliberate import or function error


### Example 2.14.6 — 18.3 Using an alias

**Status:** Runnable — audited independently.

```python
import math as m  # Imports the named standard-library tool for this step.

print(m.sqrt(36))  # Displays a labelled result for inspection.
```

In [149]:
import math as m  # Imports the named standard-library tool for this step.

print(m.sqrt(36))  # Displays a labelled result for inspection.

6.0


### Example 2.14.7 — 18.3 Using an alias

**Status:** Runnable — audited independently.

```python
import math as banana  # Imports the named standard-library tool for this step.
```

In [150]:
import math as banana  # Imports the named standard-library tool for this step.

### Example 2.14.8 — 18.4 Example with the `random` module

**Status:** Runnable — audited independently.

```python
import random  # Imports the named standard-library tool for this step.

number = random.randint(1, 5)  # Stores the value needed by later steps.
print(number)  # Displays a labelled result for inspection.
```

In [151]:
import random  # Imports the named standard-library tool for this step.

number = random.randint(1, 5)  # Stores the value needed by later steps.
print(number)  # Displays a labelled result for inspection.

4


### Example 2.14.9 — 18.5 Import errors

**Status:** Diagnostic — deliberate import or function error.

```python
import maths  # Imports the named standard-library tool for this step.
```

In [152]:
example_status = 'Example 2.14.9: diagnostic — deliberate import or function error'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.9: diagnostic — deliberate import or function error


### Example 2.14.10 — 18.5 Import errors

**Status:** Runnable — audited independently.

```python
import math  # Imports the named standard-library tool for this step.
```

In [153]:
import math  # Imports the named standard-library tool for this step.

### Example 2.14.11 — 18.5 Import errors

**Status:** Diagnostic — deliberate import or function error.

```python
import math  # Imports the named standard-library tool for this step.

print(math.squareroot(16))  # Displays a labelled result for inspection.
```

In [154]:
example_status = 'Example 2.14.11: diagnostic — deliberate import or function error'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.11: diagnostic — deliberate import or function error


### Example 2.14.12 — 18.5 Import errors

**Status:** Diagnostic — NameError: name 'math' is not defined. Did you forget to import 'math'?.

```python
print(math.sqrt(16))  # Displays a labelled result for inspection.
```

In [155]:
example_status = "Example 2.14.12: diagnostic — NameError: name 'math' is not defined. Did you forget to import 'math'?"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.12: diagnostic — NameError: name 'math' is not defined. Did you forget to import 'math'?


### Example 2.14.13 — 19.1 `SyntaxError`

**Status:** Diagnostic — deliberate or partial syntax (expected ':').

```python
if engagement > 100  # Starts a branch when this condition is true.
    print("High")  # Displays a labelled result for inspection.
```

In [156]:
example_status = "Example 2.14.13: diagnostic — deliberate or partial syntax (expected ':')"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.13: diagnostic — deliberate or partial syntax (expected ':')


### Example 2.14.14 — 19.1 `SyntaxError`

**Status:** Diagnostic — NameError: name 'engagement' is not defined.

```python
if engagement > 100:  # Starts a branch when this condition is true.
    print("High")  # Displays a labelled result for inspection.
```

In [157]:
example_status = "Example 2.14.14: diagnostic — NameError: name 'engagement' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.14: diagnostic — NameError: name 'engagement' is not defined


### Example 2.14.15 — 19.2 `IndentationError`

**Status:** Diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 1).

```python
for topic in topics:  # Repeats the indented steps for each item.
print(topic)  # Displays a labelled result for inspection.
```

In [158]:
example_status = "Example 2.14.15: diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 1)"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.15: diagnostic — deliberate or partial syntax (expected an indented block after 'for' statement on line 1)


### Example 2.14.16 — 19.2 `IndentationError`

**Status:** Diagnostic — NameError: name 'topics' is not defined.

```python
for topic in topics:  # Repeats the indented steps for each item.
    print(topic)  # Displays a labelled result for inspection.
```

In [159]:
example_status = "Example 2.14.16: diagnostic — NameError: name 'topics' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.16: diagnostic — NameError: name 'topics' is not defined


### Example 2.14.17 — 19.3 `NameError`

**Status:** Diagnostic — NameError: name 'engagement' is not defined. Did you mean: 'engagment'?.

```python
engagment = 120  # Stores the value needed by later steps.
print(engagement)  # Displays a labelled result for inspection.
```

In [160]:
example_status = "Example 2.14.17: diagnostic — NameError: name 'engagement' is not defined. Did you mean: 'engagment'?"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.17: diagnostic — NameError: name 'engagement' is not defined. Did you mean: 'engagment'?


### Example 2.14.18 — 19.3 `NameError`

**Status:** Runnable — audited independently.

```python
engagement = 120  # Stores the value needed by later steps.
print(engagement)  # Displays a labelled result for inspection.
```

In [161]:
engagement = 120  # Stores the value needed by later steps.
print(engagement)  # Displays a labelled result for inspection.

120


### Example 2.14.19 — 19.4 `TypeError`

**Status:** Diagnostic — TypeError: can only concatenate str (not "int") to str.

```python
engagement = "120"  # Stores the value needed by later steps.
result = engagement + 10  # Stores the value needed by later steps.
```

In [162]:
example_status = 'Example 2.14.19: diagnostic — TypeError: can only concatenate str (not "int") to str'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.19: diagnostic — TypeError: can only concatenate str (not "int") to str


### Example 2.14.20 — 19.4 `TypeError`

**Status:** Runnable — audited independently.

```python
engagement = "120"  # Stores the value needed by later steps.
result = int(engagement) + 10  # Stores the value needed by later steps.

print(result)  # Displays a labelled result for inspection.
```

In [163]:
engagement = "120"  # Stores the value needed by later steps.
result = int(engagement) + 10  # Stores the value needed by later steps.

print(result)  # Displays a labelled result for inspection.

130


### Example 2.14.21 — 19.5 `ValueError`

**Status:** Diagnostic — ValueError: invalid literal for int() with base 10: 'high'.

```python
engagement = int("high")  # Stores the value needed by later steps.
```

In [164]:
example_status = "Example 2.14.21: diagnostic — ValueError: invalid literal for int() with base 10: 'high'"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.21: diagnostic — ValueError: invalid literal for int() with base 10: 'high'


### Example 2.14.22 — 19.5 `ValueError`

**Status:** Manual — interactive input.

```python
try:  # Starts a protected conversion or calculation block.
    engagement = int(input("Enter engagement: "))  # Stores the value needed by later steps.
except ValueError:  # Handles the stated expected error.
    print("Enter a whole number")  # Displays a labelled result for inspection.
```

In [165]:
example_status = 'Example 2.14.22: manual — interactive input'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.22: manual — interactive input


### Example 2.14.23 — 19.6 `ModuleNotFoundError`

**Status:** Diagnostic — deliberate import or function error.

```python
import statisticss  # Imports the named standard-library tool for this step.
```

In [166]:
example_status = 'Example 2.14.23: diagnostic — deliberate import or function error'  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.23: diagnostic — deliberate import or function error


### Example 2.14.24 — 19.6 `ModuleNotFoundError`

**Status:** Runnable — audited independently.

```python
import statistics  # Imports the named standard-library tool for this step.
```

In [167]:
import statistics  # Imports the named standard-library tool for this step.

### Example 2.14.25 — 19.7 `TypeError` from a missing function argument

**Status:** Diagnostic — TypeError: classify() missing 1 required positional argument: 'value'.

```python
def classify(value):  # Defines a reusable function with explicit inputs.
    return value > 100  # Returns the result to the calling code.

result = classify()  # Stores the value needed by later steps.
```

In [168]:
example_status = "Example 2.14.25: diagnostic — TypeError: classify() missing 1 required positional argument: 'value'"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.25: diagnostic — TypeError: classify() missing 1 required positional argument: 'value'


### Example 2.14.26 — 19.7 `TypeError` from a missing function argument

**Status:** Diagnostic — NameError: name 'classify' is not defined.

```python
result = classify(120)  # Stores the value needed by later steps.
```

In [169]:
example_status = "Example 2.14.26: diagnostic — NameError: name 'classify' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.26: diagnostic — NameError: name 'classify' is not defined


### Example 2.14.27 — 19.8 Logic errors

**Status:** Runnable — audited independently.

```python
missing_values = 10  # Stores the value needed by later steps.
total_values = 200  # Stores the value needed by later steps.

missing_percentage = total_values / missing_values * 100  # Stores the value needed by later steps.
print(missing_percentage)  # Displays a labelled result for inspection.
```

In [170]:
missing_values = 10  # Stores the value needed by later steps.
total_values = 200  # Stores the value needed by later steps.

missing_percentage = total_values / missing_values * 100  # Stores the value needed by later steps.
print(missing_percentage)  # Displays a labelled result for inspection.

2000.0


### Example 2.14.28 — 19.8 Logic errors

**Status:** Diagnostic — NameError: name 'missing_values' is not defined.

```python
missing_percentage = missing_values / total_values * 100  # Stores the value needed by later steps.
print(missing_percentage)  # Displays a labelled result for inspection.
```

In [171]:
example_status = "Example 2.14.28: diagnostic — NameError: name 'missing_values' is not defined"  # Stores the value needed by later steps.
print(example_status)  # Displays a labelled result for inspection.

Example 2.14.28: diagnostic — NameError: name 'missing_values' is not defined


### Example 2.14.29 — 20. Tracing code manually

**Status:** Runnable — audited independently.

```python
count = 0  # Stores the value needed by later steps.

for value in [40, 120, 220]:  # Repeats the indented steps for each item.
    if value >= 100:  # Starts a branch when this condition is true.
        count = count + 1  # Stores the value needed by later steps.

print(count)  # Displays a labelled result for inspection.
```

In [172]:
count = 0  # Stores the value needed by later steps.

for value in [40, 120, 220]:  # Repeats the indented steps for each item.
    if value >= 100:  # Starts a branch when this condition is true.
        count = count + 1  # Stores the value needed by later steps.

print(count)  # Displays a labelled result for inspection.

2


## Checks

- Every Python fence in Tutorials 2.8–2.14 is present.
- Every executable physical line has a learner-facing comment.
- Deliberate errors and interactive cells remain inspectable without breaking Run all.
- Standard-library imports need no local package installation.

## Next Steps

Complete the matching numbered exercise before opening the Solutions notebook. Then continue to Tutorial 2.15 for longer situational problems.