# Lecture 4 Examples and Case — Control Flow, Collections, and Functions

**Course:** AAU E26 — Introduction to Scripting, Data Mining and Machine Learning  
**Lecture:** Lecture 4  
**Goal:** Run conditions, loops, collections, functions, and a record validator.

[Open this notebook in Google Colab](https://colab.research.google.com/github/asmrabbi/E26_TAN7_Scripting_CPH/blob/main/notebooks/examples/L04_examples_control_flow_collections_functions.ipynb) · [View the course repository](https://github.com/asmrabbi/E26_TAN7_Scripting_CPH)

Run the cells from top to bottom. Every executable line includes a short comment explaining what it does.


## Goal

Translate decisions and repetition into Python, use lists, write a reusable function, and validate a small batch of records.


## Setup

No extra packages or files are required for this notebook.


## Steps

### 1. Use a condition


In [1]:
satisfaction_score = 4.2  # Stores the score that we want to classify.
if satisfaction_score >= 4.0:  # Checks whether the score meets the high-satisfaction boundary.
    category = "high"  # Stores the category used when the first condition is true.
elif satisfaction_score >= 3.0:  # Checks a second boundary when the first condition is false.
    category = "medium"  # Stores the category used for scores from 3.0 up to 4.0.
else:  # Handles every remaining score below 3.0.
    category = "low"  # Stores the category used for lower scores.
print(category)  # Displays the category selected by the conditions.


high


### 2. Test boundary values


In [2]:
boundary_scores = [2.9, 3.0, 3.9, 4.0]  # Stores values just below and exactly on both boundaries.
for score in boundary_scores:  # Repeats the same decision for every test value.
    label = "high" if score >= 4.0 else "medium" if score >= 3.0 else "low"  # Applies the complete rule in one expression.
    print(score, label)  # Displays each input beside its resulting category.


2.9 low
3.0 medium
3.9 medium
4.0 high


### 3. Repeat with a for loop


In [3]:
resolution_days = [5.1, 3.2, 8.4, 4.0]  # Stores four observed resolution times.
total_days = 0.0  # Creates an accumulator that starts at zero.
for days in resolution_days:  # Visits each value in the list once.
    total_days = total_days + days  # Adds the current value to the running total.
average_days = total_days / len(resolution_days)  # Divides the total by the number of observations.
print(round(average_days, 2))  # Displays the average rounded to two decimal places.


5.18


### 4. Repeat with a while loop and a stopping condition


In [4]:
attempt = 1  # Starts the attempt counter at one.
maximum_attempts = 3  # Sets a clear limit so the loop cannot run forever.
while attempt <= maximum_attempts:  # Repeats while the current attempt is within the limit.
    print(f"Checking batch: attempt {attempt}")  # Displays the current progress.
    attempt = attempt + 1  # Increases the counter so the loop eventually stops.


Checking batch: attempt 1
Checking batch: attempt 2
Checking batch: attempt 3


### 5. Store related values in a list and dictionary


In [5]:
cities = ["Copenhagen", "Aalborg", "Copenhagen"]  # Stores several city observations in an ordered list.
unique_cities = set(cities)  # Converts the list to a set so repeated names appear only once.
record = {"record_id": 1001, "city": "Copenhagen", "cases_received": 120}  # Groups labelled values that belong to one record.
print(sorted(unique_cities))  # Displays the distinct city names in a predictable order.
print(record["cases_received"])  # Retrieves one value by its dictionary key.


['Aalborg', 'Copenhagen']
120


### 6. Put a validation rule in a function


In [6]:
def validate_case_counts(received, resolved):  # Defines a reusable function with two inputs.
    """Return a list of problems found in two case counts."""  # Documents what the function returns.
    problems = []  # Creates an empty list that will collect any problem messages.
    if received < 0:  # Checks whether the received count is impossible.
        problems.append("received is negative")  # Adds a clear message when the rule fails.
    if resolved < 0:  # Checks whether the resolved count is impossible.
        problems.append("resolved is negative")  # Adds a second possible message.
    if resolved > received:  # Checks whether more cases were resolved than received in this simplified example.
        problems.append("resolved exceeds received")  # Records the boundary-rule problem.
    return problems  # Sends the complete list back to the caller.
print(validate_case_counts(120, 112))  # Tests a normal case that should return an empty list.
print(validate_case_counts(85, 90))  # Tests a case that should report one problem.


[]
['resolved exceeds received']


### 7. Recurring case: validate several records


In [7]:
monthly_records = [{"record_id": 1001, "received": 120, "resolved": 112}, {"record_id": 1002, "received": 85, "resolved": 90}, {"record_id": 1003, "received": -3, "resolved": 0}]  # Stores three small records for the case.
problem_count = 0  # Starts a counter for records that fail at least one rule.
for monthly_record in monthly_records:  # Visits each record in the collection.
    record_problems = validate_case_counts(monthly_record["received"], monthly_record["resolved"])  # Applies the reusable validation function.
    if record_problems:  # Checks whether the returned list contains any messages.
        problem_count = problem_count + 1  # Increases the summary counter for a problematic record.
        print(monthly_record["record_id"], record_problems)  # Displays the record identifier and its problems.
print(f"Records with problems: {problem_count}")  # Displays the final number of problematic records.


1002 ['resolved exceeds received']
1003 ['received is negative', 'resolved exceeds received']
Records with problems: 2


## Checks

The boundary table should classify 3.0 as medium and 4.0 as high. The validator should flag records 1002 and 1003, for a total of two problematic records.


## Next Steps

Use the exercise notebook to add a satisfaction-score rule and test normal, invalid, missing, and boundary values.
