# Lecture 4 Complete Tutorial Companion — Python Foundations II

**Section:** Part II, Section 2.2  
**Source tutorial:** `python-foundations-ii.md`  
[Open in Google Colab](https://colab.research.google.com/github/asmrabbi/E26_TAN7_Scripting_CPH/blob/main/notebooks/examples/L04_complete_python_foundations_II_tutorial.ipynb) · [Course repository](https://github.com/asmrabbi/E26_TAN7_Scripting_CPH)

This companion follows the tutorial in source order. Every Python block from the website is included. Runnable blocks are provided as executable cells; deliberate errors, partial syntax references, interactive input, and file-dependent fragments remain visible as commented code and are labelled clearly.

## Goal

Make every Python example in the tutorial available from GitHub and Colab without removing the selectable code from the website.

## Setup

Google Colab already includes the common course packages. For a local computer, open a terminal in the repository folder and run:

```bash
python -m venv .venv
source .venv/bin/activate  # Windows PowerShell: .venv\Scripts\Activate.ps1
python -m pip install -r requirements.txt
python -m jupyter lab
```

The next cell checks the shared course dependencies and reports the exact installation command if anything is missing.

### Running this notebook on a local computer

1. Download or clone the course repository.
2. Open a terminal in the repository folder.
3. Create and activate a virtual environment.
4. Install the shared requirements with `python -m pip install -r requirements.txt`.
5. Start Jupyter with `python -m jupyter lab`.

Packages used directly in this notebook: `pandas`

In [1]:
import sys  # Provides the path to the Python interpreter running this notebook.
import importlib.util  # Provides a safe way to check whether a Python module is installed.
required_packages = {"pandas": "pandas", "matplotlib": "matplotlib", "nltk": "nltk", "sklearn": "scikit-learn"}  # Maps import names to installation names.
missing_packages = [package_name for module_name, package_name in required_packages.items() if importlib.util.find_spec(module_name) is None]  # Lists packages that are unavailable locally.
if missing_packages:  # Checks whether the local environment needs extra packages.
    install_command = f"{sys.executable} -m pip install {' '.join(missing_packages)}"  # Builds the exact local installation command.
    raise ModuleNotFoundError(f"Install the missing packages, then rerun this notebook: {install_command}")  # Stops with a useful repair instruction.
print("Dependency check passed.")  # Confirms that the shared course requirements are available.

Dependency check passed.


## Steps

The examples below follow the website tutorial in order.

### Example 1: 2.1 Required knowledge from Python Foundations I

**Website source:** `python-foundations-ii.md`, line 66  
**Status:** Runnable and audited — executed successfully during the audit.

```python
records = 250  # Stores the calculated or supplied value in records.
missing_records = 18  # Stores the calculated or supplied value in missing_records.
complete_records = records - missing_records  # Stores the calculated or supplied value in complete_records.

print(complete_records)  # Displays information so the result can be inspected.
```

In [2]:
records = 250  # Stores the calculated or supplied value in records.
missing_records = 18  # Stores the calculated or supplied value in missing_records.
complete_records = records - missing_records  # Stores the calculated or supplied value in complete_records.

print(complete_records)  # Displays information so the result can be inspected.

232


### Example 2: 2.2 Quick readiness check

**Website source:** `python-foundations-ii.md`, line 87  
**Status:** Runnable and audited — executed successfully during the audit.

```python
total_rows = 120  # Stores the calculated or supplied value in total_rows.
duplicate_rows = 8  # Stores the calculated or supplied value in duplicate_rows.
usable_rows = total_rows - duplicate_rows  # Stores the calculated or supplied value in usable_rows.

print("Usable rows:", usable_rows)  # Displays information so the result can be inspected.
```

In [3]:
total_rows = 120  # Stores the calculated or supplied value in total_rows.
duplicate_rows = 8  # Stores the calculated or supplied value in duplicate_rows.
usable_rows = total_rows - duplicate_rows  # Stores the calculated or supplied value in usable_rows.

print("Usable rows:", usable_rows)  # Displays information so the result can be inspected.

Usable rows: 112


### Example 3: 4.1 What is a Boolean value?

**Website source:** `python-foundations-ii.md`, line 153  
**Status:** Runnable and audited — executed successfully during the audit.

```python
True  # Runs this step from the tutorial example.
False  # Runs this step from the tutorial example.
```

In [4]:
True  # Runs this step from the tutorial example.
False  # Runs this step from the tutorial example.

False

### Example 4: 4.1 What is a Boolean value?

**Website source:** `python-foundations-ii.md`, line 160  
**Status:** Runnable and audited — executed successfully during the audit.

```python
record_complete = True  # Stores the calculated or supplied value in record_complete.
needs_review = False  # Stores the calculated or supplied value in needs_review.

print(record_complete)  # Displays information so the result can be inspected.
print(needs_review)  # Displays information so the result can be inspected.
```

In [5]:
record_complete = True  # Stores the calculated or supplied value in record_complete.
needs_review = False  # Stores the calculated or supplied value in needs_review.

print(record_complete)  # Displays information so the result can be inspected.
print(needs_review)  # Displays information so the result can be inspected.

True
False


### Example 5: Line-by-line explanation

**Website source:** `python-foundations-ii.md`, line 177  
**Status:** Runnable and audited — executed successfully during the audit.

```python
record_complete = True  # Stores the calculated or supplied value in record_complete.
```

In [6]:
record_complete = True  # Stores the calculated or supplied value in record_complete.

### Example 6: Line-by-line explanation

**Website source:** `python-foundations-ii.md`, line 186  
**Status:** Runnable and audited — executed successfully during the audit.

```python
needs_review = False  # Stores the calculated or supplied value in needs_review.
```

In [7]:
needs_review = False  # Stores the calculated or supplied value in needs_review.

### Example 7: Line-by-line explanation

**Website source:** `python-foundations-ii.md`, line 193  
**Status:** Deliberate error or diagnostic example — NameError: name 'record_complete' is not defined.

```python
print(record_complete)  # Displays information so the result can be inspected.
```

In [8]:
example_status = "Example 7 is labelled deliberate error or diagnostic example: NameError: name 'record_complete' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 7 is labelled deliberate error or diagnostic example: NameError: name 'record_complete' is not defined


### Example 8: Example 1: Comparing a number

**Website source:** `python-foundations-ii.md`, line 216  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 125  # Stores the calculated or supplied value in engagement.

print(engagement > 100)  # Displays information so the result can be inspected.
print(engagement == 125)  # Displays information so the result can be inspected.
print(engagement < 50)  # Displays information so the result can be inspected.
```

In [9]:
engagement = 125  # Stores the calculated or supplied value in engagement.

print(engagement > 100)  # Displays information so the result can be inspected.
print(engagement == 125)  # Displays information so the result can be inspected.
print(engagement < 50)  # Displays information so the result can be inspected.

True
True
False


### Example 9: 4.3 Assignment and equality are different

**Website source:** `python-foundations-ii.md`, line 246  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 125  # Stores the calculated or supplied value in engagement.
```

In [10]:
engagement = 125  # Stores the calculated or supplied value in engagement.

### Example 10: 4.3 Assignment and equality are different

**Website source:** `python-foundations-ii.md`, line 256  
**Status:** Deliberate error or diagnostic example — NameError: name 'engagement' is not defined.

```python
engagement == 125  # Runs this step from the tutorial example.
```

In [11]:
example_status = "Example 10 is labelled deliberate error or diagnostic example: NameError: name 'engagement' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 10 is labelled deliberate error or diagnostic example: NameError: name 'engagement' is not defined


### Example 11: Deliberate error

**Website source:** `python-foundations-ii.md`, line 268  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 3: invalid syntax. Maybe you meant '==' or ':=' instead of '='?.

```python
engagement = 125  # Stores the calculated or supplied value in engagement.

if engagement = 125:  # Starts a decision when this condition is true.
    print("The value is 125")  # Displays information so the result can be inspected.
```

In [12]:
example_status = "Example 11 is labelled deliberate error or diagnostic example: SyntaxError on line 3: invalid syntax. Maybe you meant '==' or ':=' instead of '='?"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 11 is labelled deliberate error or diagnostic example: SyntaxError on line 3: invalid syntax. Maybe you meant '==' or ':=' instead of '='?


### Example 12: Repair

**Website source:** `python-foundations-ii.md`, line 279  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 125  # Stores the calculated or supplied value in engagement.

if engagement == 125:  # Starts a decision when this condition is true.
    print("The value is 125")  # Displays information so the result can be inspected.
```

In [13]:
engagement = 125  # Stores the calculated or supplied value in engagement.

if engagement == 125:  # Starts a decision when this condition is true.
    print("The value is 125")  # Displays information so the result can be inspected.

The value is 125


### Example 13: 4.4 Comparing strings

**Website source:** `python-foundations-ii.md`, line 298  
**Status:** Runnable and audited — executed successfully during the audit.

```python
actor_type = "Municipality"  # Stores the calculated or supplied value in actor_type.

print(actor_type == "Municipality")  # Displays information so the result can be inspected.
print(actor_type == "Business")  # Displays information so the result can be inspected.
print(actor_type != "Citizen")  # Displays information so the result can be inspected.
```

In [14]:
actor_type = "Municipality"  # Stores the calculated or supplied value in actor_type.

print(actor_type == "Municipality")  # Displays information so the result can be inspected.
print(actor_type == "Business")  # Displays information so the result can be inspected.
print(actor_type != "Citizen")  # Displays information so the result can be inspected.

True
False
True


### Example 14: 4.4 Comparing strings

**Website source:** `python-foundations-ii.md`, line 316  
**Status:** Runnable and audited — executed successfully during the audit.

```python
topic = "Cycling"  # Stores the calculated or supplied value in topic.

print(topic == "Cycling")  # Displays information so the result can be inspected.
print(topic == "cycling")  # Displays information so the result can be inspected.
```

In [15]:
topic = "Cycling"  # Stores the calculated or supplied value in topic.

print(topic == "Cycling")  # Displays information so the result can be inspected.
print(topic == "cycling")  # Displays information so the result can be inspected.

True
False


### Example 15: 4.5 Storing the result of a comparison

**Website source:** `python-foundations-ii.md`, line 346  
**Status:** Runnable and audited — executed successfully during the audit.

```python
missing_values = 14  # Stores the calculated or supplied value in missing_values.
too_many_missing = missing_values > 10  # Stores the calculated or supplied value in too_many_missing.

print(too_many_missing)  # Displays information so the result can be inspected.
```

In [16]:
missing_values = 14  # Stores the calculated or supplied value in missing_values.
too_many_missing = missing_values > 10  # Stores the calculated or supplied value in too_many_missing.

print(too_many_missing)  # Displays information so the result can be inspected.

True


### Example 16: Explanation

**Website source:** `python-foundations-ii.md`, line 363  
**Status:** Deliberate error or diagnostic example — NameError: name 'missing_values' is not defined.

```python
missing_values > 10  # Runs this step from the tutorial example.
```

In [17]:
example_status = "Example 16 is labelled deliberate error or diagnostic example: NameError: name 'missing_values' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 16 is labelled deliberate error or diagnostic example: NameError: name 'missing_values' is not defined


### Example 17: Explanation

**Website source:** `python-foundations-ii.md`, line 369  
**Status:** Deliberate error or diagnostic example — NameError: name 'too_many_missing' is not defined.

```python
too_many_missing  # Runs this step from the tutorial example.
```

In [18]:
example_status = "Example 17 is labelled deliberate error or diagnostic example: NameError: name 'too_many_missing' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 17 is labelled deliberate error or diagnostic example: NameError: name 'too_many_missing' is not defined


### Example 18: Explanation

**Website source:** `python-foundations-ii.md`, line 377  
**Status:** Deliberate error or diagnostic example — NameError: name 'missing_values' is not defined.

```python
if missing_values > 10:  # Starts a decision when this condition is true.
    print("Review the data")  # Displays information so the result can be inspected.
```

In [19]:
example_status = "Example 18 is labelled deliberate error or diagnostic example: NameError: name 'missing_values' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 18 is labelled deliberate error or diagnostic example: NameError: name 'missing_values' is not defined


### Example 19: Explanation

**Website source:** `python-foundations-ii.md`, line 384  
**Status:** Deliberate error or diagnostic example — NameError: name 'missing_values' is not defined.

```python
too_many_missing = missing_values > 10  # Stores the calculated or supplied value in too_many_missing.

if too_many_missing:  # Starts a decision when this condition is true.
    print("Review the data")  # Displays information so the result can be inspected.
```

In [20]:
example_status = "Example 19 is labelled deliberate error or diagnostic example: NameError: name 'missing_values' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 19 is labelled deliberate error or diagnostic example: NameError: name 'missing_values' is not defined


### Example 20: Practice checkpoint 1

**Website source:** `python-foundations-ii.md`, line 399  
**Status:** Runnable and audited — executed successfully during the audit.

```python
records = 75  # Stores the calculated or supplied value in records.
minimum_required = 100  # Stores the calculated or supplied value in minimum_required.
enough_records = records >= minimum_required  # Runs this step from the tutorial example.

print(enough_records)  # Displays information so the result can be inspected.
```

In [21]:
records = 75  # Stores the calculated or supplied value in records.
minimum_required = 100  # Stores the calculated or supplied value in minimum_required.
enough_records = records >= minimum_required  # Runs this step from the tutorial example.

print(enough_records)  # Displays information so the result can be inspected.

False


### Example 21: 5.1 A one-way decision

**Website source:** `python-foundations-ii.md`, line 436  
**Status:** Runnable and audited — executed successfully during the audit.

```python
missing_values = 14  # Stores the calculated or supplied value in missing_values.

if missing_values > 10:  # Starts a decision when this condition is true.
    print("Review the missing data")  # Displays information so the result can be inspected.
```

In [22]:
missing_values = 14  # Stores the calculated or supplied value in missing_values.

if missing_values > 10:  # Starts a decision when this condition is true.
    print("Review the missing data")  # Displays information so the result can be inspected.

Review the missing data


### Example 22: Structure

**Website source:** `python-foundations-ii.md`, line 451  
**Status:** Deliberate error or diagnostic example — NameError: name 'condition' is not defined.

```python
if condition:  # Starts a decision when this condition is true.
    code_to_run  # Runs this step from the tutorial example.
```

In [23]:
example_status = "Example 22 is labelled deliberate error or diagnostic example: NameError: name 'condition' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 22 is labelled deliberate error or diagnostic example: NameError: name 'condition' is not defined


### Example 23: 5.2 When the condition is false

**Website source:** `python-foundations-ii.md`, line 468  
**Status:** Runnable and audited — executed successfully during the audit.

```python
missing_values = 4  # Stores the calculated or supplied value in missing_values.

if missing_values > 10:  # Starts a decision when this condition is true.
    print("Review the missing data")  # Displays information so the result can be inspected.

print("Check complete")  # Displays information so the result can be inspected.
```

In [24]:
missing_values = 4  # Stores the calculated or supplied value in missing_values.

if missing_values > 10:  # Starts a decision when this condition is true.
    print("Review the missing data")  # Displays information so the result can be inspected.

print("Check complete")  # Displays information so the result can be inspected.

Check complete


### Example 24: 5.3 Indentation is part of Python syntax

**Website source:** `python-foundations-ii.md`, line 493  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 150  # Stores the calculated or supplied value in engagement.

if engagement > 100:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
    print("Include this record in the high-engagement review")  # Displays information so the result can be inspected.

print("Finished")  # Displays information so the result can be inspected.
```

In [25]:
engagement = 150  # Stores the calculated or supplied value in engagement.

if engagement > 100:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
    print("Include this record in the high-engagement review")  # Displays information so the result can be inspected.

print("Finished")  # Displays information so the result can be inspected.

High engagement
Include this record in the high-engagement review
Finished


### Example 25: 5.3 Indentation is part of Python syntax

**Website source:** `python-foundations-ii.md`, line 513  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 4: expected an indented block after 'if' statement on line 3.

```python
engagement = 150  # Stores the calculated or supplied value in engagement.

if engagement > 100:  # Starts a decision when this condition is true.
print("High engagement")  # Displays information so the result can be inspected.
```

In [26]:
example_status = "Example 25 is labelled deliberate error or diagnostic example: SyntaxError on line 4: expected an indented block after 'if' statement on line 3"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 25 is labelled deliberate error or diagnostic example: SyntaxError on line 4: expected an indented block after 'if' statement on line 3


### Example 26: Repair

**Website source:** `python-foundations-ii.md`, line 526  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 150  # Stores the calculated or supplied value in engagement.

if engagement > 100:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
```

In [27]:
engagement = 150  # Stores the calculated or supplied value in engagement.

if engagement > 100:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.

High engagement


### Example 27: 5.4 Multiple lines inside one `if` block

**Website source:** `python-foundations-ii.md`, line 537  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 220  # Stores the calculated or supplied value in engagement.
actor_type = "Citizen Group"  # Stores the calculated or supplied value in actor_type.

if engagement > 200:  # Starts a decision when this condition is true.
    print("Priority record")  # Displays information so the result can be inspected.
    print("Actor type:", actor_type)  # Displays information so the result can be inspected.
    print("Engagement:", engagement)  # Displays information so the result can be inspected.

print("Assessment complete")  # Displays information so the result can be inspected.
```

In [28]:
engagement = 220  # Stores the calculated or supplied value in engagement.
actor_type = "Citizen Group"  # Stores the calculated or supplied value in actor_type.

if engagement > 200:  # Starts a decision when this condition is true.
    print("Priority record")  # Displays information so the result can be inspected.
    print("Actor type:", actor_type)  # Displays information so the result can be inspected.
    print("Engagement:", engagement)  # Displays information so the result can be inspected.

print("Assessment complete")  # Displays information so the result can be inspected.

Priority record
Actor type: Citizen Group
Engagement: 220
Assessment complete


### Example 28: 5.5 A condition using a string

**Website source:** `python-foundations-ii.md`, line 564  
**Status:** Runnable and audited — executed successfully during the audit.

```python
position = "Support"  # Stores the calculated or supplied value in position.

if position == "Support":  # Starts a decision when this condition is true.
    print("This record supports the proposal")  # Displays information so the result can be inspected.
```

In [29]:
position = "Support"  # Stores the calculated or supplied value in position.

if position == "Support":  # Starts a decision when this condition is true.
    print("This record supports the proposal")  # Displays information so the result can be inspected.

This record supports the proposal


### Example 29: Common mistake

**Website source:** `python-foundations-ii.md`, line 579  
**Status:** Runnable and audited — executed successfully during the audit.

```python
position = "Support"  # Stores the calculated or supplied value in position.

if position == "support":  # Starts a decision when this condition is true.
    print("This record supports the proposal")  # Displays information so the result can be inspected.
```

In [30]:
position = "Support"  # Stores the calculated or supplied value in position.

if position == "support":  # Starts a decision when this condition is true.
    print("This record supports the proposal")  # Displays information so the result can be inspected.

### Example 30: Common mistake

**Website source:** `python-foundations-ii.md`, line 590  
**Status:** Runnable and audited — executed successfully during the audit.

```python
position = "Support"  # Stores the calculated or supplied value in position.

if position.lower() == "support":  # Starts a decision when this condition is true.
    print("This record supports the proposal")  # Displays information so the result can be inspected.
```

In [31]:
position = "Support"  # Stores the calculated or supplied value in position.

if position.lower() == "support":  # Starts a decision when this condition is true.
    print("This record supports the proposal")  # Displays information so the result can be inspected.

This record supports the proposal


### Example 31: Practice checkpoint 2

**Website source:** `python-foundations-ii.md`, line 607  
**Status:** Deliberate error or diagnostic example — NameError: name '__________________' is not defined.

```python
duplicate_rows = 7  # Stores the calculated or supplied value in duplicate_rows.

if __________________:  # Starts a decision when this condition is true.
    print("Duplicates must be reviewed")  # Displays information so the result can be inspected.
```

In [32]:
example_status = "Example 31 is labelled deliberate error or diagnostic example: NameError: name '__________________' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 31 is labelled deliberate error or diagnostic example: NameError: name '__________________' is not defined


### Example 32: Practice checkpoint 2

**Website source:** `python-foundations-ii.md`, line 619  
**Status:** Runnable and audited — executed successfully during the audit.

```python
duplicate_rows = 7  # Stores the calculated or supplied value in duplicate_rows.

if duplicate_rows > 0:  # Starts a decision when this condition is true.
    print("Duplicates must be reviewed")  # Displays information so the result can be inspected.
```

In [33]:
duplicate_rows = 7  # Stores the calculated or supplied value in duplicate_rows.

if duplicate_rows > 0:  # Starts a decision when this condition is true.
    print("Duplicates must be reviewed")  # Displays information so the result can be inspected.

Duplicates must be reviewed


### Example 33: 6.1 Basic example

**Website source:** `python-foundations-ii.md`, line 636  
**Status:** Runnable and audited — executed successfully during the audit.

```python
missing_values = 14  # Stores the calculated or supplied value in missing_values.

if missing_values > 10:  # Starts a decision when this condition is true.
    print("Review the dataset")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Continue to initial analysis")  # Displays information so the result can be inspected.
```

In [34]:
missing_values = 14  # Stores the calculated or supplied value in missing_values.

if missing_values > 10:  # Starts a decision when this condition is true.
    print("Review the dataset")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Continue to initial analysis")  # Displays information so the result can be inspected.

Review the dataset


### Example 34: 6.2 Understanding the flow

**Website source:** `python-foundations-ii.md`, line 663  
**Status:** Deliberate error or diagnostic example — NameError: name 'condition' is not defined.

```python
if condition:  # Starts a decision when this condition is true.
    action_when_true  # Runs this step from the tutorial example.
else:  # Runs the fallback branch.
    action_when_false  # Runs this step from the tutorial example.
```

In [35]:
example_status = "Example 34 is labelled deliberate error or diagnostic example: NameError: name 'condition' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 34 is labelled deliberate error or diagnostic example: NameError: name 'condition' is not defined


### Example 35: 6.3 Example with user input

**Website source:** `python-foundations-ii.md`, line 681  
**Status:** Run manually with the stated input or file — interactive input.

```python
answer = input("Is the source verified? Type yes or no: ")  # Stores the calculated or supplied value in answer.

if answer == "yes":  # Starts a decision when this condition is true.
    print("The record may continue to analysis")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("The source must be reviewed")  # Displays information so the result can be inspected.
```

In [36]:
example_status = 'Example 35 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 35 is labelled run manually with the stated input or file: interactive input


### Example 36: Problem with this version

**Website source:** `python-foundations-ii.md`, line 712  
**Status:** Run manually with the stated input or file — interactive input.

```python
answer = input("Is the source verified? Type yes or no: ")  # Stores the calculated or supplied value in answer.
answer = answer.strip().lower()  # Stores the calculated or supplied value in answer.

if answer == "yes":  # Starts a decision when this condition is true.
    print("The record may continue to analysis")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("The source must be reviewed")  # Displays information so the result can be inspected.
```

In [37]:
example_status = 'Example 36 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 36 is labelled run manually with the stated input or file: interactive input


### Example 37: 6.4 Deliberate break-and-repair activity

**Website source:** `python-foundations-ii.md`, line 736  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 3: expected ':'.

```python
engagement = 80  # Stores the calculated or supplied value in engagement.

if engagement >= 100  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
else  # Runs this step from the tutorial example.
    print("Normal engagement")  # Displays information so the result can be inspected.
```

In [38]:
example_status = "Example 37 is labelled deliberate error or diagnostic example: SyntaxError on line 3: expected ':'"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 37 is labelled deliberate error or diagnostic example: SyntaxError on line 3: expected ':'


### Example 38: 6.4 Deliberate break-and-repair activity

**Website source:** `python-foundations-ii.md`, line 749  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 80  # Stores the calculated or supplied value in engagement.

if engagement >= 100:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Normal engagement")  # Displays information so the result can be inspected.
```

In [39]:
engagement = 80  # Stores the calculated or supplied value in engagement.

if engagement >= 100:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Normal engagement")  # Displays information so the result can be inspected.

Normal engagement


### Example 39: 7.1 Classifying engagement

**Website source:** `python-foundations-ii.md`, line 772  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 125  # Stores the calculated or supplied value in engagement.

if engagement >= 200:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
elif engagement >= 100:  # Checks another condition when earlier branches were false.
    print("Medium engagement")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Low engagement")  # Displays information so the result can be inspected.
```

In [40]:
engagement = 125  # Stores the calculated or supplied value in engagement.

if engagement >= 200:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
elif engagement >= 100:  # Checks another condition when earlier branches were false.
    print("Medium engagement")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Low engagement")  # Displays information so the result can be inspected.

Medium engagement


### Example 40: 7.2 Order matters

**Website source:** `python-foundations-ii.md`, line 806  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 250  # Stores the calculated or supplied value in engagement.

if engagement >= 100:  # Starts a decision when this condition is true.
    print("Medium or high engagement")  # Displays information so the result can be inspected.
elif engagement >= 200:  # Checks another condition when earlier branches were false.
    print("High engagement")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Low engagement")  # Displays information so the result can be inspected.
```

In [41]:
engagement = 250  # Stores the calculated or supplied value in engagement.

if engagement >= 100:  # Starts a decision when this condition is true.
    print("Medium or high engagement")  # Displays information so the result can be inspected.
elif engagement >= 200:  # Checks another condition when earlier branches were false.
    print("High engagement")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Low engagement")  # Displays information so the result can be inspected.

Medium or high engagement


### Example 41: 7.2 Order matters

**Website source:** `python-foundations-ii.md`, line 827  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 250  # Stores the calculated or supplied value in engagement.

if engagement >= 200:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
elif engagement >= 100:  # Checks another condition when earlier branches were false.
    print("Medium engagement")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Low engagement")  # Displays information so the result can be inspected.
```

In [42]:
engagement = 250  # Stores the calculated or supplied value in engagement.

if engagement >= 200:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
elif engagement >= 100:  # Checks another condition when earlier branches were false.
    print("Medium engagement")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Low engagement")  # Displays information so the result can be inspected.

High engagement


### Example 42: 7.3 A more detailed classification

**Website source:** `python-foundations-ii.md`, line 844  
**Status:** Runnable and audited — executed successfully during the audit.

```python
missing_percentage = 18  # Stores the calculated or supplied value in missing_percentage.

if missing_percentage == 0:  # Starts a decision when this condition is true.
    status = "No missing values"  # Stores the calculated or supplied value in status.
elif missing_percentage <= 5:  # Checks another condition when earlier branches were false.
    status = "Minor missingness"  # Stores the calculated or supplied value in status.
elif missing_percentage <= 15:  # Checks another condition when earlier branches were false.
    status = "Moderate missingness"  # Stores the calculated or supplied value in status.
else:  # Runs the fallback branch.
    status = "Substantial missingness"  # Stores the calculated or supplied value in status.

print(status)  # Displays information so the result can be inspected.
```

In [43]:
missing_percentage = 18  # Stores the calculated or supplied value in missing_percentage.

if missing_percentage == 0:  # Starts a decision when this condition is true.
    status = "No missing values"  # Stores the calculated or supplied value in status.
elif missing_percentage <= 5:  # Checks another condition when earlier branches were false.
    status = "Minor missingness"  # Stores the calculated or supplied value in status.
elif missing_percentage <= 15:  # Checks another condition when earlier branches were false.
    status = "Moderate missingness"  # Stores the calculated or supplied value in status.
else:  # Runs the fallback branch.
    status = "Substantial missingness"  # Stores the calculated or supplied value in status.

print(status)  # Displays information so the result can be inspected.

Substantial missingness


### Example 43: Why assign the result to a variable?

**Website source:** `python-foundations-ii.md`, line 869  
**Status:** Deliberate error or diagnostic example — NameError: name 'status' is not defined.

```python
print("Data-quality status:", status)  # Displays information so the result can be inspected.
```

In [44]:
example_status = "Example 43 is labelled deliberate error or diagnostic example: NameError: name 'status' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 43 is labelled deliberate error or diagnostic example: NameError: name 'status' is not defined


### Example 44: Why assign the result to a variable?

**Website source:** `python-foundations-ii.md`, line 875  
**Status:** Deliberate error or diagnostic example — NameError: name 'status' is not defined.

```python
if status == "Substantial missingness":  # Starts a decision when this condition is true.
    print("Human review required")  # Displays information so the result can be inspected.
```

In [45]:
example_status = "Example 44 is labelled deliberate error or diagnostic example: NameError: name 'status' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 44 is labelled deliberate error or diagnostic example: NameError: name 'status' is not defined


### Example 45: 7.4 Boundary testing

**Website source:** `python-foundations-ii.md`, line 888  
**Status:** Runnable and audited — executed successfully during the audit.

```python
missing_percentage = 0  # Stores the calculated or supplied value in missing_percentage.
missing_percentage = 1  # Stores the calculated or supplied value in missing_percentage.
missing_percentage = 5  # Stores the calculated or supplied value in missing_percentage.
missing_percentage = 6  # Stores the calculated or supplied value in missing_percentage.
missing_percentage = 15  # Stores the calculated or supplied value in missing_percentage.
missing_percentage = 16  # Stores the calculated or supplied value in missing_percentage.
```

In [46]:
missing_percentage = 0  # Stores the calculated or supplied value in missing_percentage.
missing_percentage = 1  # Stores the calculated or supplied value in missing_percentage.
missing_percentage = 5  # Stores the calculated or supplied value in missing_percentage.
missing_percentage = 6  # Stores the calculated or supplied value in missing_percentage.
missing_percentage = 15  # Stores the calculated or supplied value in missing_percentage.
missing_percentage = 16  # Stores the calculated or supplied value in missing_percentage.

### Example 46: 7.4 Boundary testing

**Website source:** `python-foundations-ii.md`, line 901  
**Status:** Runnable and audited — executed successfully during the audit.

```python
score = 70  # Stores the calculated or supplied value in score.

if score > 70:  # Starts a decision when this condition is true.
    print("High")  # Displays information so the result can be inspected.
elif score < 70:  # Checks another condition when earlier branches were false.
    print("Low")  # Displays information so the result can be inspected.
```

In [47]:
score = 70  # Stores the calculated or supplied value in score.

if score > 70:  # Starts a decision when this condition is true.
    print("High")  # Displays information so the result can be inspected.
elif score < 70:  # Checks another condition when earlier branches were false.
    print("Low")  # Displays information so the result can be inspected.

### Example 47: 7.4 Boundary testing

**Website source:** `python-foundations-ii.md`, line 914  
**Status:** Runnable and audited — executed successfully during the audit.

```python
score = 70  # Stores the calculated or supplied value in score.

if score >= 70:  # Starts a decision when this condition is true.
    print("High")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Low")  # Displays information so the result can be inspected.
```

In [48]:
score = 70  # Stores the calculated or supplied value in score.

if score >= 70:  # Starts a decision when this condition is true.
    print("High")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Low")  # Displays information so the result can be inspected.

High


### Example 48: Practice checkpoint 3

**Website source:** `python-foundations-ii.md`, line 935  
**Status:** Runnable and audited — executed successfully during the audit.

```python
number_of_records = 145  # Stores the calculated or supplied value in number_of_records.

# Write your decision below
```

In [49]:
number_of_records = 145  # Stores the calculated or supplied value in number_of_records.

# Write your decision below

### Example 49: Practice checkpoint 3

**Website source:** `python-foundations-ii.md`, line 944  
**Status:** Runnable and audited — executed successfully during the audit.

```python
number_of_records = 145  # Stores the calculated or supplied value in number_of_records.

if number_of_records >= 200:  # Starts a decision when this condition is true.
    print("Large dataset")  # Displays information so the result can be inspected.
elif number_of_records >= 100:  # Checks another condition when earlier branches were false.
    print("Medium dataset")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Small dataset")  # Displays information so the result can be inspected.
```

In [50]:
number_of_records = 145  # Stores the calculated or supplied value in number_of_records.

if number_of_records >= 200:  # Starts a decision when this condition is true.
    print("Large dataset")  # Displays information so the result can be inspected.
elif number_of_records >= 100:  # Checks another condition when earlier branches were false.
    print("Medium dataset")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Small dataset")  # Displays information so the result can be inspected.

Medium dataset


### Example 50: 8.1 `and`

**Website source:** `python-foundations-ii.md`, line 967  
**Status:** Runnable and audited — executed successfully during the audit.

```python
missing_values = 4  # Stores the calculated or supplied value in missing_values.
duplicate_rows = 0  # Stores the calculated or supplied value in duplicate_rows.

if missing_values <= 5 and duplicate_rows == 0:  # Starts a decision when this condition is true.
    print("The dataset passes the initial check")  # Displays information so the result can be inspected.
```

In [51]:
missing_values = 4  # Stores the calculated or supplied value in missing_values.
duplicate_rows = 0  # Stores the calculated or supplied value in duplicate_rows.

if missing_values <= 5 and duplicate_rows == 0:  # Starts a decision when this condition is true.
    print("The dataset passes the initial check")  # Displays information so the result can be inspected.

The dataset passes the initial check


### Example 51: 8.2 `or`

**Website source:** `python-foundations-ii.md`, line 996  
**Status:** Runnable and audited — executed successfully during the audit.

```python
missing_values = 3  # Stores the calculated or supplied value in missing_values.
duplicate_rows = 7  # Stores the calculated or supplied value in duplicate_rows.

if missing_values > 10 or duplicate_rows > 0:  # Starts a decision when this condition is true.
    print("Review is required")  # Displays information so the result can be inspected.
```

In [52]:
missing_values = 3  # Stores the calculated or supplied value in missing_values.
duplicate_rows = 7  # Stores the calculated or supplied value in duplicate_rows.

if missing_values > 10 or duplicate_rows > 0:  # Starts a decision when this condition is true.
    print("Review is required")  # Displays information so the result can be inspected.

Review is required


### Example 52: 8.3 `not`

**Website source:** `python-foundations-ii.md`, line 1018  
**Status:** Runnable and audited — executed successfully during the audit.

```python
source_verified = False  # Stores the calculated or supplied value in source_verified.

if not source_verified:  # Starts a decision when this condition is true.
    print("Do not use the record without review")  # Displays information so the result can be inspected.
```

In [53]:
source_verified = False  # Stores the calculated or supplied value in source_verified.

if not source_verified:  # Starts a decision when this condition is true.
    print("Do not use the record without review")  # Displays information so the result can be inspected.

Do not use the record without review


### Example 53: 8.4 A combined example

**Website source:** `python-foundations-ii.md`, line 1039  
**Status:** Runnable and audited — executed successfully during the audit.

```python
actor_type = "Citizen Group"  # Stores the calculated or supplied value in actor_type.
engagement = 240  # Stores the calculated or supplied value in engagement.
source_verified = True  # Stores the calculated or supplied value in source_verified.

if actor_type == "Citizen Group" and engagement >= 200 and source_verified:  # Starts a decision when this condition is true.
    print("Include in the high-engagement citizen-group review")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Use the standard review process")  # Displays information so the result can be inspected.
```

In [54]:
actor_type = "Citizen Group"  # Stores the calculated or supplied value in actor_type.
engagement = 240  # Stores the calculated or supplied value in engagement.
source_verified = True  # Stores the calculated or supplied value in source_verified.

if actor_type == "Citizen Group" and engagement >= 200 and source_verified:  # Starts a decision when this condition is true.
    print("Include in the high-engagement citizen-group review")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Use the standard review process")  # Displays information so the result can be inspected.

Include in the high-engagement citizen-group review


### Example 54: 8.5 Parentheses for clarity

**Website source:** `python-foundations-ii.md`, line 1064  
**Status:** Deliberate error or diagnostic example — NameError: name 'topic' is not defined.

```python
if topic == "Cycling" or topic == "Public Transport" and engagement > 100:  # Starts a decision when this condition is true.
    print("Selected")  # Displays information so the result can be inspected.
```

In [55]:
example_status = "Example 54 is labelled deliberate error or diagnostic example: NameError: name 'topic' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 54 is labelled deliberate error or diagnostic example: NameError: name 'topic' is not defined


### Example 55: 8.5 Parentheses for clarity

**Website source:** `python-foundations-ii.md`, line 1071  
**Status:** Deliberate error or diagnostic example — NameError: name 'topic' is not defined.

```python
if (topic == "Cycling" or topic == "Public Transport") and engagement > 100:  # Starts a decision when this condition is true.
    print("Selected")  # Displays information so the result can be inspected.
```

In [56]:
example_status = "Example 55 is labelled deliberate error or diagnostic example: NameError: name 'topic' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 55 is labelled deliberate error or diagnostic example: NameError: name 'topic' is not defined


### Example 56: 8.6 Common mistake: repeating the variable incorrectly

**Website source:** `python-foundations-ii.md`, line 1089  
**Status:** Runnable and audited — executed successfully during the audit.

```python
topic = "Cycling"  # Stores the calculated or supplied value in topic.

if topic == "Cycling" or "Public Transport":  # Starts a decision when this condition is true.
    print("Selected topic")  # Displays information so the result can be inspected.
```

In [57]:
topic = "Cycling"  # Stores the calculated or supplied value in topic.

if topic == "Cycling" or "Public Transport":  # Starts a decision when this condition is true.
    print("Selected topic")  # Displays information so the result can be inspected.

Selected topic


### Example 57: 8.6 Common mistake: repeating the variable incorrectly

**Website source:** `python-foundations-ii.md`, line 1100  
**Status:** Runnable and audited — executed successfully during the audit.

```python
topic = "Cycling"  # Stores the calculated or supplied value in topic.

if topic == "Cycling" or topic == "Public Transport":  # Starts a decision when this condition is true.
    print("Selected topic")  # Displays information so the result can be inspected.
```

In [58]:
topic = "Cycling"  # Stores the calculated or supplied value in topic.

if topic == "Cycling" or topic == "Public Transport":  # Starts a decision when this condition is true.
    print("Selected topic")  # Displays information so the result can be inspected.

Selected topic


### Example 58: 8.6 Common mistake: repeating the variable incorrectly

**Website source:** `python-foundations-ii.md`, line 1109  
**Status:** Deliberate error or diagnostic example — NameError: name 'topic' is not defined.

```python
if topic in ["Cycling", "Public Transport"]:  # Starts a decision when this condition is true.
    print("Selected topic")  # Displays information so the result can be inspected.
```

In [59]:
example_status = "Example 58 is labelled deliberate error or diagnostic example: NameError: name 'topic' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 58 is labelled deliberate error or diagnostic example: NameError: name 'topic' is not defined


### Example 59: Practice checkpoint 4

**Website source:** `python-foundations-ii.md`, line 1128  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 180  # Stores the calculated or supplied value in engagement.
actor_type = "NGO"  # Stores the calculated or supplied value in actor_type.

if engagement >= 150 and (actor_type == "Citizen Group" or actor_type == "NGO"):  # Starts a decision when this condition is true.
    print("Priority review")  # Displays information so the result can be inspected.
```

In [60]:
engagement = 180  # Stores the calculated or supplied value in engagement.
actor_type = "NGO"  # Stores the calculated or supplied value in actor_type.

if engagement >= 150 and (actor_type == "Citizen Group" or actor_type == "NGO"):  # Starts a decision when this condition is true.
    print("Priority review")  # Displays information so the result can be inspected.

Priority review


### Example 60: 9.1 Basic nested example

**Website source:** `python-foundations-ii.md`, line 1146  
**Status:** Runnable and audited — executed successfully during the audit.

```python
source_verified = True  # Stores the calculated or supplied value in source_verified.
engagement = 230  # Stores the calculated or supplied value in engagement.

if source_verified:  # Starts a decision when this condition is true.
    print("Source check passed")  # Displays information so the result can be inspected.

    if engagement >= 200:  # Starts a decision when this condition is true.
        print("High-engagement verified record")  # Displays information so the result can be inspected.
```

In [61]:
source_verified = True  # Stores the calculated or supplied value in source_verified.
engagement = 230  # Stores the calculated or supplied value in engagement.

if source_verified:  # Starts a decision when this condition is true.
    print("Source check passed")  # Displays information so the result can be inspected.

    if engagement >= 200:  # Starts a decision when this condition is true.
        print("High-engagement verified record")  # Displays information so the result can be inspected.

Source check passed
High-engagement verified record


### Example 61: 9.2 Nested decision with alternatives

**Website source:** `python-foundations-ii.md`, line 1170  
**Status:** Runnable and audited — executed successfully during the audit.

```python
source_verified = True  # Stores the calculated or supplied value in source_verified.
engagement = 80  # Stores the calculated or supplied value in engagement.

if source_verified:  # Starts a decision when this condition is true.
    if engagement >= 200:  # Starts a decision when this condition is true.
        print("High-engagement verified record")  # Displays information so the result can be inspected.
    else:  # Runs the fallback branch.
        print("Verified record with normal engagement")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Source review required")  # Displays information so the result can be inspected.
```

In [62]:
source_verified = True  # Stores the calculated or supplied value in source_verified.
engagement = 80  # Stores the calculated or supplied value in engagement.

if source_verified:  # Starts a decision when this condition is true.
    if engagement >= 200:  # Starts a decision when this condition is true.
        print("High-engagement verified record")  # Displays information so the result can be inspected.
    else:  # Runs the fallback branch.
        print("Verified record with normal engagement")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Source review required")  # Displays information so the result can be inspected.

Verified record with normal engagement


### Example 62: 9.3 Avoid unnecessary nesting

**Website source:** `python-foundations-ii.md`, line 1195  
**Status:** Deliberate error or diagnostic example — NameError: name 'source_verified' is not defined.

```python
if source_verified:  # Starts a decision when this condition is true.
    if engagement >= 200:  # Starts a decision when this condition is true.
        print("Selected")  # Displays information so the result can be inspected.
```

In [63]:
example_status = "Example 62 is labelled deliberate error or diagnostic example: NameError: name 'source_verified' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 62 is labelled deliberate error or diagnostic example: NameError: name 'source_verified' is not defined


### Example 63: 9.3 Avoid unnecessary nesting

**Website source:** `python-foundations-ii.md`, line 1203  
**Status:** Deliberate error or diagnostic example — NameError: name 'source_verified' is not defined.

```python
if source_verified and engagement >= 200:  # Starts a decision when this condition is true.
    print("Selected")  # Displays information so the result can be inspected.
```

In [64]:
example_status = "Example 63 is labelled deliberate error or diagnostic example: NameError: name 'source_verified' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 63 is labelled deliberate error or diagnostic example: NameError: name 'source_verified' is not defined


### Example 64: 10.1 Why conversion is necessary

**Website source:** `python-foundations-ii.md`, line 1220  
**Status:** Run manually with the stated input or file — interactive input.

```python
engagement = input("Enter the engagement value: ")  # Stores the calculated or supplied value in engagement.

print(type(engagement))  # Displays information so the result can be inspected.
```

In [65]:
example_status = 'Example 64 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 64 is labelled run manually with the stated input or file: interactive input


### Example 65: 10.1 Why conversion is necessary

**Website source:** `python-foundations-ii.md`, line 1237  
**Status:** Run manually with the stated input or file — interactive input.

```python
engagement = input("Enter the engagement value: ")  # Stores the calculated or supplied value in engagement.

if engagement > 100:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
```

In [66]:
example_status = 'Example 65 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 65 is labelled run manually with the stated input or file: interactive input


### Example 66: 10.1 Why conversion is necessary

**Website source:** `python-foundations-ii.md`, line 1248  
**Status:** Run manually with the stated input or file — interactive input.

```python
engagement = input("Enter the engagement value: ")  # Stores the calculated or supplied value in engagement.
engagement = int(engagement)  # Stores the calculated or supplied value in engagement.

if engagement > 100:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
```

In [67]:
example_status = 'Example 66 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 66 is labelled run manually with the stated input or file: interactive input


### Example 67: 10.2 Conversion in one line

**Website source:** `python-foundations-ii.md`, line 1260  
**Status:** Run manually with the stated input or file — interactive input.

```python
engagement = int(input("Enter the engagement value: "))  # Stores the calculated or supplied value in engagement.

if engagement > 100:  # Starts a decision when this condition is true.
    print("High engagement")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Normal engagement")  # Displays information so the result can be inspected.
```

In [68]:
example_status = 'Example 67 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 67 is labelled run manually with the stated input or file: interactive input


### Example 68: 10.3 Input assumptions

**Website source:** `python-foundations-ii.md`, line 1277  
**Status:** Run manually with the stated input or file — interactive input.

```python
age = int(input("Enter age: "))  # Stores the calculated or supplied value in age.
```

In [69]:
example_status = 'Example 68 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 68 is labelled run manually with the stated input or file: interactive input


### Example 69: 11.1 Why error handling matters

**Website source:** `python-foundations-ii.md`, line 1302  
**Status:** Run manually with the stated input or file — interactive input.

```python
engagement = int(input("Enter engagement: "))  # Stores the calculated or supplied value in engagement.
print("Recorded:", engagement)  # Displays information so the result can be inspected.
```

In [70]:
example_status = 'Example 69 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 69 is labelled run manually with the stated input or file: interactive input


### Example 70: 11.1 Why error handling matters

**Website source:** `python-foundations-ii.md`, line 1311  
**Status:** Run manually with the stated input or file — interactive input.

```python
try:  # Starts a protected block that may raise an expected error.
    engagement = int(input("Enter engagement: "))  # Stores the calculated or supplied value in engagement.
    print("Recorded:", engagement)  # Displays information so the result can be inspected.
except:  # Handles an error raised in the protected block.
    print("Error: enter a whole number")  # Displays information so the result can be inspected.
```

In [71]:
example_status = 'Example 70 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 70 is labelled run manually with the stated input or file: interactive input


### Example 71: 11.2 Understanding the structure

**Website source:** `python-foundations-ii.md`, line 1330  
**Status:** Deliberate error or diagnostic example — NameError: name 'code_to_run_if_an_error_occurs' is not defined.

```python
try:  # Starts a protected block that may raise an expected error.
    code_that_might_fail  # Runs this step from the tutorial example.
except:  # Handles an error raised in the protected block.
    code_to_run_if_an_error_occurs  # Runs this step from the tutorial example.
```

In [72]:
example_status = "Example 71 is labelled deliberate error or diagnostic example: NameError: name 'code_to_run_if_an_error_occurs' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 71 is labelled deliberate error or diagnostic example: NameError: name 'code_to_run_if_an_error_occurs' is not defined


### Example 72: 11.3 Catching a specific error

**Website source:** `python-foundations-ii.md`, line 1345  
**Status:** Run manually with the stated input or file — interactive input.

```python
try:  # Starts a protected block that may raise an expected error.
    engagement = int(input("Enter engagement: "))  # Stores the calculated or supplied value in engagement.
    print("Recorded:", engagement)  # Displays information so the result can be inspected.
except ValueError:  # Handles an error raised in the protected block.
    print("Error: enter a whole number")  # Displays information so the result can be inspected.
```

In [73]:
example_status = 'Example 72 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 72 is labelled run manually with the stated input or file: interactive input


### Example 73: 11.4 Adding a decision after valid input

**Website source:** `python-foundations-ii.md`, line 1359  
**Status:** Run manually with the stated input or file — interactive input.

```python
try:  # Starts a protected block that may raise an expected error.
    engagement = int(input("Enter engagement: "))  # Stores the calculated or supplied value in engagement.

    if engagement >= 200:  # Starts a decision when this condition is true.
        print("High engagement")  # Displays information so the result can be inspected.
    elif engagement >= 100:  # Checks another condition when earlier branches were false.
        print("Medium engagement")  # Displays information so the result can be inspected.
    else:  # Runs the fallback branch.
        print("Low engagement")  # Displays information so the result can be inspected.

except ValueError:  # Handles an error raised in the protected block.
    print("The engagement value must be a whole number")  # Displays information so the result can be inspected.
```

In [74]:
example_status = 'Example 73 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 73 is labelled run manually with the stated input or file: interactive input


### Example 74: 11.5 Valid type but invalid range

**Website source:** `python-foundations-ii.md`, line 1380  
**Status:** Run manually with the stated input or file — interactive input.

```python
try:  # Starts a protected block that may raise an expected error.
    percentage = float(input("Enter missing-data percentage: "))  # Stores the calculated or supplied value in percentage.

    if percentage < 0 or percentage > 100:  # Starts a decision when this condition is true.
        print("Error: percentage must be between 0 and 100")  # Displays information so the result can be inspected.
    elif percentage > 15:  # Checks another condition when earlier branches were false.
        print("Substantial missingness")  # Displays information so the result can be inspected.
    else:  # Runs the fallback branch.
        print("Missingness is within the initial review threshold")  # Displays information so the result can be inspected.

except ValueError:  # Handles an error raised in the protected block.
    print("Error: enter a numeric value")  # Displays information so the result can be inspected.
```

In [75]:
example_status = 'Example 74 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 74 is labelled run manually with the stated input or file: interactive input


### Example 75: 11.6 Avoid a completely empty `except`

**Website source:** `python-foundations-ii.md`, line 1409  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: invalid syntax.

```python
except:  # Handles an error raised in the protected block.
    print("Something went wrong")  # Displays information so the result can be inspected.
```

In [76]:
example_status = 'Example 75 is labelled deliberate error or diagnostic example: SyntaxError on line 1: invalid syntax'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 75 is labelled deliberate error or diagnostic example: SyntaxError on line 1: invalid syntax


### Example 76: 11.6 Avoid a completely empty `except`

**Website source:** `python-foundations-ii.md`, line 1416  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: invalid syntax.

```python
except ValueError:  # Handles an error raised in the protected block.
    print("Enter a numeric value")  # Displays information so the result can be inspected.
```

In [77]:
example_status = 'Example 76 is labelled deliberate error or diagnostic example: SyntaxError on line 1: invalid syntax'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 76 is labelled deliberate error or diagnostic example: SyntaxError on line 1: invalid syntax


### Example 77: Practice checkpoint 5

**Website source:** `python-foundations-ii.md`, line 1427  
**Status:** Run manually with the stated input or file — interactive input.

```python
number_of_records = int(input("Enter number of records: "))  # Stores the calculated or supplied value in number_of_records.

if number_of_records >= 100:  # Starts a decision when this condition is true.
    print("Suitable for the planned exercise")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Small dataset")  # Displays information so the result can be inspected.
```

In [78]:
example_status = 'Example 77 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 77 is labelled run manually with the stated input or file: interactive input


### Example 78: Practice checkpoint 5

**Website source:** `python-foundations-ii.md`, line 1439  
**Status:** Run manually with the stated input or file — interactive input.

```python
try:  # Starts a protected block that may raise an expected error.
    number_of_records = int(input("Enter number of records: "))  # Stores the calculated or supplied value in number_of_records.

    if number_of_records >= 100:  # Starts a decision when this condition is true.
        print("Suitable for the planned exercise")  # Displays information so the result can be inspected.
    else:  # Runs the fallback branch.
        print("Small dataset")  # Displays information so the result can be inspected.

except ValueError:  # Handles an error raised in the protected block.
    print("Enter a whole number")  # Displays information so the result can be inspected.
```

In [79]:
example_status = 'Example 78 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 78 is labelled run manually with the stated input or file: interactive input


### Example 79: 13.1 A simple definite loop

**Website source:** `python-foundations-ii.md`, line 1473  
**Status:** Runnable and audited — executed successfully during the audit.

```python
for number in [1, 2, 3]:  # Repeats the indented block for each value.
    print(number)  # Displays information so the result can be inspected.
```

In [80]:
for number in [1, 2, 3]:  # Repeats the indented block for each value.
    print(number)  # Displays information so the result can be inspected.

1
2
3


### Example 80: Explanation

**Website source:** `python-foundations-ii.md`, line 1488  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: expected an indented block after 'for' statement on line 1.

```python
for number in [1, 2, 3]:  # Repeats the indented block for each value.
```

In [81]:
example_status = "Example 80 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after 'for' statement on line 1"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 80 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after 'for' statement on line 1


### Example 81: 13.2 Looping through strings

**Website source:** `python-foundations-ii.md`, line 1504  
**Status:** Runnable and audited — executed successfully during the audit.

```python
topics = ["Cycling", "Public Transport", "Accessibility"]  # Stores the calculated or supplied value in topics.

for topic in topics:  # Repeats the indented block for each value.
    print("Current topic:", topic)  # Displays information so the result can be inspected.
```

In [82]:
topics = ["Cycling", "Public Transport", "Accessibility"]  # Stores the calculated or supplied value in topics.

for topic in topics:  # Repeats the indented block for each value.
    print("Current topic:", topic)  # Displays information so the result can be inspected.

Current topic: Cycling
Current topic: Public Transport
Current topic: Accessibility


### Example 82: 13.3 The code after the loop

**Website source:** `python-foundations-ii.md`, line 1533  
**Status:** Runnable and audited — executed successfully during the audit.

```python
topics = ["Cycling", "Public Transport", "Accessibility"]  # Stores the calculated or supplied value in topics.

for topic in topics:  # Repeats the indented block for each value.
    print(topic)  # Displays information so the result can be inspected.

print("All topics processed")  # Displays information so the result can be inspected.
```

In [83]:
topics = ["Cycling", "Public Transport", "Accessibility"]  # Stores the calculated or supplied value in topics.

for topic in topics:  # Repeats the indented block for each value.
    print(topic)  # Displays information so the result can be inspected.

print("All topics processed")  # Displays information so the result can be inspected.

Cycling
Public Transport
Accessibility
All topics processed


### Example 83: 13.4 Using `range()`

**Website source:** `python-foundations-ii.md`, line 1559  
**Status:** Runnable and audited — executed successfully during the audit.

```python
for number in range(5):  # Repeats the indented block for each value.
    print(number)  # Displays information so the result can be inspected.
```

In [84]:
for number in range(5):  # Repeats the indented block for each value.
    print(number)  # Displays information so the result can be inspected.

0
1
2
3
4


### Example 84: 13.5 Starting and stopping a range

**Website source:** `python-foundations-ii.md`, line 1580  
**Status:** Runnable and audited — executed successfully during the audit.

```python
for number in range(1, 6):  # Repeats the indented block for each value.
    print(number)  # Displays information so the result can be inspected.
```

In [85]:
for number in range(1, 6):  # Repeats the indented block for each value.
    print(number)  # Displays information so the result can be inspected.

1
2
3
4
5


### Example 85: 13.6 Adding a step

**Website source:** `python-foundations-ii.md`, line 1601  
**Status:** Runnable and audited — executed successfully during the audit.

```python
for number in range(0, 11, 2):  # Repeats the indented block for each value.
    print(number)  # Displays information so the result can be inspected.
```

In [86]:
for number in range(0, 11, 2):  # Repeats the indented block for each value.
    print(number)  # Displays information so the result can be inspected.

0
2
4
6
8
10


### Example 86: 13.7 Repeating a message

**Website source:** `python-foundations-ii.md`, line 1629  
**Status:** Runnable and audited — executed successfully during the audit.

```python
for repetition in range(3):  # Repeats the indented block for each value.
    print("Check the dataset")  # Displays information so the result can be inspected.
```

In [87]:
for repetition in range(3):  # Repeats the indented block for each value.
    print("Check the dataset")  # Displays information so the result can be inspected.

Check the dataset
Check the dataset
Check the dataset


### Example 87: 13.7 Repeating a message

**Website source:** `python-foundations-ii.md`, line 1646  
**Status:** Runnable and audited — executed successfully during the audit.

```python
for _ in range(3):  # Repeats the indented block for each value.
    print("Check the dataset")  # Displays information so the result can be inspected.
```

In [88]:
for _ in range(3):  # Repeats the indented block for each value.
    print("Check the dataset")  # Displays information so the result can be inspected.

Check the dataset
Check the dataset
Check the dataset


### Example 88: 13.8 Conditions inside a loop

**Website source:** `python-foundations-ii.md`, line 1655  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement_values = [35, 120, 240, 80]  # Stores the calculated or supplied value in engagement_values.

for engagement in engagement_values:  # Repeats the indented block for each value.
    if engagement >= 200:  # Starts a decision when this condition is true.
        print(engagement, "is high")  # Displays information so the result can be inspected.
    elif engagement >= 100:  # Checks another condition when earlier branches were false.
        print(engagement, "is medium")  # Displays information so the result can be inspected.
    else:  # Runs the fallback branch.
        print(engagement, "is low")  # Displays information so the result can be inspected.
```

In [89]:
engagement_values = [35, 120, 240, 80]  # Stores the calculated or supplied value in engagement_values.

for engagement in engagement_values:  # Repeats the indented block for each value.
    if engagement >= 200:  # Starts a decision when this condition is true.
        print(engagement, "is high")  # Displays information so the result can be inspected.
    elif engagement >= 100:  # Checks another condition when earlier branches were false.
        print(engagement, "is medium")  # Displays information so the result can be inspected.
    else:  # Runs the fallback branch.
        print(engagement, "is low")  # Displays information so the result can be inspected.

35 is low
120 is medium
240 is high
80 is low


### Example 89: 13.9 Counting values that meet a condition

**Website source:** `python-foundations-ii.md`, line 1682  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement_values = [35, 120, 240, 80, 310]  # Stores the calculated or supplied value in engagement_values.
high_count = 0  # Stores the calculated or supplied value in high_count.

for engagement in engagement_values:  # Repeats the indented block for each value.
    if engagement >= 200:  # Starts a decision when this condition is true.
        high_count = high_count + 1  # Stores the calculated or supplied value in high_count.

print("High-engagement records:", high_count)  # Displays information so the result can be inspected.
```

In [90]:
engagement_values = [35, 120, 240, 80, 310]  # Stores the calculated or supplied value in engagement_values.
high_count = 0  # Stores the calculated or supplied value in high_count.

for engagement in engagement_values:  # Repeats the indented block for each value.
    if engagement >= 200:  # Starts a decision when this condition is true.
        high_count = high_count + 1  # Stores the calculated or supplied value in high_count.

print("High-engagement records:", high_count)  # Displays information so the result can be inspected.

High-engagement records: 2


### Example 90: Step-by-step explanation

**Website source:** `python-foundations-ii.md`, line 1701  
**Status:** Runnable and audited — executed successfully during the audit.

```python
high_count = 0  # Stores the calculated or supplied value in high_count.
```

In [91]:
high_count = 0  # Stores the calculated or supplied value in high_count.

### Example 91: Step-by-step explanation

**Website source:** `python-foundations-ii.md`, line 1707  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: expected an indented block after 'for' statement on line 1.

```python
for engagement in engagement_values:  # Repeats the indented block for each value.
```

In [92]:
example_status = "Example 91 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after 'for' statement on line 1"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 91 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after 'for' statement on line 1


### Example 92: Step-by-step explanation

**Website source:** `python-foundations-ii.md`, line 1713  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: expected an indented block after 'if' statement on line 1.

```python
if engagement >= 200:  # Starts a decision when this condition is true.
```

In [93]:
example_status = "Example 92 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after 'if' statement on line 1"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 92 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after 'if' statement on line 1


### Example 93: Step-by-step explanation

**Website source:** `python-foundations-ii.md`, line 1719  
**Status:** Deliberate error or diagnostic example — NameError: name 'high_count' is not defined.

```python
high_count = high_count + 1  # Stores the calculated or supplied value in high_count.
```

In [94]:
example_status = "Example 93 is labelled deliberate error or diagnostic example: NameError: name 'high_count' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 93 is labelled deliberate error or diagnostic example: NameError: name 'high_count' is not defined


### Example 94: Step-by-step explanation

**Website source:** `python-foundations-ii.md`, line 1727  
**Status:** Deliberate error or diagnostic example — NameError: name 'high_count' is not defined.

```python
high_count += 1  # Runs this step from the tutorial example.
```

In [95]:
example_status = "Example 94 is labelled deliberate error or diagnostic example: NameError: name 'high_count' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 94 is labelled deliberate error or diagnostic example: NameError: name 'high_count' is not defined


### Example 95: 13.10 Accumulating a total

**Website source:** `python-foundations-ii.md`, line 1735  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement_values = [35, 120, 240, 80]  # Stores the calculated or supplied value in engagement_values.
total_engagement = 0  # Stores the calculated or supplied value in total_engagement.

for engagement in engagement_values:  # Repeats the indented block for each value.
    total_engagement = total_engagement + engagement  # Stores the calculated or supplied value in total_engagement.

print("Total engagement:", total_engagement)  # Displays information so the result can be inspected.
```

In [96]:
engagement_values = [35, 120, 240, 80]  # Stores the calculated or supplied value in engagement_values.
total_engagement = 0  # Stores the calculated or supplied value in total_engagement.

for engagement in engagement_values:  # Repeats the indented block for each value.
    total_engagement = total_engagement + engagement  # Stores the calculated or supplied value in total_engagement.

print("Total engagement:", total_engagement)  # Displays information so the result can be inspected.

Total engagement: 475


### Example 96: 13.10 Accumulating a total

**Website source:** `python-foundations-ii.md`, line 1753  
**Status:** Deliberate error or diagnostic example — NameError: name 'total_engagement' is not defined.

```python
average_engagement = total_engagement / len(engagement_values)  # Stores the calculated or supplied value in average_engagement.
print("Average engagement:", average_engagement)  # Displays information so the result can be inspected.
```

In [97]:
example_status = "Example 96 is labelled deliberate error or diagnostic example: NameError: name 'total_engagement' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 96 is labelled deliberate error or diagnostic example: NameError: name 'total_engagement' is not defined


### Example 97: 13.11 Deliberate indentation error

**Website source:** `python-foundations-ii.md`, line 1774  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 4: expected an indented block after 'for' statement on line 3.

```python
topics = ["Cycling", "Accessibility"]  # Stores the calculated or supplied value in topics.

for topic in topics:  # Repeats the indented block for each value.
print(topic)  # Displays information so the result can be inspected.
```

In [98]:
example_status = "Example 97 is labelled deliberate error or diagnostic example: SyntaxError on line 4: expected an indented block after 'for' statement on line 3"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 97 is labelled deliberate error or diagnostic example: SyntaxError on line 4: expected an indented block after 'for' statement on line 3


### Example 98: 13.11 Deliberate indentation error

**Website source:** `python-foundations-ii.md`, line 1783  
**Status:** Runnable and audited — executed successfully during the audit.

```python
topics = ["Cycling", "Accessibility"]  # Stores the calculated or supplied value in topics.

for topic in topics:  # Repeats the indented block for each value.
    print(topic)  # Displays information so the result can be inspected.
```

In [99]:
topics = ["Cycling", "Accessibility"]  # Stores the calculated or supplied value in topics.

for topic in topics:  # Repeats the indented block for each value.
    print(topic)  # Displays information so the result can be inspected.

Cycling
Accessibility


### Example 99: Practice checkpoint 6

**Website source:** `python-foundations-ii.md`, line 1798  
**Status:** Runnable and audited — executed successfully during the audit.

```python
topics = ["Cycling", "Parking", "Accessibility"]  # Stores the calculated or supplied value in topics.
```

In [100]:
topics = ["Cycling", "Parking", "Accessibility"]  # Stores the calculated or supplied value in topics.

### Example 100: Practice checkpoint 6

**Website source:** `python-foundations-ii.md`, line 1813  
**Status:** Runnable and audited — executed successfully during the audit.

```python
topics = ["Cycling", "Parking", "Accessibility"]  # Stores the calculated or supplied value in topics.

for topic in topics:  # Repeats the indented block for each value.
    print("Topic under review:", topic)  # Displays information so the result can be inspected.
```

In [101]:
topics = ["Cycling", "Parking", "Accessibility"]  # Stores the calculated or supplied value in topics.

for topic in topics:  # Repeats the indented block for each value.
    print("Topic under review:", topic)  # Displays information so the result can be inspected.

Topic under review: Cycling
Topic under review: Parking
Topic under review: Accessibility


### Example 101: 14.1 Countdown example

**Website source:** `python-foundations-ii.md`, line 1830  
**Status:** Run manually with the stated input or file — a while loop that should be run deliberately.

```python
number = 5  # Stores the calculated or supplied value in number.

while number > 0:  # Repeats the indented block while the condition remains true.
    print(number)  # Displays information so the result can be inspected.
    number = number - 1  # Stores the calculated or supplied value in number.

print("Finished")  # Displays information so the result can be inspected.
```

In [102]:
example_status = 'Example 101 is labelled run manually with the stated input or file: a while loop that should be run deliberately'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 101 is labelled run manually with the stated input or file: a while loop that should be run deliberately


### Example 102: Three essential parts

**Website source:** `python-foundations-ii.md`, line 1861  
**Status:** Runnable and audited — executed successfully during the audit.

```python
number = 5  # Stores the calculated or supplied value in number.
```

In [103]:
number = 5  # Stores the calculated or supplied value in number.

### Example 103: Three essential parts

**Website source:** `python-foundations-ii.md`, line 1867  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: expected an indented block after 'while' statement on line 1.

```python
while number > 0:  # Repeats the indented block while the condition remains true.
```

In [104]:
example_status = "Example 103 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after 'while' statement on line 1"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 103 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after 'while' statement on line 1


### Example 104: Three essential parts

**Website source:** `python-foundations-ii.md`, line 1873  
**Status:** Deliberate error or diagnostic example — NameError: name 'number' is not defined.

```python
number = number - 1  # Stores the calculated or supplied value in number.
```

In [105]:
example_status = "Example 104 is labelled deliberate error or diagnostic example: NameError: name 'number' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 104 is labelled deliberate error or diagnostic example: NameError: name 'number' is not defined

### Example 105: 14.2 An infinite loop

**Website source:** `python-foundations-ii.md`, line 1885  
**Status:** Run manually with the stated input or file — a while loop that should be run deliberately.

```python
number = 5  # Stores the calculated or supplied value in number.

while number > 0:  # Repeats the indented block while the condition remains true.
    print(number)  # Displays information so the result can be inspected.
```

In [106]:
example_status = 'Example 105 is labelled run manually with the stated input or file: a while loop that should be run deliberately'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 105 is labelled run manually with the stated input or file: a while loop that should be run deliberately


### Example 106: Repair

**Website source:** `python-foundations-ii.md`, line 1900  
**Status:** Run manually with the stated input or file — a while loop that should be run deliberately.

```python
number = 5  # Stores the calculated or supplied value in number.

while number > 0:  # Repeats the indented block while the condition remains true.
    print(number)  # Displays information so the result can be inspected.
    number = number - 1  # Stores the calculated or supplied value in number.
```

In [107]:
example_status = 'Example 106 is labelled run manually with the stated input or file: a while loop that should be run deliberately'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 106 is labelled run manually with the stated input or file: a while loop that should be run deliberately


### Example 107: 14.3 A loop that never starts

**Website source:** `python-foundations-ii.md`, line 1912  
**Status:** Run manually with the stated input or file — a while loop that should be run deliberately.

```python
number = 0  # Stores the calculated or supplied value in number.

while number > 0:  # Repeats the indented block while the condition remains true.
    print(number)  # Displays information so the result can be inspected.

print("Finished")  # Displays information so the result can be inspected.
```

In [108]:
example_status = 'Example 107 is labelled run manually with the stated input or file: a while loop that should be run deliberately'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 107 is labelled run manually with the stated input or file: a while loop that should be run deliberately


### Example 108: 14.4 Repeating until valid input

**Website source:** `python-foundations-ii.md`, line 1933  
**Status:** Run manually with the stated input or file — interactive input.

```python
valid_input = False  # Stores the calculated or supplied value in valid_input.

while not valid_input:  # Repeats the indented block while the condition remains true.
    answer = input("Type yes or no: ").strip().lower()  # Stores the calculated or supplied value in answer.

    if answer == "yes" or answer == "no":  # Starts a decision when this condition is true.
        valid_input = True  # Stores the calculated or supplied value in valid_input.
    else:  # Runs the fallback branch.
        print("Please type exactly yes or no")  # Displays information so the result can be inspected.

print("Accepted:", answer)  # Displays information so the result can be inspected.
```

In [109]:
example_status = 'Example 108 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 108 is labelled run manually with the stated input or file: interactive input


### Example 109: 14.5 `for` or `while`?

**Website source:** `python-foundations-ii.md`, line 1962  
**Status:** Deliberate error or diagnostic example — NameError: name 'topics' is not defined.

```python
for topic in topics:  # Repeats the indented block for each value.
    print(topic)  # Displays information so the result can be inspected.
```

In [110]:
example_status = "Example 109 is labelled deliberate error or diagnostic example: NameError: name 'topics' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 109 is labelled deliberate error or diagnostic example: NameError: name 'topics' is not defined


### Example 110: 14.5 `for` or `while`?

**Website source:** `python-foundations-ii.md`, line 1969  
**Status:** Run manually with the stated input or file — a while loop that should be run deliberately.

```python
while not valid_input:  # Repeats the indented block while the condition remains true.
    ...  # Runs this step from the tutorial example.
```

In [111]:
example_status = 'Example 110 is labelled run manually with the stated input or file: a while loop that should be run deliberately'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 110 is labelled run manually with the stated input or file: a while loop that should be run deliberately


### Example 111: 15.1 `break`

**Website source:** `python-foundations-ii.md`, line 1986  
**Status:** Runnable and audited — executed successfully during the audit.

```python
topics = ["Cycling", "Accessibility", "STOP", "Parking"]  # Stores the calculated or supplied value in topics.

for topic in topics:  # Repeats the indented block for each value.
    if topic == "STOP":  # Starts a decision when this condition is true.
        break  # Stops the nearest loop.

    print(topic)  # Displays information so the result can be inspected.

print("Loop ended")  # Displays information so the result can be inspected.
```

In [112]:
topics = ["Cycling", "Accessibility", "STOP", "Parking"]  # Stores the calculated or supplied value in topics.

for topic in topics:  # Repeats the indented block for each value.
    if topic == "STOP":  # Starts a decision when this condition is true.
        break  # Stops the nearest loop.

    print(topic)  # Displays information so the result can be inspected.

print("Loop ended")  # Displays information so the result can be inspected.

Cycling
Accessibility
Loop ended


### Example 112: 15.2 `continue`

**Website source:** `python-foundations-ii.md`, line 2014  
**Status:** Runnable and audited — executed successfully during the audit.

```python
values = [120, None, 75, 240]  # Stores the calculated or supplied value in values.

for value in values:  # Repeats the indented block for each value.
    if value is None:  # Starts a decision when this condition is true.
        continue  # Moves directly to the next loop iteration.

    print("Valid value:", value)  # Displays information so the result can be inspected.
```

In [113]:
values = [120, None, 75, 240]  # Stores the calculated or supplied value in values.

for value in values:  # Repeats the indented block for each value.
    if value is None:  # Starts a decision when this condition is true.
        continue  # Moves directly to the next loop iteration.

    print("Valid value:", value)  # Displays information so the result can be inspected.

Valid value: 120
Valid value: 75
Valid value: 240


### Example 113: 16.1 Defining and calling a function

**Website source:** `python-foundations-ii.md`, line 2058  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def show_welcome():  # Defines a reusable function.
    print("Welcome to the data-quality checker")  # Displays information so the result can be inspected.

show_welcome()  # Runs this step from the tutorial example.
```

In [114]:
def show_welcome():  # Defines a reusable function.
    print("Welcome to the data-quality checker")  # Displays information so the result can be inspected.

show_welcome()  # Runs this step from the tutorial example.

Welcome to the data-quality checker


### Example 114: Explanation

**Website source:** `python-foundations-ii.md`, line 2073  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: expected an indented block after function definition on line 1.

```python
def show_welcome():  # Defines a reusable function.
```

In [115]:
example_status = 'Example 114 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after function definition on line 1'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 114 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after function definition on line 1


### Example 115: Explanation

**Website source:** `python-foundations-ii.md`, line 2082  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: unexpected indent.

```python
    print("Welcome to the data-quality checker")  # Displays information so the result can be inspected.
```

In [116]:
example_status = 'Example 115 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 115 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent


### Example 116: Explanation

**Website source:** `python-foundations-ii.md`, line 2088  
**Status:** Deliberate error or diagnostic example — NameError: name 'show_welcome' is not defined.

```python
show_welcome()  # Runs this step from the tutorial example.
```

In [117]:
example_status = "Example 116 is labelled deliberate error or diagnostic example: NameError: name 'show_welcome' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 116 is labelled deliberate error or diagnostic example: NameError: name 'show_welcome' is not defined


### Example 117: 16.2 Meaningful function names

**Website source:** `python-foundations-ii.md`, line 2102  
**Status:** Deliberate error or diagnostic example — NameError: name 'calculate_percentage' is not defined.

```python
calculate_percentage()  # Runs this step from the tutorial example.
classify_engagement()  # Runs this step from the tutorial example.
check_missing_values()  # Runs this step from the tutorial example.
show_summary()  # Runs this step from the tutorial example.
```

In [118]:
example_status = "Example 117 is labelled deliberate error or diagnostic example: NameError: name 'calculate_percentage' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 117 is labelled deliberate error or diagnostic example: NameError: name 'calculate_percentage' is not defined


### Example 118: 16.2 Meaningful function names

**Website source:** `python-foundations-ii.md`, line 2111  
**Status:** Deliberate error or diagnostic example — NameError: name 'do_it' is not defined.

```python
do_it()  # Runs this step from the tutorial example.
thing()  # Runs this step from the tutorial example.
f1()  # Runs this step from the tutorial example.
xyz()  # Runs this step from the tutorial example.
```

In [119]:
example_status = "Example 118 is labelled deliberate error or diagnostic example: NameError: name 'do_it' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 118 is labelled deliberate error or diagnostic example: NameError: name 'do_it' is not defined


### Example 119: 16.3 Parameters and arguments

**Website source:** `python-foundations-ii.md`, line 2124  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def greet_actor(actor_name):  # Defines a reusable function.
    print("Record submitted by:", actor_name)  # Displays information so the result can be inspected.

greet_actor("Green Streets Association")  # Runs this step from the tutorial example.
greet_actor("Local Business Council")  # Runs this step from the tutorial example.
```

In [120]:
def greet_actor(actor_name):  # Defines a reusable function.
    print("Record submitted by:", actor_name)  # Displays information so the result can be inspected.

greet_actor("Green Streets Association")  # Runs this step from the tutorial example.
greet_actor("Local Business Council")  # Runs this step from the tutorial example.

Record submitted by: Green Streets Association
Record submitted by: Local Business Council


### Example 120: Terminology

**Website source:** `python-foundations-ii.md`, line 2143  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: expected an indented block after function definition on line 1.

```python
def greet_actor(actor_name):  # Defines a reusable function.
```

In [121]:
example_status = 'Example 120 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after function definition on line 1'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 120 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after function definition on line 1

### Example 121: Terminology

**Website source:** `python-foundations-ii.md`, line 2151  
**Status:** Deliberate error or diagnostic example — NameError: name 'greet_actor' is not defined.

```python
greet_actor("Green Streets Association")  # Runs this step from the tutorial example.
```

In [122]:
example_status = "Example 121 is labelled deliberate error or diagnostic example: NameError: name 'greet_actor' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 121 is labelled deliberate error or diagnostic example: NameError: name 'greet_actor' is not defined


### Example 122: 16.4 Multiple parameters

**Website source:** `python-foundations-ii.md`, line 2161  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def show_record(actor_name, topic, engagement):  # Defines a reusable function.
    print("Actor:", actor_name)  # Displays information so the result can be inspected.
    print("Topic:", topic)  # Displays information so the result can be inspected.
    print("Engagement:", engagement)  # Displays information so the result can be inspected.

show_record("Cycling Alliance", "Cycling", 245)  # Runs this step from the tutorial example.
```

In [123]:
def show_record(actor_name, topic, engagement):  # Defines a reusable function.
    print("Actor:", actor_name)  # Displays information so the result can be inspected.
    print("Topic:", topic)  # Displays information so the result can be inspected.
    print("Engagement:", engagement)  # Displays information so the result can be inspected.

show_record("Cycling Alliance", "Cycling", 245)  # Runs this step from the tutorial example.

Actor: Cycling Alliance
Topic: Cycling
Engagement: 245


### Example 123: 16.5 Returning a value

**Website source:** `python-foundations-ii.md`, line 2186  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def calculate_missing_percentage(missing_values, total_values):  # Defines a reusable function.
    percentage = missing_values / total_values * 100  # Stores the calculated or supplied value in percentage.
    return percentage  # Returns a result to the function caller.

result = calculate_missing_percentage(18, 200)  # Stores the calculated or supplied value in result.
print(result)  # Displays information so the result can be inspected.
```

In [124]:
def calculate_missing_percentage(missing_values, total_values):  # Defines a reusable function.
    percentage = missing_values / total_values * 100  # Stores the calculated or supplied value in percentage.
    return percentage  # Returns a result to the function caller.

result = calculate_missing_percentage(18, 200)  # Stores the calculated or supplied value in result.
print(result)  # Displays information so the result can be inspected.

9.0


### Example 124: Explanation

**Website source:** `python-foundations-ii.md`, line 2203  
**Status:** Deliberate error or diagnostic example — SyntaxError: 'return' outside function.

```python
return percentage  # Returns a result to the function caller.
```

In [125]:
example_status = "Example 124 is labelled deliberate error or diagnostic example: SyntaxError: 'return' outside function"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 124 is labelled deliberate error or diagnostic example: SyntaxError: 'return' outside function


### Example 125: Explanation

**Website source:** `python-foundations-ii.md`, line 2209  
**Status:** Deliberate error or diagnostic example — NameError: name 'calculate_missing_percentage' is not defined.

```python
result = calculate_missing_percentage(18, 200)  # Stores the calculated or supplied value in result.
```

In [126]:
example_status = "Example 125 is labelled deliberate error or diagnostic example: NameError: name 'calculate_missing_percentage' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 125 is labelled deliberate error or diagnostic example: NameError: name 'calculate_missing_percentage' is not defined


### Example 126: 16.6 `print()` and `return` are not the same

**Website source:** `python-foundations-ii.md`, line 2221  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def calculate_total(a, b):  # Defines a reusable function.
    print(a + b)  # Displays information so the result can be inspected.
```

In [127]:
def calculate_total(a, b):  # Defines a reusable function.
    print(a + b)  # Displays information so the result can be inspected.

### Example 127: 16.6 `print()` and `return` are not the same

**Website source:** `python-foundations-ii.md`, line 2228  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def calculate_total(a, b):  # Defines a reusable function.
    return a + b  # Returns a result to the function caller.
```

In [128]:
def calculate_total(a, b):  # Defines a reusable function.
    return a + b  # Returns a result to the function caller.

### Example 128: 16.6 `print()` and `return` are not the same

**Website source:** `python-foundations-ii.md`, line 2235  
**Status:** Deliberate error or diagnostic example — NameError: name 'calculate_total' is not defined.

```python
total = calculate_total(5, 7)  # Stores the calculated or supplied value in total.
average = total / 2  # Stores the calculated or supplied value in average.

print(average)  # Displays information so the result can be inspected.
```

In [129]:
example_status = "Example 128 is labelled deliberate error or diagnostic example: NameError: name 'calculate_total' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 128 is labelled deliberate error or diagnostic example: NameError: name 'calculate_total' is not defined


### Example 129: 16.7 A function with conditional logic

**Website source:** `python-foundations-ii.md`, line 2248  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def classify_engagement(engagement):  # Defines a reusable function.
    if engagement >= 200:  # Starts a decision when this condition is true.
        return "High"  # Returns a result to the function caller.
    elif engagement >= 100:  # Checks another condition when earlier branches were false.
        return "Medium"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Low"  # Returns a result to the function caller.

print(classify_engagement(240))  # Displays information so the result can be inspected.
print(classify_engagement(130))  # Displays information so the result can be inspected.
print(classify_engagement(45))  # Displays information so the result can be inspected.
```

In [130]:
def classify_engagement(engagement):  # Defines a reusable function.
    if engagement >= 200:  # Starts a decision when this condition is true.
        return "High"  # Returns a result to the function caller.
    elif engagement >= 100:  # Checks another condition when earlier branches were false.
        return "Medium"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Low"  # Returns a result to the function caller.

print(classify_engagement(240))  # Displays information so the result can be inspected.
print(classify_engagement(130))  # Displays information so the result can be inspected.
print(classify_engagement(45))  # Displays information so the result can be inspected.

High
Medium
Low


### Example 130: 16.8 A function with validation

**Website source:** `python-foundations-ii.md`, line 2276  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def classify_percentage(percentage):  # Defines a reusable function.
    if percentage < 0 or percentage > 100:  # Starts a decision when this condition is true.
        return "Invalid percentage"  # Returns a result to the function caller.
    elif percentage > 15:  # Checks another condition when earlier branches were false.
        return "Substantial missingness"  # Returns a result to the function caller.
    elif percentage > 5:  # Checks another condition when earlier branches were false.
        return "Moderate missingness"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Minor missingness"  # Returns a result to the function caller.

print(classify_percentage(18))  # Displays information so the result can be inspected.
print(classify_percentage(4))  # Displays information so the result can be inspected.
print(classify_percentage(120))  # Displays information so the result can be inspected.
```

In [131]:
def classify_percentage(percentage):  # Defines a reusable function.
    if percentage < 0 or percentage > 100:  # Starts a decision when this condition is true.
        return "Invalid percentage"  # Returns a result to the function caller.
    elif percentage > 15:  # Checks another condition when earlier branches were false.
        return "Substantial missingness"  # Returns a result to the function caller.
    elif percentage > 5:  # Checks another condition when earlier branches were false.
        return "Moderate missingness"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Minor missingness"  # Returns a result to the function caller.

print(classify_percentage(18))  # Displays information so the result can be inspected.
print(classify_percentage(4))  # Displays information so the result can be inspected.
print(classify_percentage(120))  # Displays information so the result can be inspected.

Substantial missingness
Minor missingness
Invalid percentage


### Example 131: 16.9 Local and global variables

**Website source:** `python-foundations-ii.md`, line 2306  
**Status:** Runnable and audited — executed successfully during the audit.

```python
status = "Global status"  # Stores the calculated or supplied value in status.

def show_status():  # Defines a reusable function.
    status = "Local status"  # Stores the calculated or supplied value in status.
    print(status)  # Displays information so the result can be inspected.

show_status()  # Runs this step from the tutorial example.
print(status)  # Displays information so the result can be inspected.
```

In [132]:
status = "Global status"  # Stores the calculated or supplied value in status.

def show_status():  # Defines a reusable function.
    status = "Local status"  # Stores the calculated or supplied value in status.
    print(status)  # Displays information so the result can be inspected.

show_status()  # Runs this step from the tutorial example.
print(status)  # Displays information so the result can be inspected.

Local status
Global status


### Example 132: Error 1: Function not called

**Website source:** `python-foundations-ii.md`, line 2338  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def show_message():  # Defines a reusable function.
    print("Hello")  # Displays information so the result can be inspected.
```

In [133]:
def show_message():  # Defines a reusable function.
    print("Hello")  # Displays information so the result can be inspected.

### Example 133: Error 1: Function not called

**Website source:** `python-foundations-ii.md`, line 2347  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def show_message():  # Defines a reusable function.
    print("Hello")  # Displays information so the result can be inspected.

show_message()  # Runs this step from the tutorial example.
```

In [134]:
def show_message():  # Defines a reusable function.
    print("Hello")  # Displays information so the result can be inspected.

show_message()  # Runs this step from the tutorial example.

Hello


### Example 134: Error 2: Missing argument

**Website source:** `python-foundations-ii.md`, line 2356  
**Status:** Deliberate error or diagnostic example — TypeError: greet() missing 1 required positional argument: 'name'.

```python
def greet(name):  # Defines a reusable function.
    print("Hello", name)  # Displays information so the result can be inspected.

greet()  # Runs this step from the tutorial example.
```

In [135]:
example_status = "Example 134 is labelled deliberate error or diagnostic example: TypeError: greet() missing 1 required positional argument: 'name'"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 134 is labelled deliberate error or diagnostic example: TypeError: greet() missing 1 required positional argument: 'name'


### Example 135: Error 2: Missing argument

**Website source:** `python-foundations-ii.md`, line 2367  
**Status:** Deliberate error or diagnostic example — NameError: name 'greet' is not defined.

```python
greet("Amina")  # Runs this step from the tutorial example.
```

In [136]:
example_status = "Example 135 is labelled deliberate error or diagnostic example: NameError: name 'greet' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 135 is labelled deliberate error or diagnostic example: NameError: name 'greet' is not defined


### Example 136: Error 3: Incorrect indentation

**Website source:** `python-foundations-ii.md`, line 2373  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 2: expected an indented block after function definition on line 1.

```python
def greet(name):  # Defines a reusable function.
print("Hello", name)  # Displays information so the result can be inspected.
```

In [137]:
example_status = 'Example 136 is labelled deliberate error or diagnostic example: SyntaxError on line 2: expected an indented block after function definition on line 1'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 136 is labelled deliberate error or diagnostic example: SyntaxError on line 2: expected an indented block after function definition on line 1


### Example 137: Error 3: Incorrect indentation

**Website source:** `python-foundations-ii.md`, line 2380  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def greet(name):  # Defines a reusable function.
    print("Hello", name)  # Displays information so the result can be inspected.
```

In [138]:
def greet(name):  # Defines a reusable function.
    print("Hello", name)  # Displays information so the result can be inspected.

### Example 138: Practice checkpoint 7

**Website source:** `python-foundations-ii.md`, line 2400  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def calculate_completion_rate(complete_records, total_records):  # Defines a reusable function.
    rate = complete_records / total_records * 100  # Stores the calculated or supplied value in rate.
    return rate  # Returns a result to the function caller.

result = calculate_completion_rate(180, 200)  # Stores the calculated or supplied value in result.
print(result)  # Displays information so the result can be inspected.
```

In [139]:
def calculate_completion_rate(complete_records, total_records):  # Defines a reusable function.
    rate = complete_records / total_records * 100  # Stores the calculated or supplied value in rate.
    return rate  # Returns a result to the function caller.

result = calculate_completion_rate(180, 200)  # Stores the calculated or supplied value in result.
print(result)  # Displays information so the result can be inspected.

90.0


### Example 139: 17.1 Apply one function to several values

**Website source:** `python-foundations-ii.md`, line 2423  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def classify_engagement(engagement):  # Defines a reusable function.
    if engagement >= 200:  # Starts a decision when this condition is true.
        return "High"  # Returns a result to the function caller.
    elif engagement >= 100:  # Checks another condition when earlier branches were false.
        return "Medium"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Low"  # Returns a result to the function caller.

engagement_values = [35, 120, 240, 80]  # Stores the calculated or supplied value in engagement_values.

for engagement in engagement_values:  # Repeats the indented block for each value.
    category = classify_engagement(engagement)  # Stores the calculated or supplied value in category.
    print(engagement, "->", category)  # Displays information so the result can be inspected.
```

In [140]:
def classify_engagement(engagement):  # Defines a reusable function.
    if engagement >= 200:  # Starts a decision when this condition is true.
        return "High"  # Returns a result to the function caller.
    elif engagement >= 100:  # Checks another condition when earlier branches were false.
        return "Medium"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Low"  # Returns a result to the function caller.

engagement_values = [35, 120, 240, 80]  # Stores the calculated or supplied value in engagement_values.

for engagement in engagement_values:  # Repeats the indented block for each value.
    category = classify_engagement(engagement)  # Stores the calculated or supplied value in category.
    print(engagement, "->", category)  # Displays information so the result can be inspected.

35 -> Low
120 -> Medium
240 -> High
80 -> Low


### Example 140: 17.2 Count function results

**Website source:** `python-foundations-ii.md`, line 2458  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def classify_engagement(engagement):  # Defines a reusable function.
    if engagement >= 200:  # Starts a decision when this condition is true.
        return "High"  # Returns a result to the function caller.
    elif engagement >= 100:  # Checks another condition when earlier branches were false.
        return "Medium"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Low"  # Returns a result to the function caller.

engagement_values = [35, 120, 240, 80, 310]  # Stores the calculated or supplied value in engagement_values.
high_count = 0  # Stores the calculated or supplied value in high_count.

for engagement in engagement_values:  # Repeats the indented block for each value.
    category = classify_engagement(engagement)  # Stores the calculated or supplied value in category.

    if category == "High":  # Starts a decision when this condition is true.
        high_count = high_count + 1  # Stores the calculated or supplied value in high_count.

print("High-engagement count:", high_count)  # Displays information so the result can be inspected.
```

In [141]:
def classify_engagement(engagement):  # Defines a reusable function.
    if engagement >= 200:  # Starts a decision when this condition is true.
        return "High"  # Returns a result to the function caller.
    elif engagement >= 100:  # Checks another condition when earlier branches were false.
        return "Medium"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Low"  # Returns a result to the function caller.

engagement_values = [35, 120, 240, 80, 310]  # Stores the calculated or supplied value in engagement_values.
high_count = 0  # Stores the calculated or supplied value in high_count.

for engagement in engagement_values:  # Repeats the indented block for each value.
    category = classify_engagement(engagement)  # Stores the calculated or supplied value in category.

    if category == "High":  # Starts a decision when this condition is true.
        high_count = high_count + 1  # Stores the calculated or supplied value in high_count.

print("High-engagement count:", high_count)  # Displays information so the result can be inspected.

High-engagement count: 2


### Example 141: 17.3 More advanced example: produce a simple report

**Website source:** `python-foundations-ii.md`, line 2489  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def classify_engagement(engagement):  # Defines a reusable function.
    if engagement >= 200:  # Starts a decision when this condition is true.
        return "High"  # Returns a result to the function caller.
    elif engagement >= 100:  # Checks another condition when earlier branches were false.
        return "Medium"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Low"  # Returns a result to the function caller.


engagement_values = [35, 120, 240, 80, 310]  # Stores the calculated or supplied value in engagement_values.

high_count = 0  # Stores the calculated or supplied value in high_count.
medium_count = 0  # Stores the calculated or supplied value in medium_count.
low_count = 0  # Stores the calculated or supplied value in low_count.

for engagement in engagement_values:  # Repeats the indented block for each value.
    category = classify_engagement(engagement)  # Stores the calculated or supplied value in category.

    if category == "High":  # Starts a decision when this condition is true.
        high_count = high_count + 1  # Stores the calculated or supplied value in high_count.
    elif category == "Medium":  # Checks another condition when earlier branches were false.
        medium_count = medium_count + 1  # Stores the calculated or supplied value in medium_count.
    else:  # Runs the fallback branch.
        low_count = low_count + 1  # Stores the calculated or supplied value in low_count.

print("Engagement report")  # Displays information so the result can be inspected.
print("-----------------")  # Displays information so the result can be inspected.
print("High:", high_count)  # Displays information so the result can be inspected.
print("Medium:", medium_count)  # Displays information so the result can be inspected.
print("Low:", low_count)  # Displays information so the result can be inspected.
```

In [142]:
def classify_engagement(engagement):  # Defines a reusable function.
    if engagement >= 200:  # Starts a decision when this condition is true.
        return "High"  # Returns a result to the function caller.
    elif engagement >= 100:  # Checks another condition when earlier branches were false.
        return "Medium"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Low"  # Returns a result to the function caller.


engagement_values = [35, 120, 240, 80, 310]  # Stores the calculated or supplied value in engagement_values.

high_count = 0  # Stores the calculated or supplied value in high_count.
medium_count = 0  # Stores the calculated or supplied value in medium_count.
low_count = 0  # Stores the calculated or supplied value in low_count.

for engagement in engagement_values:  # Repeats the indented block for each value.
    category = classify_engagement(engagement)  # Stores the calculated or supplied value in category.

    if category == "High":  # Starts a decision when this condition is true.
        high_count = high_count + 1  # Stores the calculated or supplied value in high_count.
    elif category == "Medium":  # Checks another condition when earlier branches were false.
        medium_count = medium_count + 1  # Stores the calculated or supplied value in medium_count.
    else:  # Runs the fallback branch.
        low_count = low_count + 1  # Stores the calculated or supplied value in low_count.

print("Engagement report")  # Displays information so the result can be inspected.
print("-----------------")  # Displays information so the result can be inspected.
print("High:", high_count)  # Displays information so the result can be inspected.
print("Medium:", medium_count)  # Displays information so the result can be inspected.
print("Low:", low_count)  # Displays information so the result can be inspected.

Engagement report
-----------------
High: 2
Medium: 1
Low: 2


### Example 142: 18.1 Importing a standard module

**Website source:** `python-foundations-ii.md`, line 2555  
**Status:** Runnable and audited — executed successfully during the audit.

```python
import math  # Imports a module used by this example.

result = math.sqrt(16)  # Stores the calculated or supplied value in result.
print(result)  # Displays information so the result can be inspected.
```

In [143]:
import math  # Imports a module used by this example.

result = math.sqrt(16)  # Stores the calculated or supplied value in result.
print(result)  # Displays information so the result can be inspected.

4.0


### Example 143: Explanation

**Website source:** `python-foundations-ii.md`, line 2570  
**Status:** Runnable and audited — executed successfully during the audit.

```python
import math  # Imports a module used by this example.
```

In [144]:
import math  # Imports a module used by this example.

### Example 144: Explanation

**Website source:** `python-foundations-ii.md`, line 2576  
**Status:** Deliberate error or diagnostic example — NameError: name 'math' is not defined. Did you forget to import 'math'?.

```python
math.sqrt(16)  # Runs this step from the tutorial example.
```

In [145]:
example_status = "Example 144 is labelled deliberate error or diagnostic example: NameError: name 'math' is not defined. Did you forget to import 'math'?"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 144 is labelled deliberate error or diagnostic example: NameError: name 'math' is not defined. Did you forget to import 'math'?


### Example 145: 18.2 Importing one item

**Website source:** `python-foundations-ii.md`, line 2588  
**Status:** Runnable and audited — executed successfully during the audit.

```python
from math import sqrt  # Imports a named tool from a module.

result = sqrt(25)  # Stores the calculated or supplied value in result.
print(result)  # Displays information so the result can be inspected.
```

In [146]:
from math import sqrt  # Imports a named tool from a module.

result = sqrt(25)  # Stores the calculated or supplied value in result.
print(result)  # Displays information so the result can be inspected.

5.0


### Example 146: 18.2 Importing one item

**Website source:** `python-foundations-ii.md`, line 2605  
**Status:** Run manually with the stated input or file — an intentionally incomplete function call.

```python
math.sqrt()  # Runs this step from the tutorial example.
```

In [147]:
example_status = 'Example 146 is labelled run manually with the stated input or file: an intentionally incomplete function call'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 146 is labelled run manually with the stated input or file: an intentionally incomplete function call


### Example 147: 18.3 Using an alias

**Website source:** `python-foundations-ii.md`, line 2617  
**Status:** Runnable and audited — executed successfully during the audit.

```python
import pandas as pd  # Imports a module used by this example.
```

In [148]:
import pandas as pd  # Imports a module used by this example.

### Example 148: 18.3 Using an alias

**Website source:** `python-foundations-ii.md`, line 2625  
**Status:** Runnable and audited — executed successfully during the audit.

```python
import math as m  # Imports a module used by this example.

print(m.sqrt(36))  # Displays information so the result can be inspected.
```

In [149]:
import math as m  # Imports a module used by this example.

print(m.sqrt(36))  # Displays information so the result can be inspected.

6.0


### Example 149: 18.3 Using an alias

**Website source:** `python-foundations-ii.md`, line 2639  
**Status:** Runnable and audited — executed successfully during the audit.

```python
import math as banana  # Imports a module used by this example.
```

In [150]:
import math as banana  # Imports a module used by this example.

### Example 150: 18.4 Example with the `random` module

**Website source:** `python-foundations-ii.md`, line 2649  
**Status:** Runnable and audited — executed successfully during the audit.

```python
import random  # Imports a module used by this example.

number = random.randint(1, 5)  # Stores the calculated or supplied value in number.
print(number)  # Displays information so the result can be inspected.
```

In [151]:
import random  # Imports a module used by this example.

number = random.randint(1, 5)  # Stores the calculated or supplied value in number.
print(number)  # Displays information so the result can be inspected.

3


### Example 151: 18.5 Import errors

**Website source:** `python-foundations-ii.md`, line 2668  
**Status:** Run manually with the stated input or file — an intentionally misspelled import.

```python
import maths  # Imports a module used by this example.
```

In [152]:
example_status = 'Example 151 is labelled run manually with the stated input or file: an intentionally misspelled import'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 151 is labelled run manually with the stated input or file: an intentionally misspelled import


### Example 152: 18.5 Import errors

**Website source:** `python-foundations-ii.md`, line 2680  
**Status:** Runnable and audited — executed successfully during the audit.

```python
import math  # Imports a module used by this example.
```

In [153]:
import math  # Imports a module used by this example.

### Example 153: 18.5 Import errors

**Website source:** `python-foundations-ii.md`, line 2686  
**Status:** Deliberate error or diagnostic example — AttributeError: module 'math' has no attribute 'squareroot'.

```python
import math  # Imports a module used by this example.

print(math.squareroot(16))  # Displays information so the result can be inspected.
```

In [154]:
example_status = "Example 153 is labelled deliberate error or diagnostic example: AttributeError: module 'math' has no attribute 'squareroot'"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 153 is labelled deliberate error or diagnostic example: AttributeError: module 'math' has no attribute 'squareroot'


### Example 154: 18.5 Import errors

**Website source:** `python-foundations-ii.md`, line 2696  
**Status:** Deliberate error or diagnostic example — NameError: name 'math' is not defined. Did you forget to import 'math'?.

```python
print(math.sqrt(16))  # Displays information so the result can be inspected.
```

In [155]:
example_status = "Example 154 is labelled deliberate error or diagnostic example: NameError: name 'math' is not defined. Did you forget to import 'math'?"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 154 is labelled deliberate error or diagnostic example: NameError: name 'math' is not defined. Did you forget to import 'math'?


### Example 155: 19.1 `SyntaxError`

**Website source:** `python-foundations-ii.md`, line 2722  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: expected ':'.

```python
if engagement > 100  # Starts a decision when this condition is true.
    print("High")  # Displays information so the result can be inspected.
```

In [156]:
example_status = "Example 155 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected ':'"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 155 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected ':'


### Example 156: 19.1 `SyntaxError`

**Website source:** `python-foundations-ii.md`, line 2731  
**Status:** Deliberate error or diagnostic example — NameError: name 'engagement' is not defined.

```python
if engagement > 100:  # Starts a decision when this condition is true.
    print("High")  # Displays information so the result can be inspected.
```

In [157]:
example_status = "Example 156 is labelled deliberate error or diagnostic example: NameError: name 'engagement' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 156 is labelled deliberate error or diagnostic example: NameError: name 'engagement' is not defined


### Example 157: 19.2 `IndentationError`

**Website source:** `python-foundations-ii.md`, line 2742  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 2: expected an indented block after 'for' statement on line 1.

```python
for topic in topics:  # Repeats the indented block for each value.
print(topic)  # Displays information so the result can be inspected.
```

In [158]:
example_status = "Example 157 is labelled deliberate error or diagnostic example: SyntaxError on line 2: expected an indented block after 'for' statement on line 1"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 157 is labelled deliberate error or diagnostic example: SyntaxError on line 2: expected an indented block after 'for' statement on line 1


### Example 158: 19.2 `IndentationError`

**Website source:** `python-foundations-ii.md`, line 2749  
**Status:** Deliberate error or diagnostic example — NameError: name 'topics' is not defined.

```python
for topic in topics:  # Repeats the indented block for each value.
    print(topic)  # Displays information so the result can be inspected.
```

In [159]:
example_status = "Example 158 is labelled deliberate error or diagnostic example: NameError: name 'topics' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 158 is labelled deliberate error or diagnostic example: NameError: name 'topics' is not defined


### Example 159: 19.3 `NameError`

**Website source:** `python-foundations-ii.md`, line 2760  
**Status:** Deliberate error or diagnostic example — NameError: name 'engagement' is not defined. Did you mean: 'engagment'?.

```python
engagment = 120  # Stores the calculated or supplied value in engagment.
print(engagement)  # Displays information so the result can be inspected.
```

In [160]:
example_status = "Example 159 is labelled deliberate error or diagnostic example: NameError: name 'engagement' is not defined. Did you mean: 'engagment'?"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 159 is labelled deliberate error or diagnostic example: NameError: name 'engagement' is not defined. Did you mean: 'engagment'?


### Example 160: 19.3 `NameError`

**Website source:** `python-foundations-ii.md`, line 2769  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 120  # Stores the calculated or supplied value in engagement.
print(engagement)  # Displays information so the result can be inspected.
```

In [161]:
engagement = 120  # Stores the calculated or supplied value in engagement.
print(engagement)  # Displays information so the result can be inspected.

120


### Example 161: 19.4 `TypeError`

**Website source:** `python-foundations-ii.md`, line 2780  
**Status:** Deliberate error or diagnostic example — TypeError: can only concatenate str (not "int") to str.

```python
engagement = "120"  # Stores the calculated or supplied value in engagement.
result = engagement + 10  # Stores the calculated or supplied value in result.
```

In [162]:
example_status = 'Example 161 is labelled deliberate error or diagnostic example: TypeError: can only concatenate str (not "int") to str'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 161 is labelled deliberate error or diagnostic example: TypeError: can only concatenate str (not "int") to str


### Example 162: 19.4 `TypeError`

**Website source:** `python-foundations-ii.md`, line 2789  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = "120"  # Stores the calculated or supplied value in engagement.
result = int(engagement) + 10  # Stores the calculated or supplied value in result.

print(result)  # Displays information so the result can be inspected.
```

In [163]:
engagement = "120"  # Stores the calculated or supplied value in engagement.
result = int(engagement) + 10  # Stores the calculated or supplied value in result.

print(result)  # Displays information so the result can be inspected.

130


### Example 163: 19.5 `ValueError`

**Website source:** `python-foundations-ii.md`, line 2802  
**Status:** Deliberate error or diagnostic example — ValueError: invalid literal for int() with base 10: 'high'.

```python
engagement = int("high")  # Stores the calculated or supplied value in engagement.
```

In [164]:
example_status = "Example 163 is labelled deliberate error or diagnostic example: ValueError: invalid literal for int() with base 10: 'high'"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 163 is labelled deliberate error or diagnostic example: ValueError: invalid literal for int() with base 10: 'high'


### Example 164: 19.5 `ValueError`

**Website source:** `python-foundations-ii.md`, line 2810  
**Status:** Run manually with the stated input or file — interactive input.

```python
try:  # Starts a protected block that may raise an expected error.
    engagement = int(input("Enter engagement: "))  # Stores the calculated or supplied value in engagement.
except ValueError:  # Handles an error raised in the protected block.
    print("Enter a whole number")  # Displays information so the result can be inspected.
```

In [165]:
example_status = 'Example 164 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 164 is labelled run manually with the stated input or file: interactive input


### Example 165: 19.6 `ModuleNotFoundError`

**Website source:** `python-foundations-ii.md`, line 2823  
**Status:** Run manually with the stated input or file — an intentionally misspelled import.

```python
import pandass  # Imports a module used by this example.
```

In [166]:
example_status = 'Example 165 is labelled run manually with the stated input or file: an intentionally misspelled import'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 165 is labelled run manually with the stated input or file: an intentionally misspelled import


### Example 166: 19.6 `ModuleNotFoundError`

**Website source:** `python-foundations-ii.md`, line 2829  
**Status:** Runnable and audited — executed successfully during the audit.

```python
import pandas  # Imports a module used by this example.
```

In [167]:
import pandas  # Imports a module used by this example.

### Example 167: 19.7 `TypeError` from a missing function argument

**Website source:** `python-foundations-ii.md`, line 2841  
**Status:** Deliberate error or diagnostic example — TypeError: classify() missing 1 required positional argument: 'value'.

```python
def classify(value):  # Defines a reusable function.
    return value > 100  # Returns a result to the function caller.

result = classify()  # Stores the calculated or supplied value in result.
```

In [168]:
example_status = "Example 167 is labelled deliberate error or diagnostic example: TypeError: classify() missing 1 required positional argument: 'value'"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 167 is labelled deliberate error or diagnostic example: TypeError: classify() missing 1 required positional argument: 'value'


### Example 168: 19.7 `TypeError` from a missing function argument

**Website source:** `python-foundations-ii.md`, line 2850  
**Status:** Deliberate error or diagnostic example — NameError: name 'classify' is not defined.

```python
result = classify(120)  # Stores the calculated or supplied value in result.
```

In [169]:
example_status = "Example 168 is labelled deliberate error or diagnostic example: NameError: name 'classify' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 168 is labelled deliberate error or diagnostic example: NameError: name 'classify' is not defined


### Example 169: 19.8 Logic errors

**Website source:** `python-foundations-ii.md`, line 2862  
**Status:** Runnable and audited — executed successfully during the audit.

```python
missing_values = 10  # Stores the calculated or supplied value in missing_values.
total_values = 200  # Stores the calculated or supplied value in total_values.

missing_percentage = total_values / missing_values * 100  # Stores the calculated or supplied value in missing_percentage.
print(missing_percentage)  # Displays information so the result can be inspected.
```

In [170]:
missing_values = 10  # Stores the calculated or supplied value in missing_values.
total_values = 200  # Stores the calculated or supplied value in total_values.

missing_percentage = total_values / missing_values * 100  # Stores the calculated or supplied value in missing_percentage.
print(missing_percentage)  # Displays information so the result can be inspected.

2000.0


### Example 170: 19.8 Logic errors

**Website source:** `python-foundations-ii.md`, line 2874  
**Status:** Deliberate error or diagnostic example — NameError: name 'missing_values' is not defined.

```python
missing_percentage = missing_values / total_values * 100  # Stores the calculated or supplied value in missing_percentage.
print(missing_percentage)  # Displays information so the result can be inspected.
```

In [171]:
example_status = "Example 170 is labelled deliberate error or diagnostic example: NameError: name 'missing_values' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 170 is labelled deliberate error or diagnostic example: NameError: name 'missing_values' is not defined


### Example 171: 20. Tracing code manually

**Website source:** `python-foundations-ii.md`, line 2895  
**Status:** Runnable and audited — executed successfully during the audit.

```python
count = 0  # Stores the calculated or supplied value in count.

for value in [40, 120, 220]:  # Repeats the indented block for each value.
    if value >= 100:  # Starts a decision when this condition is true.
        count = count + 1  # Stores the calculated or supplied value in count.

print(count)  # Displays information so the result can be inspected.
```

In [172]:
count = 0  # Stores the calculated or supplied value in count.

for value in [40, 120, 220]:  # Repeats the indented block for each value.
    if value >= 100:  # Starts a decision when this condition is true.
        count = count + 1  # Stores the calculated or supplied value in count.

print(count)  # Displays information so the result can be inspected.

2


### Example 172: 21.3 Step 2: Create the classification function

**Website source:** `python-foundations-ii.md`, line 2968  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def classify_missingness(percentage):  # Defines a reusable function.
    if percentage > 15:  # Starts a decision when this condition is true.
        return "Substantial missingness"  # Returns a result to the function caller.
    elif percentage > 5:  # Checks another condition when earlier branches were false.
        return "Moderate missingness"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Minor missingness"  # Returns a result to the function caller.
```

In [173]:
def classify_missingness(percentage):  # Defines a reusable function.
    if percentage > 15:  # Starts a decision when this condition is true.
        return "Substantial missingness"  # Returns a result to the function caller.
    elif percentage > 5:  # Checks another condition when earlier branches were false.
        return "Moderate missingness"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Minor missingness"  # Returns a result to the function caller.

### Example 173: 21.3 Step 2: Create the classification function

**Website source:** `python-foundations-ii.md`, line 2980  
**Status:** Deliberate error or diagnostic example — NameError: name 'classify_missingness' is not defined.

```python
print(classify_missingness(18))  # Displays information so the result can be inspected.
print(classify_missingness(10))  # Displays information so the result can be inspected.
print(classify_missingness(3))  # Displays information so the result can be inspected.
```

In [174]:
example_status = "Example 173 is labelled deliberate error or diagnostic example: NameError: name 'classify_missingness' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 173 is labelled deliberate error or diagnostic example: NameError: name 'classify_missingness' is not defined


### Example 174: 21.4 Step 3: Add input and error handling

**Website source:** `python-foundations-ii.md`, line 2998  
**Status:** Run manually with the stated input or file — interactive input.

```python
try:  # Starts a protected block that may raise an expected error.
    total_records = int(input("Enter total records: "))  # Stores the calculated or supplied value in total_records.
    missing_records = int(input("Enter missing records: "))  # Stores the calculated or supplied value in missing_records.

except ValueError:  # Handles an error raised in the protected block.
    print("Error: both values must be whole numbers")  # Displays information so the result can be inspected.
```

In [175]:
example_status = 'Example 174 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 174 is labelled run manually with the stated input or file: interactive input


### Example 175: 21.5 Step 4: Add validation

**Website source:** `python-foundations-ii.md`, line 3013  
**Status:** Run manually with the stated input or file — interactive input.

```python
try:  # Starts a protected block that may raise an expected error.
    total_records = int(input("Enter total records: "))  # Stores the calculated or supplied value in total_records.
    missing_records = int(input("Enter missing records: "))  # Stores the calculated or supplied value in missing_records.

    if total_records <= 0:  # Starts a decision when this condition is true.
        print("Error: total records must be greater than zero")  # Displays information so the result can be inspected.
    elif missing_records < 0:  # Checks another condition when earlier branches were false.
        print("Error: missing records cannot be negative")  # Displays information so the result can be inspected.
    elif missing_records > total_records:  # Checks another condition when earlier branches were false.
        print("Error: missing records cannot exceed total records")  # Displays information so the result can be inspected.
    else:  # Runs the fallback branch.
        print("Inputs accepted")  # Displays information so the result can be inspected.

except ValueError:  # Handles an error raised in the protected block.
    print("Error: both values must be whole numbers")  # Displays information so the result can be inspected.
```

In [176]:
example_status = 'Example 175 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 175 is labelled run manually with the stated input or file: interactive input


### Example 176: 21.6 Step 5: Complete the script

**Website source:** `python-foundations-ii.md`, line 3035  
**Status:** Run manually with the stated input or file — interactive input.

```python
def classify_missingness(percentage):  # Defines a reusable function.
    if percentage > 15:  # Starts a decision when this condition is true.
        return "Substantial missingness"  # Returns a result to the function caller.
    elif percentage > 5:  # Checks another condition when earlier branches were false.
        return "Moderate missingness"  # Returns a result to the function caller.
    else:  # Runs the fallback branch.
        return "Minor missingness"  # Returns a result to the function caller.


try:  # Starts a protected block that may raise an expected error.
    total_records = int(input("Enter total records: "))  # Stores the calculated or supplied value in total_records.
    missing_records = int(input("Enter missing records: "))  # Stores the calculated or supplied value in missing_records.

    if total_records <= 0:  # Starts a decision when this condition is true.
        print("Error: total records must be greater than zero")  # Displays information so the result can be inspected.

    elif missing_records < 0:  # Checks another condition when earlier branches were false.
        print("Error: missing records cannot be negative")  # Displays information so the result can be inspected.

    elif missing_records > total_records:  # Checks another condition when earlier branches were false.
        print("Error: missing records cannot exceed total records")  # Displays information so the result can be inspected.

    else:  # Runs the fallback branch.
        missing_percentage = missing_records / total_records * 100  # Stores the calculated or supplied value in missing_percentage.
        status = classify_missingness(missing_percentage)  # Stores the calculated or supplied value in status.

        print()  # Displays information so the result can be inspected.
        print("Data-quality report")  # Displays information so the result can be inspected.
        print("-------------------")  # Displays information so the result can be inspected.
        print("Total records:", total_records)  # Displays information so the result can be inspected.
        print("Missing records:", missing_records)  # Displays information so the result can be inspected.
        print("Missing percentage:", round(missing_percentage, 2))  # Displays information so the result can be inspected.
        print("Classification:", status)  # Displays information so the result can be inspected.

except ValueError:  # Handles an error raised in the protected block.
    print("Error: both values must be whole numbers")  # Displays information so the result can be inspected.
```

In [177]:
example_status = 'Example 176 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 176 is labelled run manually with the stated input or file: interactive input


### Example 177: Function definition

**Website source:** `python-foundations-ii.md`, line 3094  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: expected an indented block after function definition on line 1.

```python
def classify_missingness(percentage):  # Defines a reusable function.
```

In [178]:
example_status = 'Example 177 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after function definition on line 1'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 177 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after function definition on line 1


### Example 178: Function definition

**Website source:** `python-foundations-ii.md`, line 3100  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: unexpected indent.

```python
    if percentage > 15:  # Starts a decision when this condition is true.
```

In [179]:
example_status = 'Example 178 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 178 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent


### Example 179: Function definition

**Website source:** `python-foundations-ii.md`, line 3106  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: unexpected indent.

```python
        return "Substantial missingness"  # Returns a result to the function caller.
```

In [180]:
example_status = 'Example 179 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 179 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent


### Example 180: Input block

**Website source:** `python-foundations-ii.md`, line 3114  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: expected an indented block after 'try' statement on line 1.

```python
try:  # Starts a protected block that may raise an expected error.
```

In [181]:
example_status = "Example 180 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after 'try' statement on line 1"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 180 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected an indented block after 'try' statement on line 1


### Example 181: Input block

**Website source:** `python-foundations-ii.md`, line 3120  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: unexpected indent.

```python
    total_records = int(input("Enter total records: "))  # Stores the calculated or supplied value in total_records.
```

In [182]:
example_status = 'Example 181 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 181 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent


### Example 182: Validation block

**Website source:** `python-foundations-ii.md`, line 3128  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: unexpected indent.

```python
    if total_records <= 0:  # Starts a decision when this condition is true.
```

In [183]:
example_status = 'Example 182 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 182 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent


### Example 183: Validation block

**Website source:** `python-foundations-ii.md`, line 3134  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: unexpected indent.

```python
    elif missing_records > total_records:  # Checks another condition when earlier branches were false.
```

In [184]:
example_status = 'Example 183 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 183 is labelled deliberate error or diagnostic example: SyntaxError on line 1: unexpected indent


### Example 184: Calculation block

**Website source:** `python-foundations-ii.md`, line 3142  
**Status:** Deliberate error or diagnostic example — NameError: name 'missing_records' is not defined.

```python
missing_percentage = missing_records / total_records * 100  # Stores the calculated or supplied value in missing_percentage.
```

In [185]:
example_status = "Example 184 is labelled deliberate error or diagnostic example: NameError: name 'missing_records' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 184 is labelled deliberate error or diagnostic example: NameError: name 'missing_records' is not defined


### Example 185: Calculation block

**Website source:** `python-foundations-ii.md`, line 3148  
**Status:** Deliberate error or diagnostic example — NameError: name 'classify_missingness' is not defined.

```python
status = classify_missingness(missing_percentage)  # Stores the calculated or supplied value in status.
```

In [186]:
example_status = "Example 185 is labelled deliberate error or diagnostic example: NameError: name 'classify_missingness' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 185 is labelled deliberate error or diagnostic example: NameError: name 'classify_missingness' is not defined


### Example 186: Calculation block

**Website source:** `python-foundations-ii.md`, line 3154  
**Status:** Deliberate error or diagnostic example — NameError: name 'missing_percentage' is not defined.

```python
round(missing_percentage, 2)  # Runs this step from the tutorial example.
```

In [187]:
example_status = "Example 186 is labelled deliberate error or diagnostic example: NameError: name 'missing_percentage' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 186 is labelled deliberate error or diagnostic example: NameError: name 'missing_percentage' is not defined


### Example 187: Error block

**Website source:** `python-foundations-ii.md`, line 3162  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: invalid syntax.

```python
except ValueError:  # Handles an error raised in the protected block.
```

In [188]:
example_status = 'Example 187 is labelled deliberate error or diagnostic example: SyntaxError on line 1: invalid syntax'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 187 is labelled deliberate error or diagnostic example: SyntaxError on line 1: invalid syntax


### Example 188: 22. Advanced example: reviewing several records

**Website source:** `python-foundations-ii.md`, line 3210  
**Status:** Runnable and audited — executed successfully during the audit.

```python
def review_record(actor_type, engagement, source_verified):  # Defines a reusable function.
    if not source_verified:  # Starts a decision when this condition is true.
        return "Source review"  # Returns a result to the function caller.

    if engagement >= 200 and actor_type in ["Citizen Group", "NGO"]:  # Starts a decision when this condition is true.
        return "Priority review"  # Returns a result to the function caller.

    if engagement >= 100:  # Starts a decision when this condition is true.
        return "Standard review"  # Returns a result to the function caller.

    return "Low-priority review"  # Returns a result to the function caller.


records = [  # Stores the calculated or supplied value in records.
    ["Citizen Group", 240, True],  # Runs this step from the tutorial example.
    ["Business", 130, True],  # Runs this step from the tutorial example.
    ["NGO", 260, False],  # Runs this step from the tutorial example.
    ["Municipality", 75, True]  # Runs this step from the tutorial example.
]  # Runs this step from the tutorial example.

priority_count = 0  # Stores the calculated or supplied value in priority_count.
source_review_count = 0  # Stores the calculated or supplied value in source_review_count.

for record in records:  # Repeats the indented block for each value.
    actor_type = record[0]  # Stores the calculated or supplied value in actor_type.
    engagement = record[1]  # Stores the calculated or supplied value in engagement.
    source_verified = record[2]  # Stores the calculated or supplied value in source_verified.

    decision = review_record(actor_type, engagement, source_verified)  # Stores the calculated or supplied value in decision.

    print(actor_type, "->", decision)  # Displays information so the result can be inspected.

    if decision == "Priority review":  # Starts a decision when this condition is true.
        priority_count = priority_count + 1  # Stores the calculated or supplied value in priority_count.
    elif decision == "Source review":  # Checks another condition when earlier branches were false.
        source_review_count = source_review_count + 1  # Stores the calculated or supplied value in source_review_count.

print()  # Displays information so the result can be inspected.
print("Priority reviews:", priority_count)  # Displays information so the result can be inspected.
print("Source reviews:", source_review_count)  # Displays information so the result can be inspected.
```

In [189]:
def review_record(actor_type, engagement, source_verified):  # Defines a reusable function.
    if not source_verified:  # Starts a decision when this condition is true.
        return "Source review"  # Returns a result to the function caller.

    if engagement >= 200 and actor_type in ["Citizen Group", "NGO"]:  # Starts a decision when this condition is true.
        return "Priority review"  # Returns a result to the function caller.

    if engagement >= 100:  # Starts a decision when this condition is true.
        return "Standard review"  # Returns a result to the function caller.

    return "Low-priority review"  # Returns a result to the function caller.


records = [  # Stores the calculated or supplied value in records.
    ["Citizen Group", 240, True],  # Runs this step from the tutorial example.
    ["Business", 130, True],  # Runs this step from the tutorial example.
    ["NGO", 260, False],  # Runs this step from the tutorial example.
    ["Municipality", 75, True]  # Runs this step from the tutorial example.
]  # Runs this step from the tutorial example.

priority_count = 0  # Stores the calculated or supplied value in priority_count.
source_review_count = 0  # Stores the calculated or supplied value in source_review_count.

for record in records:  # Repeats the indented block for each value.
    actor_type = record[0]  # Stores the calculated or supplied value in actor_type.
    engagement = record[1]  # Stores the calculated or supplied value in engagement.
    source_verified = record[2]  # Stores the calculated or supplied value in source_verified.

    decision = review_record(actor_type, engagement, source_verified)  # Stores the calculated or supplied value in decision.

    print(actor_type, "->", decision)  # Displays information so the result can be inspected.

    if decision == "Priority review":  # Starts a decision when this condition is true.
        priority_count = priority_count + 1  # Stores the calculated or supplied value in priority_count.
    elif decision == "Source review":  # Checks another condition when earlier branches were false.
        source_review_count = source_review_count + 1  # Stores the calculated or supplied value in source_review_count.

print()  # Displays information so the result can be inspected.
print("Priority reviews:", priority_count)  # Displays information so the result can be inspected.
print("Source reviews:", source_review_count)  # Displays information so the result can be inspected.

Citizen Group -> Priority review
Business -> Standard review
NGO -> Source review
Municipality -> Low-priority review

Priority reviews: 1
Source reviews: 1


### Example 189: Activity 1: Predict and run

**Website source:** `python-foundations-ii.md`, line 3285  
**Status:** Runnable and audited — executed successfully during the audit.

```python
value = 12  # Stores the calculated or supplied value in value.

if value > 10:  # Starts a decision when this condition is true.
    print("A")  # Displays information so the result can be inspected.
elif value > 5:  # Checks another condition when earlier branches were false.
    print("B")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("C")  # Displays information so the result can be inspected.
```

In [190]:
value = 12  # Stores the calculated or supplied value in value.

if value > 10:  # Starts a decision when this condition is true.
    print("A")  # Displays information so the result can be inspected.
elif value > 5:  # Checks another condition when earlier branches were false.
    print("B")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("C")  # Displays information so the result can be inspected.

A


### Example 190: Activity 2: Modify

**Website source:** `python-foundations-ii.md`, line 3304  
**Status:** Runnable and audited — executed successfully during the audit.

```python
engagement = 125  # Stores the calculated or supplied value in engagement.

if engagement >= 200:  # Starts a decision when this condition is true.
    print("High")  # Displays information so the result can be inspected.
elif engagement >= 100:  # Checks another condition when earlier branches were false.
    print("Medium")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Low")  # Displays information so the result can be inspected.
```

In [191]:
engagement = 125  # Stores the calculated or supplied value in engagement.

if engagement >= 200:  # Starts a decision when this condition is true.
    print("High")  # Displays information so the result can be inspected.
elif engagement >= 100:  # Checks another condition when earlier branches were false.
    print("Medium")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("Low")  # Displays information so the result can be inspected.

Medium


### Example 191: Activity 3: Break and repair

**Website source:** `python-foundations-ii.md`, line 3330  
**Status:** Deliberate error or diagnostic example — SyntaxError on line 1: expected ':'.

```python
def classify(value)  # Defines a reusable function.
if value > 100:  # Starts a decision when this condition is true.
return "High"  # Returns a result to the function caller.
else  # Runs this step from the tutorial example.
return "Low"  # Returns a result to the function caller.

print(classify())  # Displays information so the result can be inspected.
```

In [192]:
example_status = "Example 191 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected ':'"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 191 is labelled deliberate error or diagnostic example: SyntaxError on line 1: expected ':'


### Example 192: Activity 4: Loop and count

**Website source:** `python-foundations-ii.md`, line 3348  
**Status:** Runnable and audited — executed successfully during the audit.

```python
missing_counts = [0, 3, 12, 4, 18, 2]  # Stores the calculated or supplied value in missing_counts.
```

In [193]:
missing_counts = [0, 3, 12, 4, 18, 2]  # Stores the calculated or supplied value in missing_counts.

### Example 193: Activity 5: Create a function

**Website source:** `python-foundations-ii.md`, line 3366  
**Status:** Deliberate error or diagnostic example — NameError: name 'calculate_percentage' is not defined.

```python
calculate_percentage(part, whole)  # Runs this step from the tutorial example.
```

In [194]:
example_status = "Example 193 is labelled deliberate error or diagnostic example: NameError: name 'calculate_percentage' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 193 is labelled deliberate error or diagnostic example: NameError: name 'calculate_percentage' is not defined


### Example 194: Activity 5: Create a function

**Website source:** `python-foundations-ii.md`, line 3377  
**Status:** Deliberate error or diagnostic example — NameError: name 'calculate_percentage' is not defined.

```python
calculate_percentage(15, 100)  # Runs this step from the tutorial example.
calculate_percentage(5, 0)  # Runs this step from the tutorial example.
```

In [195]:
example_status = "Example 194 is labelled deliberate error or diagnostic example: NameError: name 'calculate_percentage' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 194 is labelled deliberate error or diagnostic example: NameError: name 'calculate_percentage' is not defined


### Example 195: Activity 7: Meaningful mini-case

**Website source:** `python-foundations-ii.md`, line 3401  
**Status:** Runnable and audited — executed successfully during the audit.

```python
confidence_scores = [85, 42, 91, 67, 50, 78]  # Stores the calculated or supplied value in confidence_scores.
```

In [196]:
confidence_scores = [85, 42, 91, 67, 50, 78]  # Stores the calculated or supplied value in confidence_scores.

### Example 196: Question 1

**Website source:** `python-foundations-ii.md`, line 3431  
**Status:** Runnable and audited — executed successfully during the audit.

```python
x = 5  # Stores the calculated or supplied value in x.
```

In [197]:
x = 5  # Stores the calculated or supplied value in x.

### Example 197: Question 1

**Website source:** `python-foundations-ii.md`, line 3437  
**Status:** Deliberate error or diagnostic example — NameError: name 'x' is not defined.

```python
x == 5  # Runs this step from the tutorial example.
```

In [198]:
example_status = "Example 197 is labelled deliberate error or diagnostic example: NameError: name 'x' is not defined"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 197 is labelled deliberate error or diagnostic example: NameError: name 'x' is not defined


### Example 198: Question 4

**Website source:** `python-foundations-ii.md`, line 3453  
**Status:** Runnable and audited — executed successfully during the audit.

```python
score = 75  # Stores the calculated or supplied value in score.

if score >= 80:  # Starts a decision when this condition is true.
    print("A")  # Displays information so the result can be inspected.
elif score >= 60:  # Checks another condition when earlier branches were false.
    print("B")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("C")  # Displays information so the result can be inspected.
```

In [199]:
score = 75  # Stores the calculated or supplied value in score.

if score >= 80:  # Starts a decision when this condition is true.
    print("A")  # Displays information so the result can be inspected.
elif score >= 60:  # Checks another condition when earlier branches were false.
    print("B")  # Displays information so the result can be inspected.
else:  # Runs the fallback branch.
    print("C")  # Displays information so the result can be inspected.

B


### Example 199: Question 5

**Website source:** `python-foundations-ii.md`, line 3468  
**Status:** Run manually with the stated input or file — interactive input.

```python
number = input("Enter a number: ")  # Stores the calculated or supplied value in number.
print(number + 1)  # Displays information so the result can be inspected.
```

In [200]:
example_status = 'Example 199 is labelled run manually with the stated input or file: interactive input'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 199 is labelled run manually with the stated input or file: interactive input


### Example 200: Question 7

**Website source:** `python-foundations-ii.md`, line 3481  
**Status:** Run manually with the stated input or file — a while loop that should be run deliberately.

```python
count = 5  # Stores the calculated or supplied value in count.

while count > 0:  # Repeats the indented block while the condition remains true.
    print(count)  # Displays information so the result can be inspected.
```

In [201]:
example_status = 'Example 200 is labelled run manually with the stated input or file: a while loop that should be run deliberately'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 200 is labelled run manually with the stated input or file: a while loop that should be run deliberately


### Example 201: Question 10

**Website source:** `python-foundations-ii.md`, line 3500  
**Status:** Deliberate error or diagnostic example — ValueError: invalid literal for int() with base 10: 'hello'.

```python
int("hello")  # Runs this step from the tutorial example.
```

In [202]:
example_status = "Example 201 is labelled deliberate error or diagnostic example: ValueError: invalid literal for int() with base 10: 'hello'"  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 201 is labelled deliberate error or diagnostic example: ValueError: invalid literal for int() with base 10: 'hello'


### Example 202: 29. What comes next

**Website source:** `python-foundations-ii.md`, line 3666  
**Status:** Run manually with the stated input or file — an external CSV file.

```python
import pandas as pd  # Imports a module used by this example.

data = pd.read_csv("green_mobility_records.csv")  # Stores the calculated or supplied value in data.
selected_data = data[data["engagement"] >= 100]  # Runs this step from the tutorial example.
```

In [203]:
example_status = 'Example 202 is labelled run manually with the stated input or file: an external CSV file'  # Stores the audit result without executing unsafe or deliberately broken code.
print(example_status)  # Displays why the original snippet is not run automatically.

Example 202 is labelled run manually with the stated input or file: an external CSV file


## Checks

- Total website Python blocks included: **202**
- Runnable and audited: **97**
- Deliberate error or diagnostic examples: **75**
- Interactive, loop-safety, plot, or file-dependent examples: **30**
- Syntax references: **0**

All executable cells in this notebook are safe for top-to-bottom execution. Deliberately broken examples remain available as commented code for classroom diagnosis.

## Next Steps

Use the shorter lecture examples notebook for live teaching, the exercise notebook for student work, and this complete companion whenever a website code example needs to be run or copied.