# Lecture 5: Examples 3.1–3.13

The exact example and exercise numbers match the live tutorial. Open an item from the index below, or search for its full number. Run **Setup** before the core examples and solutions. Tutorial 3.14 contains standalone guided examples. The data are synthetic teaching records.


## Numbered index

| Number | Exact tutorial title |
|---|---|
| [Example 3.1.1](#scrollTo=l05-example-3-1-1) | Why move beyond individual variables? |
| [Example 3.1.2](#scrollTo=l05-example-3-1-2) | Identify the unit of observation |
| [Example 3.1.3](#scrollTo=l05-example-3-1-3) | Variable versus value |
| [Example 3.1.4](#scrollTo=l05-example-3-1-4) | A category is a modelling decision |
| [Example 3.2.1](#scrollTo=l05-example-3-2-1) | Delimiters are not always commas |
| [Example 3.2.2](#scrollTo=l05-example-3-2-2) | Read a CSV mentally |
| [Example 3.2.3](#scrollTo=l05-example-3-2-3) | Detect a delimiter problem |
| [Example 3.3.1](#scrollTo=l05-example-3-3-1) | Import pandas |
| [Example 3.3.2](#scrollTo=l05-example-3-3-2) | Line-by-line explanation |
| [Example 3.3.3](#scrollTo=l05-example-3-3-3) | Confirm pandas is available |
| [Example 3.3.4](#scrollTo=l05-example-3-3-4) | What is a DataFrame? |
| [Example 3.3.5](#scrollTo=l05-example-3-3-5) | DataFrame versus Series |
| [Example 3.3.6](#scrollTo=l05-example-3-3-6) | The main course loading method: raw GitHub URL |
| [Example 3.3.7](#scrollTo=l05-example-3-3-7) | Load from a local path |
| [Example 3.3.8](#scrollTo=l05-example-3-3-8) | Uploading a CSV in Google Colab |
| [Example 3.3.9](#scrollTo=l05-example-3-3-9) | Upload through Python |
| [Example 3.3.10](#scrollTo=l05-example-3-3-10) | Wrong delimiter |
| [Example 3.3.11](#scrollTo=l05-example-3-3-11) | Encoding error |
| [Example 3.3.12](#scrollTo=l05-example-3-3-12) | Methods versus attributes |
| [Example 3.3.13](#scrollTo=l05-example-3-3-13) | Broken code |
| [Example 3.4.1](#scrollTo=l05-example-3-4-1) | Start from a fresh load |
| [Example 3.4.2](#scrollTo=l05-example-3-4-2) | head() — inspect the first rows |
| [Example 3.4.3](#scrollTo=l05-example-3-4-3) | tail() — inspect the final rows |
| [Example 3.4.4](#scrollTo=l05-example-3-4-4) | sample() — inspect rows from different positions |
| [Example 3.4.5](#scrollTo=l05-example-3-4-5) | shape — how many rows and columns? |
| [Example 3.4.6](#scrollTo=l05-example-3-4-6) | len(df) — another way to count rows |
| [Example 3.4.7](#scrollTo=l05-example-3-4-7) | columns — inspect column names |
| [Example 3.4.8](#scrollTo=l05-example-3-4-8) | index — inspect row labels |
| [Example 3.4.9](#scrollTo=l05-example-3-4-9) | dtypes — how pandas currently represents each column |
| [Example 3.4.10](#scrollTo=l05-example-3-4-10) | info() — compact structural inspection |
| [Example 3.4.11](#scrollTo=l05-example-3-4-11) | A repeatable first-inspection routine |
| [Example 3.4.12](#scrollTo=l05-example-3-4-12) | Interpret shape correctly |
| [Example 3.4.13](#scrollTo=l05-example-3-4-13) | Compare `head()` and `sample()` |
| [Example 3.4.14](#scrollTo=l05-example-3-4-14) | Broken code |
| [Example 3.4.15](#scrollTo=l05-example-3-4-15) | Repair |
| [Example 3.5.1](#scrollTo=l05-example-3-5-1) | Select one column |
| [Example 3.5.2](#scrollTo=l05-example-3-5-2) | Why the column name uses quotation marks |
| [Example 3.5.3](#scrollTo=l05-example-3-5-3) | Select a numeric column |
| [Example 3.5.4](#scrollTo=l05-example-3-5-4) | Select several columns |
| [Example 3.5.5](#scrollTo=l05-example-3-5-5) | Build a readable preview table |
| [Example 3.5.6](#scrollTo=l05-example-3-5-6) | Selecting by label with .loc[] |
| [Example 3.5.7](#scrollTo=l05-example-3-5-7) | Important slicing detail |
| [Example 3.5.8](#scrollTo=l05-example-3-5-8) | Selecting by position with .iloc[] |
| [Example 3.5.9](#scrollTo=l05-example-3-5-9) | Boolean filtering |
| [Example 3.5.10](#scrollTo=l05-example-3-5-10) | Filter by category |
| [Example 3.5.11](#scrollTo=l05-example-3-5-11) | Combine conditions with & |
| [Example 3.5.12](#scrollTo=l05-example-3-5-12) | Why the parentheses matter |
| [Example 3.5.13](#scrollTo=l05-example-3-5-13) | Combine alternatives with | |
| [Example 3.5.14](#scrollTo=l05-example-3-5-14) | Use .isin() for several allowed categories |
| [Example 3.5.15](#scrollTo=l05-example-3-5-15) | Filter and then choose columns |
| [Example 3.5.16](#scrollTo=l05-example-3-5-16) | Filtering is an analytical decision |
| [Example 3.5.17](#scrollTo=l05-example-3-5-17) | Broken code 1 |
| [Example 3.5.18](#scrollTo=l05-example-3-5-18) | Repair |
| [Example 3.5.19](#scrollTo=l05-example-3-5-19) | Broken code 2 |
| [Example 3.5.20](#scrollTo=l05-example-3-5-20) | Repair |
| [Example 3.6.1](#scrollTo=l05-example-3-6-1) | Inspect pandas dtypes |
| [Example 3.6.2](#scrollTo=l05-example-3-6-2) | Build a conceptual type table |
| [Example 3.6.3](#scrollTo=l05-example-3-6-3) | Compare technical and conceptual types |
| [Example 3.7.1](#scrollTo=l05-example-3-7-1) | count() — count non-missing values |
| [Example 3.7.2](#scrollTo=l05-example-3-7-2) | count() versus len() |
| [Example 3.7.3](#scrollTo=l05-example-3-7-3) | sum() — total a numeric column |
| [Example 3.7.4](#scrollTo=l05-example-3-7-4) | mean() — arithmetic average |
| [Example 3.7.5](#scrollTo=l05-example-3-7-5) | median() — middle value |
| [Example 3.7.6](#scrollTo=l05-example-3-7-6) | min() and max() |
| [Example 3.7.7](#scrollTo=l05-example-3-7-7) | std() — standard deviation |
| [Example 3.7.8](#scrollTo=l05-example-3-7-8) | describe() — several summaries together |
| [Example 3.7.9](#scrollTo=l05-example-3-7-9) | round() for readable output |
| [Example 3.7.10](#scrollTo=l05-example-3-7-10) | Received and resolved totals |
| [Example 3.7.11](#scrollTo=l05-example-3-7-11) | Find the row associated with an extreme value |
| [Example 3.7.12](#scrollTo=l05-example-3-7-12) | Inspect the negative minimum |
| [Example 3.7.13](#scrollTo=l05-example-3-7-13) | Missing values and numerical calculations |
| [Example 3.7.14](#scrollTo=l05-example-3-7-14) | Preliminary satisfaction mean |
| [Example 3.7.18](#scrollTo=l05-example-3-7-18) | A numerical summary |
| [Example 3.8.1](#scrollTo=l05-example-3-8-1) | Column arithmetic |
| [Example 3.8.2](#scrollTo=l05-example-3-8-2) | Inspect the derived column |
| [Example 3.8.3](#scrollTo=l05-example-3-8-3) | Create a row-level resolution rate |
| [Example 3.8.4](#scrollTo=l05-example-3-8-4) | Inspect the rate |
| [Example 3.8.5](#scrollTo=l05-example-3-8-5) | Method A — calculate each row's percentage, then average the percentages |
| [Example 3.8.6](#scrollTo=l05-example-3-8-6) | Method B — divide total resolved by total received |
| [Example 3.8.7](#scrollTo=l05-example-3-8-7) | Percentage of rows with missing feedback |
| [Example 3.8.8](#scrollTo=l05-example-3-8-8) | Percentage of rows belonging to a category |
| [Example 3.8.9](#scrollTo=l05-example-3-8-9) | Create a clearly named percentage |
| [Example 3.9.1](#scrollTo=l05-example-3-9-1) | Inspect unique values before counting them |
| [Example 3.9.2](#scrollTo=l05-example-3-9-2) | Count distinct values with nunique() |
| [Example 3.9.3](#scrollTo=l05-example-3-9-3) | Frequency table with value_counts() |
| [Example 3.9.4](#scrollTo=l05-example-3-9-4) | Percentages with normalize=True |
| [Example 3.9.5](#scrollTo=l05-example-3-9-5) | Include missing values when relevant |
| [Example 3.9.6](#scrollTo=l05-example-3-9-6) | Mode |
| [Example 3.9.7](#scrollTo=l05-example-3-9-7) | Introductory groupby() |
| [Example 3.9.8](#scrollTo=l05-example-3-9-8) | Group totals |
| [Example 3.9.9](#scrollTo=l05-example-3-9-9) | Several calculations at once with .agg() |
| [Example 3.9.10](#scrollTo=l05-example-3-9-10) | Grouping by a dirty category can mislead |
| [Example 3.9.11](#scrollTo=l05-example-3-9-11) | Cross-tabulation with pd.crosstab() |
| [Example 3.9.12](#scrollTo=l05-example-3-9-12) | Percentage crosstab — optional extension |
| [Example 3.9.13](#scrollTo=l05-example-3-9-13) | Compare satisfaction by service type |
| [Example 3.10.1](#scrollTo=l05-example-3-10-1) | Missing values with isna() |
| [Example 3.10.2](#scrollTo=l05-example-3-10-2) | Total recognised missing cells |
| [Example 3.10.3](#scrollTo=l05-example-3-10-3) | Missing percentages |
| [Example 3.10.4](#scrollTo=l05-example-3-10-4) | Missing satisfaction score |
| [Example 3.10.5](#scrollTo=l05-example-3-10-5) | Missing feedback |
| [Example 3.10.6](#scrollTo=l05-example-3-10-6) | Exact duplicate rows |
| [Example 3.10.7](#scrollTo=l05-example-3-10-7) | Why only one duplicate is counted |
| [Example 3.10.8](#scrollTo=l05-example-3-10-8) | Duplicate identifiers are not the same as duplicate rows |
| [Example 3.10.9](#scrollTo=l05-example-3-10-9) | Category consistency |
| [Example 3.10.10](#scrollTo=l05-example-3-10-10) | Negative case counts |
| [Example 3.10.11](#scrollTo=l05-example-3-10-11) | Out-of-range satisfaction |
| [Example 3.10.12](#scrollTo=l05-example-3-10-12) | Resolved greater than received |
| [Example 3.10.13](#scrollTo=l05-example-3-10-13) | Detect a numeric-looking column containing text |
| [Example 3.10.14](#scrollTo=l05-example-3-10-14) | Important |
| [Example 3.10.15](#scrollTo=l05-example-3-10-15) | Detect invalid date-like values without overwriting the raw column |
| [Example 3.10.16](#scrollTo=l05-example-3-10-16) | Build a first data-quality summary |
| [Example 3.10.17](#scrollTo=l05-example-3-10-17) | Separate observation from action |
| [Example 3.10.18](#scrollTo=l05-example-3-10-18) | Quality problem changes a calculation |
| [Example 3.11.1](#scrollTo=l05-example-3-11-1) | Start by reading the text |
| [Example 3.11.2](#scrollTo=l05-example-3-11-2) | Count available text responses |
| [Example 3.11.3](#scrollTo=l05-example-3-11-3) | Character length |
| [Example 3.11.4](#scrollTo=l05-example-3-11-4) | Approximate word count with pandas string methods |
| [Example 3.11.5](#scrollTo=l05-example-3-11-5) | Search for a literal word with .str.contains() |
| [Example 3.11.6](#scrollTo=l05-example-3-11-6) | Explain each argument |
| [Example 3.11.7](#scrollTo=l05-example-3-11-7) | Search for alternatives with a simple pattern |
| [Example 3.11.8](#scrollTo=l05-example-3-11-8) | Search for clarity-related wording |
| [Example 3.11.9](#scrollTo=l05-example-3-11-9) | Search for speed-related wording |
| [Example 3.11.10](#scrollTo=l05-example-3-11-10) | Literal versus regex search |
| [Example 3.11.11](#scrollTo=l05-example-3-11-11) | Compare text presence with a numeric variable |
| [Example 3.11.12](#scrollTo=l05-example-3-11-12) | Text length by service type |
| [Example 3.11.13](#scrollTo=l05-example-3-11-13) | Identify potentially difficult experiences |
| [Example 3.12.1](#scrollTo=l05-example-3-12-1) | From an idea to an operational rule |
| [Example 3.12.2](#scrollTo=l05-example-3-12-2) | Count the indicator |
| [Example 3.12.3](#scrollTo=l05-example-3-12-3) | Create several transparent indicators |
| [Example 3.12.4](#scrollTo=l05-example-3-12-4) | Inspect the rule against the original text |
| [Example 3.12.5](#scrollTo=l05-example-3-12-5) | Satisfaction by waiting mention |
| [Example 3.12.6](#scrollTo=l05-example-3-12-6) | Compare indicator counts across service types |
| [Example 3.12.7](#scrollTo=l05-example-3-12-7) | Cross-tabulate a code and category |
| [Example 3.12.8](#scrollTo=l05-example-3-12-8) | A transparent code is better than a vague label |
| [Example 3.12.12](#scrollTo=l05-example-3-12-12) | Reading matched and unmatched feedback |
| [Example 3.13.1](#scrollTo=l05-example-3-13-1) | Good provenance statement |
| [Example 3.13.2](#scrollTo=l05-example-3-13-2) | Good preliminary finding |


## Setup

Run this cell first. It loads the versioned raw CSV from GitHub and checks the expected 121 × 14 structure. Keep the raw data unchanged during Lecture 5.


In [1]:
import pandas as pd  # Loads the library feature used by this step.
data_url = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"  # Stores the calculated or supplied value for later use.
df = pd.read_csv(data_url)  # Stores the calculated or supplied value for later use.
print("Dataset shape:", df.shape)  # Displays the result so it can be inspected.
assert df.shape == (121, 14), "The wrong dataset version was loaded."  # Stores the calculated or supplied value for later use.
display(df.head())  # Displays the result so it can be inspected.


Dataset shape: (121, 14)
     record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                         feedback
0  SR2026-0001   2026-01-01  Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8  The guidance was clear, but the supporting-document requirements caused delays.
1  SR2026-0002   2026-01-01  Copenhagen         Transport             124             110             5.1                 3.9             92               32               10                    8         54.7               Several users asked for clearer information about service changes.
2  SR2026-0003   2026-01-01  Copenhagen        Employment             105              93             5.5

# Tutorial 3.1


## Example 3.1.1 — Why move beyond individual variables?

[Open Example 3.1.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.1/example-3.1.1)


In [2]:
city = "Copenhagen"
service_type = "Housing"
cases_received = 120
cases_resolved = 112


This is manageable. But imagine 5 cities, 8 service types and 24 months. Creating separate variable names for every combination would become difficult to maintain and analyse.

A table gives repeated observations a common structure:

| city | service_type | cases_received | cases_resolved |
|---|---|---:|---:|
| Copenhagen | Housing | 120 | 112 |
| Copenhagen | Transport | 85 | 90 |
| Aalborg | Housing | 95 | 89 |

Each row follows the same schema. That lets us ask questions across many observations rather than writing a separate calculation for each one.


## Example 3.1.2 — Identify the unit of observation

**Lecture slide:** 6. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.1.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.1/example-3.1.2)


Consider:

| student_id | lecture | attendance |
|---|---|---|
| S01 | L1 | Present |
| S01 | L2 | Present |
| S02 | L1 | Absent |

What does one row represent?

**Suggested answer:** one student's attendance status for one lecture.

It would be wrong to say that the table has three students merely because it has three rows. Student `S01` appears twice.



#### Course CSV observation

One row in the course CSV represents one service category in one city during one reporting month.

| report_month | city | service_type | cases_received |
|---|---|---|---:|
| 2026-01-01 | Copenhagen | Housing | 130 |

The row is a monthly service report. The value 130 counts cases within it. `cases_received` is the variable, and 130 is its value in this row. Several reports can describe one city. Therefore, 121 rows does not mean 121 citizens. This is synthetic teaching data.


## Example 3.1.3 — Variable versus value

[Open Example 3.1.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.1/example-3.1.3)


In this row:

```text
Copenhagen,Housing,120,112
```

- `city` is a **variable**;
- `Copenhagen` is one **value** of that variable;
- `cases_received` is a **variable**;
- `120` is one **value** of that variable.

A variable describes what kind of information a column contains. A value is one stored observation for that variable.


## Example 3.1.4 — A category is a modelling decision

[Open Example 3.1.4 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.1/example-3.1.4)


Suppose a column called `service_type` contains:

```text
Housing
Transport
Employment
```

These categories may be useful, but the dataset itself does not tell us:

- who designed the categories;
- whether all cases fit neatly into one category;
- whether another organisation would classify cases differently;
- whether categories changed over time.

The computational task begins with the stored categories, but critical interpretation asks how those categories came to exist.


# Tutorial 3.2


## Example 3.2.1 — Delimiters are not always commas

[Open Example 3.2.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.2/example-3.2.1)


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
pd.read_csv("file.csv", sep=";")
```


In [3]:
# pd.read_csv("file.csv", sep=";")  # Stores the calculated or supplied value for later use.
print("Reference cell: run the website example manually to observe FileNotFoundError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe FileNotFoundError.


Do not memorise `sep=";"` as a universal fix. First inspect what delimiter the file actually uses.


## Example 3.2.2 — Read a CSV mentally

**Lecture slide:** 7. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.2.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.2/example-3.2.2)


```csv
id,city,cases
1,Copenhagen,12
2,Aalborg,9
3,,7
```

Answer before coding:

1. How many columns are shown?
2. How many data rows are shown?
3. Which field is missing?

**Answer:** three columns, three data rows, and the `city` field is missing in row 3.



#### A course CSV excerpt

This excerpt contains three selected columns and the first two course records.

```csv
city,service_type,cases_received
Copenhagen,Housing,130
Copenhagen,Transport,124
```

Commas separate fields and the first line supplies the column names. Quotation marks keep a comma inside a feedback value in the same field. A blank field can mean missing information, while zero is a recorded numeric value.


## Example 3.2.3 — Detect a delimiter problem

[Open Example 3.2.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.2/example-3.2.3)


Suppose pandas displays one column named:

```text
city;service_type;cases_received
```

and each row also looks like one long text string.

A likely explanation is that the source file uses `;` but was read using the default comma separator.

This is a file-reading problem, not evidence that the dataset genuinely has one variable.


# Tutorial 3.3


## Example 3.3.1 — Import pandas

[Open Example 3.3.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.1)


In [4]:
import pandas as pd


### Line-by-line explanation

- `import` asks Python to load a library/module.
- `pandas` is the library name.
- `as pd` creates the conventional short alias `pd`.

We then write:


## Example 3.3.2 — Line-by-line explanation

[Open Example 3.3.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.2)


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
pd.read_csv(...)
```


In [5]:
# pd.read_csv(...)  # Runs this part of the documented analysis.
print("Reference cell: run the website example manually to observe ValueError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe ValueError.


instead of:


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
pandas.read_csv(...)
```


In [6]:
# pandas.read_csv(...)  # Runs this part of the documented analysis.
print("Reference cell: run the website example manually to observe NameError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe NameError.


The alias is a convention, not a requirement of the library.


## Example 3.3.3 — Confirm pandas is available

**Lecture slide:** 13. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.3.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.3)


In [7]:
import pandas as pd

print(pd.__version__)


2.2.3


### Why is `__version__` written with double underscores?

`pd` is the pandas module and the dot asks for something that belongs to that module. `__version__` is a special attribute maintained by pandas. It stores the version label for the installed pandas package, so `pd.__version__` may return text such as `"3.0.5"`.

The two underscores before and after `version` are part of the attribute's exact name. Python programmers often call this style a **dunder** name, meaning “double underscore”. Such names are commonly reserved for information or behaviour defined by Python or by a library. In this example we only read the attribute; we do not change it.

There are no parentheses after `__version__` because it is an **attribute containing a value**, not a function that must be called. Compare:

- `pd.__version__` reads a stored version label;
- `pd.read_csv(...)` calls a function and therefore uses parentheses.

**Expected output**

A pandas version number, for example:

```text
3.0.5
```

Your exact version may differ. The course examples are designed around standard pandas functionality and should not depend on one exact minor version.


## Example 3.3.4 — What is a DataFrame?

[Open Example 3.3.4 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.4)


In [8]:
import pandas as pd

data = {
    "city": ["Copenhagen", "Aalborg"],
    "cases_received": [120, 92]
}

df_small = pd.DataFrame(data)
df_small


         city  cases_received
0  Copenhagen             120
1     Aalborg              92


**Expected display**

```text
          city  cases_received
0   Copenhagen             120
1      Aalborg              92
```

The leftmost `0` and `1` are the DataFrame's **index labels**. They are not part of the original dictionary values.


## Example 3.3.5 — DataFrame versus Series

**Lecture slides:** 13, 18. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.3.5 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.5)


Column names are strings. Their spelling and capital letters must match.


In [9]:
city = df["city"]
small_table = df[["city", "cases_received"]]
print(type(city).__name__)
print(type(small_table).__name__)


Series
DataFrame


### Why add `.__name__` after `type(...)`?

`type(city)` returns the class object that describes what kind of Python object `city` is. Printing that class object directly gives a technical result such as `<class 'pandas.core.series.Series'>`. Adding `.__name__` asks the class object for only its short name, so the output becomes the easier-to-read word `Series`.

Read `type(city).__name__` from left to right:

1. `type(city)` finds the class of `city`;
2. the dot accesses information stored on that class;
3. `__name__` returns the class's short name.

The paired underscores are part of Python's special attribute name and must be typed exactly. There are no parentheses after `__name__` because the code is reading an attribute rather than calling a function.

**Expected output on the raw course CSV**

```text
Series
DataFrame
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | One pair of brackets selects a Series. |
| 2 | A list of names selects a DataFrame. |
| 3 | Show the type of the single column. |
| 4 | Show the type of the selected table. |

#### Additional tutorial explanation


In [10]:
print(type(df_small))
print(type(df_small["city"]))
print(type(df_small[["city"]]))


<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


**Expected idea**

- `df_small` is a `DataFrame`;
- `df_small["city"]` is a `Series`;
- `df_small[["city"]]` is a one-column `DataFrame`.

A `Series` is one-dimensional. A DataFrame is two-dimensional.


## Example 3.3.6 — The main course loading method: raw GitHub URL

**Lecture slides:** 12, 13. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.3.6 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.6)


The raw address supplies CSV text. The GitHub preview is a webpage.


In [11]:
import pandas as pd
url = (
    "https://raw.githubusercontent.com/asmrabbi/"
    "E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
)
df = pd.read_csv(url)
print(type(df).__name__)


DataFrame


Here `type(df)` identifies the object's class, while `.__name__` keeps only the short class name for display. Without `.__name__`, Python would print a longer technical representation such as `<class 'pandas.core.frame.DataFrame'>`. The double underscores belong to the special attribute's exact name, and there are no final parentheses because `__name__` is a stored attribute rather than a function call.

**Expected output on the raw course CSV**

```text
DataFrame
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Make pandas available as pd. |
| 2 | Begin the address of the raw file. |
| 3 | The address starts here. |
| 4 | Python joins these adjacent strings. |
| 5 | Finish storing the address. |
| 6 | Read the CSV and store the table in df. |
| 7 | Show the kind of object we loaded. |

### What `pd.read_csv()` does

Conceptually:

```text
CSV FILE / URL
      ↓
pd.read_csv(...)
      ↓
DataFrame stored in Python memory
```

The original file and the DataFrame are not the same object. Changing the DataFrame does not automatically rewrite the original CSV.

#### Additional tutorial explanation


In [12]:
import pandas as pd

url = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df = pd.read_csv(url)

df.head()


     record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                         feedback
0  SR2026-0001   2026-01-01  Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8  The guidance was clear, but the supporting-document requirements caused delays.
1  SR2026-0002   2026-01-01  Copenhagen         Transport             124             110             5.1                 3.9             92               32               10                    8         54.7               Several users asked for clearer information about service changes.
2  SR2026-0003   2026-01-01  Copenhagen        Employment             105              93             5.5                 3.9     

This is convenient in Colab because the dataset can be loaded directly without manually uploading it every session.



### Full class representation and short class name

Compare these two lines. `type(df)` returns the class object. Its `__name__` attribute gives the short name. The paired underscores are part of the exact attribute name.


In [13]:
print(type(df))
print(type(df).__name__)


<class 'pandas.core.frame.DataFrame'>
DataFrame


**Expected output**

```text
<class 'pandas.core.frame.DataFrame'>
DataFrame
```


## Example 3.3.7 — Load from a local path

[Open Example 3.3.7 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.7)


If the file is already available at the relative path:

```text
data/E26_TAN7_service_experience_raw.csv
```

use:


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
df = pd.read_csv("data/E26_TAN7_service_experience_raw.csv")
```


In [14]:
# df = pd.read_csv("data/E26_TAN7_service_experience_raw.csv")  # Stores the calculated or supplied value for later use.
print("Reference cell: run the website example manually to observe FileNotFoundError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe FileNotFoundError.


The path must be correct relative to the notebook's current working directory.


## Example 3.3.8 — Uploading a CSV in Google Colab

[Open Example 3.3.8 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.8)


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
df = pd.read_csv("E26_TAN7_service_experience_raw.csv")
```


In [15]:
# df = pd.read_csv("E26_TAN7_service_experience_raw.csv")  # Stores the calculated or supplied value for later use.
print("Reference cell: run the website example manually to observe FileNotFoundError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe FileNotFoundError.


A temporary Colab runtime may lose uploaded files when the runtime ends. This is one reason the direct repository URL is useful for course examples.

### Upload through Python


## Example 3.3.9 — Upload through Python

[Open Example 3.3.9 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.9)


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
from google.colab import files

uploaded = files.upload()
```


In [16]:
# from google.colab import files  # Loads the library feature used by this step.
#
# uploaded = files.upload()  # Stores the calculated or supplied value for later use.
print("Reference cell: run the website example manually to observe ModuleNotFoundError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe ModuleNotFoundError.


After selecting the file:


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
df = pd.read_csv("E26_TAN7_service_experience_raw.csv")
```


In [17]:
# df = pd.read_csv("E26_TAN7_service_experience_raw.csv")  # Stores the calculated or supplied value for later use.
print("Reference cell: run the website example manually to observe FileNotFoundError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe FileNotFoundError.


This `files` helper is specific to Google Colab. It is not required in ordinary Python or Jupyter environments.


## Example 3.3.10 — Wrong delimiter

[Open Example 3.3.10 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.10)


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
df = pd.read_csv("file.csv", sep=";")
```


In [18]:
# df = pd.read_csv("file.csv", sep=";")  # Stores the calculated or supplied value for later use.
print("Reference cell: run the website example manually to observe FileNotFoundError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe FileNotFoundError.


Use this only when `;` is genuinely the delimiter.

### Encoding error

An encoding error may require specifying an encoding, for example:


## Example 3.3.11 — Encoding error

[Open Example 3.3.11 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.11)


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
df = pd.read_csv("file.csv", encoding="utf-8")
```


In [19]:
# df = pd.read_csv("file.csv", encoding="utf-8")  # Stores the calculated or supplied value for later use.
print("Reference cell: run the website example manually to observe FileNotFoundError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe FileNotFoundError.


Do not randomly try encodings until something runs. First identify the source's documented encoding if possible.


## Example 3.3.12 — Methods versus attributes

[Open Example 3.3.12 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.12)


In [20]:
df.head()


     record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                         feedback
0  SR2026-0001   2026-01-01  Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8  The guidance was clear, but the supporting-document requirements caused delays.
1  SR2026-0002   2026-01-01  Copenhagen         Transport             124             110             5.1                 3.9             92               32               10                    8         54.7               Several users asked for clearer information about service changes.
2  SR2026-0003   2026-01-01  Copenhagen        Employment             105              93             5.5                 3.9     

An **attribute** provides information and does not normally use parentheses:


In [21]:
df.shape


(121, 14)


Writing `df.shape()` is a common beginner error because `shape` is not a method.



### The length method behind len()

Python also reserves double-underscore names for special behaviour. `__len__()` is the method behind the ordinary `len()` function. Use `len(df)` to count DataFrame rows. Python calls the object's length method for you. This method uses parentheses because it carries out an operation.


In [22]:
print(len(df))


121


On the unchanged course CSV, the output is `121`.


## Example 3.3.13 — Broken code

[Open Example 3.3.13 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.3/example-3.3.13)


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
import pandas as pd

df = pd.read_csv("E26_TAN7_service_experiences_raw.csv")
```


In [23]:
# import pandas as pd  # Loads the library feature used by this step.
#
# df = pd.read_csv("E26_TAN7_service_experiences_raw.csv")  # Stores the calculated or supplied value for later use.
print("Reference cell: run the website example manually to observe FileNotFoundError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe FileNotFoundError.


The filename is deliberately wrong: `experiences` should be `experience`.

1. Run the code.
2. Read the final line of the error message.
3. Identify the filename Python tried to open.
4. Repair the filename.
5. Rerun the cell.

This is ordinary debugging, not evidence that pandas is broken.


# Tutorial 3.4


## Example 3.4.1 — Start from a fresh load

[Open Example 3.4.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.1)


In [24]:
import pandas as pd

url = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df = pd.read_csv(url)


## Example 3.4.2 — head() — inspect the first rows

[Open Example 3.4.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.2)


In [25]:
df.head()


     record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                         feedback
0  SR2026-0001   2026-01-01  Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8  The guidance was clear, but the supporting-document requirements caused delays.
1  SR2026-0002   2026-01-01  Copenhagen         Transport             124             110             5.1                 3.9             92               32               10                    8         54.7               Several users asked for clearer information about service changes.
2  SR2026-0003   2026-01-01  Copenhagen        Employment             105              93             5.5                 3.9     

By default, `head()` shows the first five rows.


In [26]:
df.head(10)


     record_id report_month          city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                           feedback
0  SR2026-0001   2026-01-01    Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8    The guidance was clear, but the supporting-document requirements caused delays.
1  SR2026-0002   2026-01-01    Copenhagen         Transport             124             110             5.1                 3.9             92               32               10                    8         54.7                 Several users asked for clearer information about service changes.
2  SR2026-0003   2026-01-01    Copenhagen        Employment             105              93             5.5           

shows ten.

### What `head()` can tell you

- whether the expected columns appear;
- whether the values roughly resemble the expected data;
- whether column names loaded correctly;
- whether an obvious parsing problem occurred.

### What `head()` cannot tell you

It cannot prove that the first five rows are representative of the entire dataset.


## Example 3.4.3 — tail() — inspect the final rows

[Open Example 3.4.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.3)


In [27]:
df.tail()


       record_id report_month     city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                   feedback
116  SR2026-0117   2026-06-01  Aalborg         Transport              80              79             3.4                 4.2             56               24                6                    4         32.4   The digital form worked well, although some instructions were confusing.
117  SR2026-0118   2026-06-01  Aalborg        Employment              66              65             4.2                 4.2             42               24                6                    3         37.5                                                                        NaN
118  SR2026-0119   2026-06-01  Aalborg             Waste              71              70             2.3                 4.3             49            

This can reveal problems that do not appear at the beginning of a file.


## Example 3.4.4 — sample() — inspect rows from different positions

[Open Example 3.4.4 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.4)


In [28]:
df.sample(5, random_state=42)


      record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                               feedback
44  SR2026-0045   2026-03-01  Copenhagen  Citizen Services             185             174             2.6                 4.2            154               31               10                    6         56.2                   The online process was easy to use, although one step was confusing.
47  SR2026-0048   2026-03-01      Aarhus        Employment              96              90             4.4                 3.9             70               26               12                    5         55.1  The online information was helpful, but some users wanted more detailed instructions.
4   SR2026-0005   2026-01-01  Copenhagen  Citizen Services             166             152             3.1   

`sample(5)` chooses five rows. `random_state=42` makes the teaching example reproducible so that students running the same pandas version and data can usually see the same sampled row positions.

Do not use a random sample as proof that the dataset has no errors. It is an inspection aid.


## Example 3.4.5 — shape — how many rows and columns?

[Open Example 3.4.5 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.5)


In [29]:
df.shape


(121, 14)


**Expected output for the course dataset**

```text
(121, 14)
```

The first number is the row count. The second is the column count.

You can unpack the pair:


In [30]:
rows, columns = df.shape

print("Rows:", rows)
print("Columns:", columns)


Rows: 121
Columns: 14


**Expected output**

```text
Rows: 121
Columns: 14
```


## Example 3.4.6 — len(df) — another way to count rows

[Open Example 3.4.6 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.6)


In [31]:
len(df)


121


**Expected output**

```text
121
```

`len(df)` counts rows in this context. It does not report the number of columns.


## Example 3.4.7 — columns — inspect column names

[Open Example 3.4.7 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.7)


In [32]:
df.columns


Index(['record_id', 'report_month', 'city', 'service_type', 'cases_received',
       'cases_resolved', 'resolution_days', 'satisfaction_score',
       'digital_cases', 'in_person_cases', 'repeat_contacts',
       'complaints_received', 'staff_hours', 'feedback'],
      dtype='object')


You should see the fourteen column labels.

For a simple Python list:


In [33]:
print(df.columns.tolist())


['record_id', 'report_month', 'city', 'service_type', 'cases_received', 'cases_resolved', 'resolution_days', 'satisfaction_score', 'digital_cases', 'in_person_cases', 'repeat_contacts', 'complaints_received', 'staff_hours', 'feedback']


Expected labels:

```text
['record_id', 'report_month', 'city', 'service_type', 'cases_received', 'cases_resolved', 'resolution_days', 'satisfaction_score', 'digital_cases', 'in_person_cases', 'repeat_contacts', 'complaints_received', 'staff_hours', 'feedback']
```

Column names matter because later code must match them exactly.


## Example 3.4.8 — index — inspect row labels

[Open Example 3.4.8 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.8)


In [34]:
df.index


RangeIndex(start=0, stop=121, step=1)


For this freshly loaded dataset, pandas creates a default integer-like index starting at 0.

The index is not the same as `record_id`.

This distinction matters:

```text
DataFrame index: 0, 1, 2, 3, ...
record_id values: SR2026-0001, SR2026-0002, SR2026-0003, ...
```


## Example 3.4.9 — dtypes — how pandas currently represents each column

[Open Example 3.4.9 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.9)


In [35]:
df.dtypes


record_id               object
report_month            object
city                    object
service_type            object
cases_received           int64
cases_resolved           int64
resolution_days         object
satisfaction_score     float64
digital_cases            int64
in_person_cases          int64
repeat_contacts          int64
complaints_received      int64
staff_hours            float64
feedback                object


Numeric columns such as `cases_received` should be recognised as numeric. Text-like columns may appear as `object`, `str`, or a pandas string dtype depending on the pandas version and configuration.

Do not memorise one exact printed dtype name for text. Focus on the conceptual question:

> Did pandas recognise a column in a way that is usable for the operation we want to perform?

A particularly important column is `resolution_days`. It contains the word `unknown` in three records, so pandas cannot safely treat every value in that column as an ordinary number during a basic import.


## Example 3.4.10 — info() — compact structural inspection

[Open Example 3.4.10 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.10)


In [36]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   record_id            121 non-null    object 
 1   report_month         121 non-null    object 
 2   city                 121 non-null    object 
 3   service_type         121 non-null    object 
 4   cases_received       121 non-null    int64  
 5   cases_resolved       121 non-null    int64  
 6   resolution_days      121 non-null    object 
 7   satisfaction_score   117 non-null    float64
 8   digital_cases        121 non-null    int64  
 9   in_person_cases      121 non-null    int64  
 10  repeat_contacts      121 non-null    int64  
 11  complaints_received  121 non-null    int64  
 12  staff_hours          121 non-null    float64
 13  feedback             118 non-null    object 
dtypes: float64(2), int64(6), object(6)
memory usage: 13.4+ KB


`info()` reports:

- number of rows;
- column names;
- number of non-missing values in each column;
- technical dtypes;
- approximate memory usage.

You do not need to memorise the full display. Learn to read it.

For the course dataset, pay particular attention to:

- `satisfaction_score`, which has four missing values;
- `feedback`, which has three missing values;
- `resolution_days`, which is not straightforwardly numeric because of a non-numeric entry.


## Example 3.4.11 — A repeatable first-inspection routine

[Open Example 3.4.11 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.11)


In [37]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst rows:")
display(df.head())

print("\nData types:")
print(df.dtypes)

print("\nInfo:")
df.info()


Shape: (121, 14)

Columns:
['record_id', 'report_month', 'city', 'service_type', 'cases_received', 'cases_resolved', 'resolution_days', 'satisfaction_score', 'digital_cases', 'in_person_cases', 'repeat_contacts', 'complaints_received', 'staff_hours', 'feedback']

First rows:
     record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                         feedback
0  SR2026-0001   2026-01-01  Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8  The guidance was clear, but the supporting-document requirements caused delays.
1  SR2026-0002   2026-01-01  Copenhagen         Transport             124             110             5.1                 3.9             92    

This does not complete a data-quality assessment, but it prevents many careless mistakes.


## Example 3.4.12 — Interpret shape correctly

**Lecture slide:** 16. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.4.12 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.12)


shape is an attribute. head() is a method that runs an operation.


In [38]:
print(df.shape)
print(len(df))
print(df.columns[:4].tolist())


(121, 14)
121
['record_id', 'report_month', 'city', 'service_type']


**Expected output on the raw course CSV**

```text
(121, 14)
121
['record_id', 'report_month', 'city', 'service_type']
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Show the number of rows, then columns. |
| 2 | Count the rows. |
| 3 | Show the first four column names. |

#### Additional tutorial explanation


In [39]:
print(df.shape)


(121, 14)


Output:

```text
(121, 14)
```

Correct statement:

> The DataFrame currently contains 121 rows and 14 columns.

Incorrect statement:

> The dataset contains 121 citizens.

Why? Because the unit of observation is a service-category-city-month record, not a citizen.


## Example 3.4.13 — Compare `head()` and `sample()`

[Open Example 3.4.13 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.13)


In [40]:
print("First five rows")
display(df.head())

print("Random sample")
display(df.sample(5, random_state=42))


First five rows
     record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                         feedback
0  SR2026-0001   2026-01-01  Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8  The guidance was clear, but the supporting-document requirements caused delays.
1  SR2026-0002   2026-01-01  Copenhagen         Transport             124             110             5.1                 3.9             92               32               10                    8         54.7               Several users asked for clearer information about service changes.
2  SR2026-0003   2026-01-01  Copenhagen        Employment             105              93             5.5         

The purpose is not to calculate anything. It is to inspect more than one part of the table.


## Example 3.4.14 — Broken code

[Open Example 3.4.14 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.14)


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
print(df.shape())
```


In [41]:
# print(df.shape())  # Displays the result so it can be inspected.
print("Reference cell: run the website example manually to observe TypeError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe TypeError.


You may receive an error because `shape` is an attribute, not a callable method.

### Repair


## Example 3.4.15 — Repair

[Open Example 3.4.15 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.4/example-3.4.15)


In [42]:
print(df.shape)


(121, 14)


Use parentheses for methods such as `head()`, but not for `shape`.


# Tutorial 3.5


## Example 3.5.1 — Select one column

[Open Example 3.5.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.1)


In [43]:
city = df["city"]
city.head()


0    Copenhagen
1    Copenhagen
2    Copenhagen
3    Copenhagen
4    Copenhagen


`df["city"]` returns a pandas `Series`.

You can verify:


In [44]:
print(type(df["city"]))


<class 'pandas.core.series.Series'>


### Why the column name uses quotation marks


## Example 3.5.2 — Why the column name uses quotation marks

[Open Example 3.5.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.2)


In [45]:
df["city"]


0       Copenhagen
1       Copenhagen
2       Copenhagen
3       Copenhagen
4       Copenhagen
5           Aarhus
6      copenhagen 
7           Aarhus
8           Aarhus
9           Aarhus
10          Odense
11          Odense
12          Odense
13          Odense
14          Odense
15         Aalborg
16         Aalborg
17         Aalborg
18         Aalborg
19         Aalborg
[121 rows in full result. Run the cell to display all rows.]


uses the string `"city"` as a column label.

This is different from:


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
df[city]
```


In [46]:
# df[city]  # Runs this part of the documented analysis.
print("Reference cell: run the website example manually to observe KeyError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe KeyError.


which asks Python to find a variable called `city` and use its value as the key.

Unless you deliberately created such a variable, that code will fail.


## Example 3.5.3 — Select a numeric column

[Open Example 3.5.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.3)


In [47]:
cases = df["cases_received"]
print(cases.head())


0    130
1    124
2    105
3    104
4    166
Name: cases_received, dtype: int64


You now have a one-dimensional Series containing the values from that column.

A Series supports calculations such as:


In [48]:
print(cases.sum())


12653


We will study calculations systematically in Tutorial 3.7.


## Example 3.5.4 — Select several columns

[Open Example 3.5.4 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.4)


In [49]:
subset = df[["city", "service_type", "cases_received"]]
subset.head()


         city      service_type  cases_received
0  Copenhagen           Housing             130
1  Copenhagen         Transport             124
2  Copenhagen        Employment             105
3  Copenhagen             Waste             104
4  Copenhagen  Citizen Services             166


Notice the **double square brackets**:

```text
outer [ ... ]  → select from the DataFrame
inner [ ... ]  → Python list of column names
```


## Example 3.5.5 — Build a readable preview table

**Lecture slide:** 15. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.5.5 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.5)


The labels 0, 1 and 2 are the DataFrame index.


In [50]:
preview = df[["city", "service_type", "cases_received"]]
display(preview.head(3))


         city service_type  cases_received
0  Copenhagen      Housing             130
1  Copenhagen    Transport             124
2  Copenhagen   Employment             105


**Expected output on the raw course CSV**

```text
         city service_type  cases_received
0  Copenhagen      Housing             130
1  Copenhagen    Transport             124
2  Copenhagen   Employment             105
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Choose three columns for a compact table. |
| 2 | Show its first three rows. |

#### Additional tutorial explanation


In [51]:
columns_to_show = [
    "record_id",
    "city",
    "service_type",
    "cases_received",
    "cases_resolved"
]

preview = df[columns_to_show]
preview.head()


     record_id        city      service_type  cases_received  cases_resolved
0  SR2026-0001  Copenhagen           Housing             130             116
1  SR2026-0002  Copenhagen         Transport             124             110
2  SR2026-0003  Copenhagen        Employment             105              93
3  SR2026-0004  Copenhagen             Waste             104              94
4  SR2026-0005  Copenhagen  Citizen Services             166             152


Separating the list from the selection can make longer code easier to read.


## Example 3.5.6 — Selecting by label with .loc[]

**Lecture slide:** 19. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.5.6 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.6)


.loc includes the ending label, so 0:2 includes row 2.


In [52]:
columns = ["city", "cases_received"]
display(df.loc[0:2, columns])


         city  cases_received
0  Copenhagen             130
1  Copenhagen             124
2  Copenhagen             105


**Expected output on the raw course CSV**

```text
         city  cases_received
0  Copenhagen             130
1  Copenhagen             124
2  Copenhagen             105
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Choose the columns we want. |
| 2 | Show row labels 0 through 2 and those columns. |

### Important slicing detail

For label-based `.loc[]` slicing, the endpoint is normally included.

#### Additional tutorial explanation


In [53]:
df.loc[0]


record_id                                                    SR2026-0001
report_month                                                  2026-01-01
city                                                          Copenhagen
service_type                                                     Housing
cases_received                                                       130
cases_resolved                                                       116
resolution_days                                                      8.0
satisfaction_score                                                   3.5
digital_cases                                                         88
in_person_cases                                                       42
repeat_contacts                                                       17
complaints_received                                                   10
staff_hours                                                         87.8
feedback               The guidance was clear, but 

returns the row labelled `0`.

You can select rows and columns together:


In [54]:
df.loc[0:4, ["city", "service_type", "cases_received"]]


         city      service_type  cases_received
0  Copenhagen           Housing             130
1  Copenhagen         Transport             124
2  Copenhagen        Employment             105
3  Copenhagen             Waste             104
4  Copenhagen  Citizen Services             166


## Example 3.5.7 — Important slicing detail

[Open Example 3.5.7 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.7)


In [55]:
df.loc[0:4]


     record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                         feedback
0  SR2026-0001   2026-01-01  Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8  The guidance was clear, but the supporting-document requirements caused delays.
1  SR2026-0002   2026-01-01  Copenhagen         Transport             124             110             5.1                 3.9             92               32               10                    8         54.7               Several users asked for clearer information about service changes.
2  SR2026-0003   2026-01-01  Copenhagen        Employment             105              93             5.5                 3.9     

therefore includes labels `0`, `1`, `2`, `3` and `4` when those labels exist.


## Example 3.5.8 — Selecting by position with .iloc[]

**Lecture slide:** 41. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.5.8 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.8)


.iloc stops before 3. .loc includes label 2. These selections happen to match here.


In [56]:
print(df.loc[0:2, "city"].tolist())
print(df.iloc[0:3, 2].tolist())


['Copenhagen', 'Copenhagen', 'Copenhagen']
['Copenhagen', 'Copenhagen', 'Copenhagen']


**Expected output on the raw course CSV**

```text
['Copenhagen', 'Copenhagen', 'Copenhagen']
['Copenhagen', 'Copenhagen', 'Copenhagen']
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Select row labels 0 through 2 and the city column. |
| 2 | Select positions 0, 1, 2 and column position 2. |

### `.loc[]` versus `.iloc[]`

| Tool | Think in terms of | Example |
|---|---|---|
| `.loc[]` | labels/names | `df.loc[0:4, ["city", "cases_received"]]` |
| `.iloc[]` | integer positions | `df.iloc[0:5, 0:3]` |

A useful rule:

> Use `.loc[]` when your reasoning is about named labels or conditions. Use `.iloc[]` when your reasoning is explicitly about positions.

#### Additional tutorial explanation


In [57]:
df.iloc[0]


record_id                                                    SR2026-0001
report_month                                                  2026-01-01
city                                                          Copenhagen
service_type                                                     Housing
cases_received                                                       130
cases_resolved                                                       116
resolution_days                                                      8.0
satisfaction_score                                                   3.5
digital_cases                                                         88
in_person_cases                                                       42
repeat_contacts                                                       17
complaints_received                                                   10
staff_hours                                                         87.8
feedback               The guidance was clear, but 

returns the first row.


In [58]:
df.iloc[0:5]


     record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                         feedback
0  SR2026-0001   2026-01-01  Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8  The guidance was clear, but the supporting-document requirements caused delays.
1  SR2026-0002   2026-01-01  Copenhagen         Transport             124             110             5.1                 3.9             92               32               10                    8         54.7               Several users asked for clearer information about service changes.
2  SR2026-0003   2026-01-01  Copenhagen        Employment             105              93             5.5                 3.9     

returns the first five positions: 0 through 4.

You can select row and column positions together:


In [59]:
df.iloc[0:5, 0:4]


     record_id report_month        city      service_type
0  SR2026-0001   2026-01-01  Copenhagen           Housing
1  SR2026-0002   2026-01-01  Copenhagen         Transport
2  SR2026-0003   2026-01-01  Copenhagen        Employment
3  SR2026-0004   2026-01-01  Copenhagen             Waste
4  SR2026-0005   2026-01-01  Copenhagen  Citizen Services


This means:

- first five row positions;
- first four column positions.


## Example 3.5.9 — Boolean filtering

**Lecture slide:** 21. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.5.9 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.9)


Each True marks a row that passes the condition.


In [60]:
high = df["cases_received"] > 100
print(high.head(7))


0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: cases_received, dtype: bool


**Expected output on the raw course CSV**

```text
0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: cases_received, dtype: bool
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Compare every stored case count with 100. |
| 2 | Show the first seven True or False results. |

#### Additional tutorial explanation


In [61]:
df["cases_received"] > 100


0      True
1      True
2      True
3      True
4      True
5      True
6     False
7     False
8     False
9      True
10     True
11    False
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
[121 rows in full result. Run the cell to display all rows.]


This produces a Series of `True` and `False` values.

Then use that Boolean Series to keep the matching rows:


In [62]:
high_case_rows = df[df["cases_received"] > 100]
high_case_rows


      record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                            feedback
0   SR2026-0001   2026-01-01  Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8     The guidance was clear, but the supporting-document requirements caused delays.
1   SR2026-0002   2026-01-01  Copenhagen         Transport             124             110             5.1                 3.9             92               32               10                    8         54.7                  Several users asked for clearer information about service changes.
2   SR2026-0003   2026-01-01  Copenhagen        Employment             105              93             5.5            

## Example 3.5.10 — Filter by category

[Open Example 3.5.10 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.10)


In [63]:
housing = df[df["service_type"] == "Housing"]
housing


       record_id report_month        city service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                                     feedback
0    SR2026-0001   2026-01-01  Copenhagen      Housing             130             116             8.0                 3.5             88               42               17                   10         87.8              The guidance was clear, but the supporting-document requirements caused delays.
5    SR2026-0006   2026-01-01      Aarhus      Housing             111              96             7.5                 3.6             69               42               16                    8         72.0            Helpful staff explained the housing process, although the waiting time felt long.
15   SR2026-0016   2026-01-01     Aalborg      Housing              86              73             6.8 

This keeps rows where the stored value exactly matches `"Housing"`.

String matching is case-sensitive.


In [64]:
df[df["service_type"] == "housing"]


Empty DataFrame
Columns: [record_id, report_month, city, service_type, cases_received, cases_resolved, resolution_days, satisfaction_score, digital_cases, in_person_cases, repeat_contacts, complaints_received, staff_hours, feedback]
Index: []


will not match `"Housing"`.

Do not immediately lowercase the source data just to make a filter work. In Lecture 5, first inspect the stored categories. Category standardisation belongs mainly to Lecture 6.


## Example 3.5.11 — Combine conditions with &

**Lecture slide:** 23. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.5.11 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.11)


Use & between pandas conditions, with parentheses around each comparison.


In [65]:
mask = (
    (df["service_type"] == "Transport") &
    (df["cases_received"] > 90)
)
columns = ["city", "cases_received"]
display(df.loc[mask, columns].head(3))


            city  cases_received
1     Copenhagen             124
6    copenhagen               95
21    Copenhagen             126


**Expected output on the raw course CSV**

```text
            city  cases_received
1     Copenhagen             124
6    copenhagen               95
21    Copenhagen             126
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Begin a rule across the rows. |
| 2 | The exact label must be Transport, and... |
| 3 | ...the stored case count must exceed 90. |
| 4 | Finish the combined rule. |
| 5 | Choose the columns to show. |
| 6 | Preview the matching records. |

### Why the parentheses matter

With pandas Boolean conditions, write each comparison inside parentheses:

#### Additional tutorial explanation


In [66]:
result = df[
    (df["city"] == "Copenhagen") &
    (df["cases_received"] > 100)
]

result


      record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                            feedback
0   SR2026-0001   2026-01-01  Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8     The guidance was clear, but the supporting-document requirements caused delays.
1   SR2026-0002   2026-01-01  Copenhagen         Transport             124             110             5.1                 3.9             92               32               10                    8         54.7                  Several users asked for clearer information about service changes.
2   SR2026-0003   2026-01-01  Copenhagen        Employment             105              93             5.5            

## Example 3.5.12 — Why the parentheses matter

[Open Example 3.5.12 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.12)


In [67]:
(df["city"] == "Copenhagen")


0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
[121 rows in full result. Run the cell to display all rows.]


and combine them with `&`.

Do not write:


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
(df["city"] == "Copenhagen") and (df["cases_received"] > 100)
```


In [68]:
# (df["city"] == "Copenhagen") and (df["cases_received"] > 100)  # Stores the calculated or supplied value for later use.
print("Reference cell: run the website example manually to observe ValueError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe ValueError.


Python's ordinary `and` operator does not work element-by-element across a pandas Series in the way required here.


## Example 3.5.13 — Combine alternatives with |

[Open Example 3.5.13 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.13)


In [69]:
result = df[
    (df["service_type"] == "Housing") |
    (df["service_type"] == "Transport")
]


`|` is the element-wise OR operator in this pandas context.


## Example 3.5.14 — Use .isin() for several allowed categories

[Open Example 3.5.14 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.14)


In [70]:
result = df[
    df["service_type"].isin(["Housing", "Transport"])
]


Read it as:

> Keep rows where `service_type` is in this list of allowed values.

This often becomes easier to read when the list contains several categories.


## Example 3.5.15 — Filter and then choose columns

**Lecture slide:** 22. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.5.15 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.15)


head(3) limits the display. It does not change the 62 matching rows.


In [71]:
high = df["cases_received"] > 100
selected = df.loc[high, ["city", "cases_received"]]
print("Matching rows:", len(selected))
display(selected.head(3))


Matching rows: 62
         city  cases_received
0  Copenhagen             130
1  Copenhagen             124
2  Copenhagen             105


**Expected output on the raw course CSV**

```text
Matching rows: 62
         city  cases_received
0  Copenhagen             130
1  Copenhagen             124
2  Copenhagen             105
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Create the True or False rule. |
| 2 | Keep matching rows and two columns. |
| 3 | Count all matches, before the preview. |
| 4 | Display the first three matches. |

#### Additional tutorial explanation


In [72]:
result = df.loc[
    df["cases_received"] > 100,
    ["record_id", "city", "service_type", "cases_received"]
]

result


      record_id        city      service_type  cases_received
0   SR2026-0001  Copenhagen           Housing             130
1   SR2026-0002  Copenhagen         Transport             124
2   SR2026-0003  Copenhagen        Employment             105
3   SR2026-0004  Copenhagen             Waste             104
4   SR2026-0005  Copenhagen  Citizen Services             166
5   SR2026-0006      Aarhus           Housing             111
9   SR2026-0010      Aarhus  Citizen Services             123
10  SR2026-0011      Odense        Transport              107
14  SR2026-0015      Odense  Citizen Services             110
20  SR2026-0021  Copenhagen           Housing             157
21  SR2026-0022  Copenhagen         Transport             126
22  SR2026-0023  Copenhagen        Employment             120
23  SR2026-0024  Copenhagen             Waste             112
24  SR2026-0025  Copenhagen  Citizen Services             161
25  SR2026-0026      Aarhus           Housing             136
26  SR20

This combines a row condition with named column selection.

The structure is:

```text
df.loc[row_condition, columns_to_return]
```


## Example 3.5.16 — Filtering is an analytical decision

[Open Example 3.5.16 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.16)


In [73]:
copenhagen = df[df["city"] == "Copenhagen"]


you are not merely using syntax. You are deciding that only rows exactly labelled `Copenhagen` belong to this subset.

But the raw course data also contains:

```text
 copenhagen 
Koebenhavn
```

Should those count as Copenhagen?

That is a cleaning/classification question. Lecture 5 should reveal the problem; Lecture 6 will make and document the transformation decision.


## Example 3.5.17 — Broken code 1

[Open Example 3.5.17 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.17)


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
df["City"]
```


In [74]:
# df["City"]  # Runs this part of the documented analysis.
print("Reference cell: run the website example manually to observe KeyError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe KeyError.


The actual column is `city` with a lowercase `c`.

Likely result:

```text
KeyError: 'City'
```

### Repair


## Example 3.5.18 — Repair

[Open Example 3.5.18 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.18)


In [75]:
df["city"]


0       Copenhagen
1       Copenhagen
2       Copenhagen
3       Copenhagen
4       Copenhagen
5           Aarhus
6      copenhagen 
7           Aarhus
8           Aarhus
9           Aarhus
10          Odense
11          Odense
12          Odense
13          Odense
14          Odense
15         Aalborg
16         Aalborg
17         Aalborg
18         Aalborg
19         Aalborg
[121 rows in full result. Run the cell to display all rows.]


### Broken code 2


## Example 3.5.19 — Broken code 2

[Open Example 3.5.19 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.19)


This is a deliberate debugging or syntax reference from the tutorial. Read the exact code below and run it manually when asked. The following safe cell lets Run all continue.

```python
df[(df["city"] == "Copenhagen") and (df["cases_received"] > 100)]
```


In [76]:
# df[(df["city"] == "Copenhagen") and (df["cases_received"] > 100)]  # Stores the calculated or supplied value for later use.
print("Reference cell: run the website example manually to observe ValueError.")  # Explains why Run all continues safely.


Reference cell: run the website example manually to observe ValueError.


### Repair


## Example 3.5.20 — Repair

[Open Example 3.5.20 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.5/example-3.5.20)


In [77]:
df[
    (df["city"] == "Copenhagen") &
    (df["cases_received"] > 100)
]


      record_id report_month        city      service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                            feedback
0   SR2026-0001   2026-01-01  Copenhagen           Housing             130             116             8.0                 3.5             88               42               17                   10         87.8     The guidance was clear, but the supporting-document requirements caused delays.
1   SR2026-0002   2026-01-01  Copenhagen         Transport             124             110             5.1                 3.9             92               32               10                    8         54.7                  Several users asked for clearer information about service changes.
2   SR2026-0003   2026-01-01  Copenhagen        Employment             105              93             5.5            

# Tutorial 3.6


## Example 3.6.1 — Inspect pandas dtypes

**Lecture slide:** 17. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.6.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.6/example-3.6.1)


resolution_days includes "unknown". A numeric intention needs valid numeric values.


In [78]:
columns = ["cases_received", "resolution_days"]
print(df[columns].dtypes)


cases_received      int64
resolution_days    object
dtype: object


**Expected output on the raw course CSV**

```text
cases_received      int64
resolution_days    object
dtype: object
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Name the two columns to inspect. |
| 2 | Show how pandas currently stores each one. |

#### Additional tutorial explanation


In [79]:
print(df.dtypes)


record_id               object
report_month            object
city                    object
service_type            object
cases_received           int64
cases_resolved           int64
resolution_days         object
satisfaction_score     float64
digital_cases            int64
in_person_cases          int64
repeat_contacts          int64
complaints_received      int64
staff_hours            float64
feedback                object
dtype: object


Do not read this as a complete data dictionary. It reports pandas' technical representation.

A robust interpretation might say:

> `cases_received` and `cases_resolved` are technically numeric and conceptually counts; `record_id` is technically integer-like but conceptually an identifier; `resolution_days` is conceptually numeric but its raw stored values include non-numeric text; `report_month` is conceptually date-like but may initially be loaded as text.

That is much more informative than simply copying the dtype list.


## Example 3.6.2 — Build a conceptual type table

[Open Example 3.6.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.6/example-3.6.2)


In [80]:
conceptual_types = {
    "record_id": "identifier",
    "report_month": "date-like",
    "city": "categorical",
    "service_type": "categorical",
    "cases_received": "numeric count",
    "cases_resolved": "numeric count",
    "resolution_days": "numeric measure",
    "satisfaction_score": "numeric rating",
    "digital_cases": "numeric count",
    "in_person_cases": "numeric count",
    "repeat_contacts": "numeric count",
    "complaints_received": "numeric count",
    "staff_hours": "numeric measure",
    "feedback": "free text"
}

for column, role in conceptual_types.items():
    print(column, "->", role)


record_id -> identifier
report_month -> date-like
city -> categorical
service_type -> categorical
cases_received -> numeric count
cases_resolved -> numeric count
resolution_days -> numeric measure
satisfaction_score -> numeric rating
digital_cases -> numeric count
in_person_cases -> numeric count
repeat_contacts -> numeric count
complaints_received -> numeric count
staff_hours -> numeric measure
feedback -> free text


The dictionary does not change the DataFrame. It documents your interpretation of each variable's role.


## Example 3.6.3 — Compare technical and conceptual types

[Open Example 3.6.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.6/example-3.6.3)


In [81]:
for column in df.columns:
    print(column, "| pandas dtype:", df[column].dtype)


record_id | pandas dtype: object
report_month | pandas dtype: object
city | pandas dtype: object
service_type | pandas dtype: object
cases_received | pandas dtype: int64
cases_resolved | pandas dtype: int64
resolution_days | pandas dtype: object
satisfaction_score | pandas dtype: float64
digital_cases | pandas dtype: int64
in_person_cases | pandas dtype: int64
repeat_contacts | pandas dtype: int64
complaints_received | pandas dtype: int64
staff_hours | pandas dtype: float64
feedback | pandas dtype: object


Then compare the printed dtype with the conceptual role table.

Question:

> Which columns are most likely to require conversion before later analysis?

A strong answer should mention at least `report_month` and `resolution_days`, while explaining why.


# Tutorial 3.7


## Example 3.7.1 — count() — count non-missing values

[Open Example 3.7.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.1)


In [82]:
df["cases_received"].count()


121


**Expected output**

```text
121
```

For `feedback`:


In [83]:
df["feedback"].count()


118


**Expected output**

```text
118
```

Why 118 instead of 121? Three feedback values are missing.

### `count()` versus `len()`


## Example 3.7.2 — count() versus len()

[Open Example 3.7.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.2)


In [84]:
print("Rows:", len(df))
print("Non-missing feedback values:", df["feedback"].count())


Rows: 121
Non-missing feedback values: 118


Expected:

```text
Rows: 121
Non-missing feedback values: 118
```

This distinction becomes important when calculating percentages.


## Example 3.7.3 — sum() — total a numeric column

[Open Example 3.7.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.3)


In [85]:
total_cases_received = df["cases_received"].sum()
print(total_cases_received)


12653


**Expected output on the raw teaching dataset**

```text
12653
```

Do not immediately interpret this as a trustworthy real-world total. The raw column contains a negative value that will be investigated later.

That gives us an important lesson:

> pandas can calculate correctly from values that are substantively wrong.


## Example 3.7.4 — mean() — arithmetic average

[Open Example 3.7.4 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.4)


In [86]:
mean_cases = df["cases_received"].mean()
print(mean_cases)


104.5702479338843


**Expected output**

```text
104.570248
```

The mean is:

```text
sum of values / number of included values
```

A mean can be sensitive to extreme or invalid observations.


## Example 3.7.5 — median() — middle value

[Open Example 3.7.5 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.5)


In [87]:
median_cases = df["cases_received"].median()
print(median_cases)


102.0


**Expected output**

```text
102.0
```

The median is the middle value after sorting the observations. With an even number of observations, pandas uses the average of the two middle values.

### Mean versus median

The raw course data gives:

```text
Mean:   104.570248
Median: 102.0
```

They are not identical because they answer different questions and respond differently to the distribution of values.

Do not automatically choose one. Ask what summary is appropriate and whether the underlying values are valid.


## Example 3.7.6 — min() and max()

[Open Example 3.7.6 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.6)


In [88]:
print("Minimum:", df["cases_received"].min())
print("Maximum:", df["cases_received"].max())


Minimum: -4
Maximum: 185


**Expected output**

```text
Minimum: -4
Maximum: 185
```

The minimum immediately raises a quality question:

> Can a number of received cases legitimately be negative?

A descriptive calculation has therefore helped us discover a potential data problem.


## Example 3.7.7 — std() — standard deviation

[Open Example 3.7.7 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.7)


In [89]:
std_cases = df["cases_received"].std()
print(round(std_cases, 2))


27.26


**Expected output**

```text
27.26
```

At this level, interpret standard deviation as an indicator of spread around the mean. A larger standard deviation generally indicates that values are more dispersed.

You are **not** required to calculate the standard-deviation formula by hand in this course.


## Example 3.7.8 — describe() — several summaries together

**Lecture slide:** 42. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.7.8 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.8)


50% is the median. The negative minimum is a reason to inspect the source.


In [90]:
display(df["cases_received"].describe().round(2))


count    121.00
mean     104.57
std       27.26
min       -4.00
25%       86.00
50%      102.00
75%      122.00
max      185.00


**Expected output on the raw course CSV**

```text
count    121.00
mean     104.57
std       27.26
min       -4.00
25%       86.00
50%      102.00
75%      122.00
max      185.00
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Calculate and display a standard descriptive summary. |

### How to read the output

- `count`: non-missing observations included;
- `mean`: arithmetic average;
- `std`: standard deviation;
- `min`: smallest observed value;
- `25%`: first quartile;
- `50%`: median;
- `75%`: third quartile;
- `max`: largest observed value.

The quartiles divide the ordered observations into parts. You do not need advanced distribution theory here; you should simply recognise that they provide more information than one average.

#### Additional tutorial explanation


In [91]:
df["cases_received"].describe()


count    121.000000
mean     104.570248
std       27.256750
min       -4.000000
25%       86.000000
50%      102.000000
75%      122.000000
max      185.000000


Expected values are approximately:

```text
count    121.000000
mean     104.570248
std       27.256750
min       -4.000000
25%       86.000000
50%      102.000000
75%      122.000000
max      185.000000
```


## Example 3.7.9 — round() for readable output

[Open Example 3.7.9 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.9)


In [92]:
mean_cases = df["cases_received"].mean()
print("Mean cases:", round(mean_cases, 2))


Mean cases: 104.57


Output:

```text
Mean cases: 104.57
```

Rounding changes how a value is displayed or stored after rounding. It does not improve the quality of the underlying data.


## Example 3.7.10 — Received and resolved totals

[Open Example 3.7.10 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.10)


In [93]:
total_received = df["cases_received"].sum()
total_resolved = df["cases_resolved"].sum()

print("Cases received:", total_received)
print("Cases resolved:", total_resolved)


Cases received: 12653
Cases resolved: 11958


**Expected output**

```text
Cases received: 12653
Cases resolved: 11958
```

This immediately invites a derived calculation, which we will formalise in Tutorial 3.8.


## Example 3.7.11 — Find the row associated with an extreme value

[Open Example 3.7.11 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.11)


In [94]:
max_index = df["cases_received"].idxmax()
df.loc[max_index]


record_id                                                    SR2026-0045
report_month                                                  2026-03-01
city                                                          Copenhagen
service_type                                            Citizen Services
cases_received                                                       185
cases_resolved                                                       174
resolution_days                                                      2.6
satisfaction_score                                                   4.2
digital_cases                                                        154
in_person_cases                                                       31
repeat_contacts                                                       10
complaints_received                                                    6
staff_hours                                                         56.2
feedback               The online process was easy 

`idxmax()` returns the index label of the first maximum value.

Likewise:


In [95]:
min_index = df["cases_received"].idxmin()
df.loc[min_index]


record_id                                                    SR2026-0054
report_month                                                  2026-03-01
city                                                              Odense
service_type                                                       Waste
cases_received                                                        -4
cases_resolved                                                         0
resolution_days                                                      3.0
satisfaction_score                                                   4.1
digital_cases                                                          0
in_person_cases                                                        0
repeat_contacts                                                        0
complaints_received                                                    0
staff_hours                                                         29.7
feedback               Helpful guidance, but some u

This is especially useful when a minimum or maximum looks suspicious.


## Example 3.7.12 — Inspect the negative minimum

[Open Example 3.7.12 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.12)


In [96]:
min_index = df["cases_received"].idxmin()

print("Minimum row index:", min_index)
display(df.loc[[min_index]])


Minimum row index: 53
      record_id report_month    city service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                      feedback
53  SR2026-0054   2026-03-01  Odense        Waste              -4               0             3.0                 4.1              0                0                0                    0         29.7  Helpful guidance, but some users reported delayed follow-up.


The point is not to delete the record. The point is to connect a statistical signal to the underlying row.


## Example 3.7.13 — Missing values and numerical calculations

[Open Example 3.7.13 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.13)


In [97]:
df["satisfaction_score"].mean()


4.112820512820512


uses the available non-missing scores.

This is convenient, but it creates an interpretive responsibility:

> When you report an average, know how many observations actually contributed to it.

Check:


In [98]:
print("Rows:", len(df))
print("Available satisfaction scores:", df["satisfaction_score"].count())


Rows: 121
Available satisfaction scores: 117


Expected:

```text
Rows: 121
Available satisfaction scores: 117
```


## Example 3.7.14 — Preliminary satisfaction mean

**Lecture slide:** 26. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.7.14 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.14)


Four scores are missing. Two other scores fall outside the expected range 1 to 5.


In [99]:
scores = df["satisfaction_score"]
print("Rows:", len(df))
print("Recorded scores:", scores.count())
print("Raw mean:", round(scores.mean(), 2))


Rows: 121
Recorded scores: 117
Raw mean: 4.11


**Expected output on the raw course CSV**

```text
Rows: 121
Recorded scores: 117
Raw mean: 4.11
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Select the satisfaction scores. |
| 2 | Count all rows in the table. |
| 3 | Count only non-missing scores. |
| 4 | Average the available stored scores. |

#### Additional tutorial explanation


In [100]:
mean_satisfaction = df["satisfaction_score"].mean()
print(round(mean_satisfaction, 2))


4.11


**Expected raw-data result**

```text
4.11
```

But the teaching schema says the expected range is 1–5, and the raw data contains two out-of-range values. Therefore:

> **4.11 is a technically correct mean of the currently stored non-missing values, but it should not yet be treated as a validated analytical result.**

This distinction is central to the course.


## Example 3.7.18 — A numerical summary

**Lecture slide:** 25. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.7.18 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.7/example-3.7.18)


The minimum is -4. These raw summaries still need investigation.


In [101]:
cases = df["cases_received"]
print("Total:", cases.sum())
print("Mean:", round(cases.mean(), 2))
print("Median:", cases.median())
print("Minimum:", cases.min())


Total: 12653
Mean: 104.57
Median: 102.0
Minimum: -4


**Expected output on the raw course CSV**

```text
Total: 12653
Mean: 104.57
Median: 102.0
Minimum: -4
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Select the received-case counts. |
| 2 | Add the stored counts across all rows. |
| 3 | Calculate the arithmetic average. |
| 4 | Find the middle value after ordering. |
| 5 | Find the smallest stored count. |

#### Additional tutorial explanation

A researcher wants a first summary of the received-case counts. Calculate the stored total, average, middle value and minimum. Keep the result preliminary while the negative count and duplicate are unresolved.


# Tutorial 3.8


## Example 3.8.1 — Column arithmetic

[Open Example 3.8.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.8/example-3.8.1)


In [102]:
cases_received = 120
cases_resolved = 112
unresolved_cases = cases_received - cases_resolved


With pandas, the same logic can be applied to every row:


In [103]:
df["unresolved_cases"] = (
    df["cases_received"] - df["cases_resolved"]
)


The new column is calculated row by row.


## Example 3.8.2 — Inspect the derived column

**Lecture slide:** 27. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.8.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.8/example-3.8.2)


For row 0, 130 - 116 = 14. The original source columns stay available.


In [104]:
df["case_gap"] = df["cases_received"] - df["cases_resolved"]
columns = ["cases_received", "cases_resolved", "case_gap"]
display(df[columns].head(3))


   cases_received  cases_resolved  case_gap
0             130             116        14
1             124             110        14
2             105              93        12


**Expected output on the raw course CSV**

```text
   cases_received  cases_resolved  case_gap
0             130             116        14
1             124             110        14
2             105              93        12
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Subtract resolved cases from received cases in each row. |
| 2 | Keep the source values beside the new result. |
| 3 | Show the first three calculations. |

#### Additional tutorial explanation


In [105]:
df["unresolved_cases"] = (
    df["cases_received"] - df["cases_resolved"]
)

display(
    df[[
        "record_id",
        "cases_received",
        "cases_resolved",
        "unresolved_cases"
    ]].head(8)
)


     record_id  cases_received  cases_resolved  unresolved_cases
0  SR2026-0001             130             116                14
1  SR2026-0002             124             110                14
2  SR2026-0003             105              93                12
3  SR2026-0004             104              94                10
4  SR2026-0005             166             152                14
5  SR2026-0006             111              96                15
6  SR2026-0007              95              88                 7
7  SR2026-0008              87              80                 7


A negative derived value should immediately trigger inspection.

For example, if `cases_resolved` is greater than `cases_received`, `unresolved_cases` becomes negative.

The formula is behaving correctly. The relationship between the source values may be questionable.


## Example 3.8.3 — Create a row-level resolution rate

[Open Example 3.8.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.8/example-3.8.3)


In [106]:
df["resolution_rate"] = (
    df["cases_resolved"] /
    df["cases_received"] * 100
)


## Example 3.8.4 — Inspect the rate

**Lecture slide:** 28. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.8.4 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.8/example-3.8.4)


108.75% follows from the stored values. The reporting rule needs checking.


In [107]:
df["resolution_rate"] = (
    df["cases_resolved"] / df["cases_received"] * 100
)
columns = ["cases_received", "cases_resolved", "resolution_rate"]
display(df.loc[[0, 11], columns].round(2))


    cases_received  cases_resolved  resolution_rate
0              130             116            89.23
11              80              87           108.75


**Expected output on the raw course CSV**

```text
    cases_received  cases_resolved  resolution_rate
0              130             116            89.23
11              80              87           108.75
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Name the new percentage column. |
| 2 | Calculate resolved / received × 100. |
| 3 | Finish the calculation for every row. |
| 4 | Choose the inputs and the new measure. |
| 5 | Show two reports, rounded for display. |

#### Additional tutorial explanation


In [108]:
display(
    df[[
        "record_id",
        "cases_received",
        "cases_resolved",
        "resolution_rate"
    ]]
)


      record_id  cases_received  cases_resolved  resolution_rate
0   SR2026-0001             130             116        89.230769
1   SR2026-0002             124             110        88.709677
2   SR2026-0003             105              93        88.571429
3   SR2026-0004             104              94        90.384615
4   SR2026-0005             166             152        91.566265
5   SR2026-0006             111              96        86.486486
6   SR2026-0007              95              88        92.631579
7   SR2026-0008              87              80        91.954023
8   SR2026-0009              97              89        91.752577
9   SR2026-0010             123             113        91.869919
10  SR2026-0011             107              92        85.981308
11  SR2026-0012              80              87       108.750000
12  SR2026-0013              69              63        91.304348
13  SR2026-0014              82              73        89.024390
14  SR2026-0015          

You should notice at least three conceptual problems:

1. three rows exceed 100% because resolved cases exceed received cases;
2. one row has a negative `cases_received` value, so its calculated rate is not substantively meaningful;
3. a future or revised file could contain a zero denominator, so the rule for zero received cases must still be documented.

pandas may represent `0 / 0` as `NaN` rather than raising the same error you might see with ordinary scalar Python division. The supplied raw file does not currently contain a zero `cases_received` value, but code should still anticipate that boundary.

The important question is not merely “How do I suppress an unusual output?” It is:

> **What should the rate mean for invalid or zero received counts, and what does the data documentation say?**


## Example 3.8.5 — Method A — calculate each row's percentage, then average the percentages

[Open Example 3.8.5 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.8/example-3.8.5)


In [109]:
mean_row_rate = df["resolution_rate"].mean()
print(round(mean_row_rate, 2))


93.66


On the raw teaching data this produces a preliminary value around:

```text
93.66
```

### Method B — divide total resolved by total received


## Example 3.8.6 — Method B — divide total resolved by total received

**Lecture slide:** 43. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.8.6 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.8/example-3.8.6)


Different denominators answer different questions. Both still use unvalidated raw values.


In [110]:
row_average = df["resolution_rate"].mean()
overall = df["cases_resolved"].sum() / df["cases_received"].sum() * 100
print("Average of row rates:", round(row_average, 2))
print("Ratio of totals:", round(overall, 2))


Average of row rates: 93.66
Ratio of totals: 94.51


**Expected output on the raw course CSV**

```text
Average of row rates: 93.66
Ratio of totals: 94.51
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Give every report percentage equal weight. |
| 2 | Divide the total resolved count by the total received count. |
| 3 | Display the average report percentage. |
| 4 | Display the percentage based on all stored counts. |

#### Additional tutorial explanation


In [111]:
overall_rate = (
    df["cases_resolved"].sum() /
    df["cases_received"].sum() * 100
)

print(round(overall_rate, 2))


94.51


On the raw teaching data:

```text
94.51
```

These are **not the same measure**.

Why?

Method A gives every row equal weight, regardless of whether it contains 5 cases or 500 cases. Method B effectively weights rows by the number of cases received.

This is a crucial analytical lesson:

> **Two reasonable-looking formulas can answer different questions. Always define the measure before reporting it.**

The raw dataset also contains quality problems, so neither result should yet be treated as final evidence.


## Example 3.8.7 — Percentage of rows with missing feedback

[Open Example 3.8.7 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.8/example-3.8.7)


In [112]:
df["feedback"].isna()


0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
[121 rows in full result. Run the cell to display all rows.]


`True` behaves like 1 and `False` like 0 in many pandas aggregations, so:


In [113]:
missing_feedback = df["feedback"].isna().sum()
total_rows = len(df)

missing_feedback_pct = missing_feedback / total_rows * 100

print("Missing feedback rows:", missing_feedback)
print("Missing feedback percentage:", round(missing_feedback_pct, 2))


Missing feedback rows: 3
Missing feedback percentage: 2.48


**Expected output**

```text
Missing feedback rows: 1
Missing feedback percentage: 6.25
```

This percentage uses **all rows** as the denominator.

If you used another denominator, you would be answering another question.


## Example 3.8.8 — Percentage of rows belonging to a category

**Lecture slide:** 30. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.8.8 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.8/example-3.8.8)


17.36% of raw report rows carry the exact label Housing.


In [114]:
housing_rows = (df["service_type"] == "Housing").sum()
housing_pct = housing_rows / len(df) * 100
print("Housing rows:", housing_rows)
print("Percentage of rows:", round(housing_pct, 2))


Housing rows: 21
Percentage of rows: 17.36


**Expected output on the raw course CSV**

```text
Housing rows: 21
Percentage of rows: 17.36
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Count True results for the exact Housing label. |
| 2 | Divide by all 121 rows and multiply by 100. |
| 3 | Display the numerator. |
| 4 | Display the percentage, rounded for reading. |

#### Additional tutorial explanation


In [115]:
housing_rows = (df["service_type"] == "Housing").sum()
housing_pct = housing_rows / len(df) * 100

print("Housing rows:", housing_rows)
print("Housing percentage:", round(housing_pct, 2))


Housing rows: 21
Housing percentage: 17.36


Expected:

```text
Housing rows: 21
Housing percentage: 17.36
```

This means 17.36% of **rows in this raw teaching table** are labelled exactly `Housing`. It does not mean that 17.36% of citizens use Housing services.

The unit of observation determines the meaning of the percentage.


## Example 3.8.9 — Create a clearly named percentage

[Open Example 3.8.9 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.8/example-3.8.9)


In [116]:
df["resolved_pct_of_received"] = (
    df["cases_resolved"] /
    df["cases_received"] * 100
)


The longer name is more informative than simply `rate` because it states the numerator and denominator relationship.


# Tutorial 3.9


## Example 3.9.1 — Inspect unique values before counting them

[Open Example 3.9.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.1)


In [117]:
print(df["service_type"].unique())


['Housing' 'Transport' 'Employment' 'Waste' 'Citizen Services'
 'Transport ' 'Citizen services' 'WASTE' 'Employment Services']


Expected raw labels:

```text
['Housing' 'Transport' 'Employment' 'Waste' 'Citizen Services'
 'Transport ' 'Citizen services' 'WASTE' 'Employment Services']
```

For `city`:


In [118]:
print(df["city"].unique())


['Copenhagen' 'Aarhus' ' copenhagen ' 'Odense' 'Aalborg' 'AALBORG'
 'Odense ' 'aarhus' 'Koebenhavn']


The raw values include several inconsistent forms, for example:

```text
Copenhagen
 copenhagen 
AALBORG
Koebenhavn
Aalborg
```

This is why `unique()` is useful before group analysis.

If categories that should be equivalent are split across spellings, the group results will also be split.


## Example 3.9.2 — Count distinct values with nunique()

[Open Example 3.9.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.2)


In [119]:
df["service_type"].nunique()


9


**Expected output**

```text
9
```

The value is nine because four inconsistent one-row labels are stored separately from the five intended service categories. For the raw `city` column, `nunique()` counts the stored strings as distinct. That number therefore reflects data consistency as well as conceptual categories.


## Example 3.9.3 — Frequency table with value_counts()

**Lecture slide:** 29. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.9.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.3)


"Transport" and "Transport " count as separate labels.


In [120]:
counts = df["service_type"].value_counts()
display(counts)


service_type
Transport              24
Employment             24
Waste                  24
Citizen Services       24
Housing                21
Transport               1
Citizen services        1
WASTE                   1
Employment Services     1


**Expected output on the raw course CSV**

```text
service_type
Transport              24
Employment             24
Waste                  24
Citizen Services       24
Housing                21
Transport               1
Citizen services        1
WASTE                   1
Employment Services     1
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Count rows for each exact service label. |
| 2 | Display the frequency table. |

#### Additional tutorial explanation


In [121]:
df["service_type"].value_counts()


service_type
Transport              24
Employment             24
Waste                  24
Citizen Services       24
Housing                21
Transport               1
Citizen services        1
WASTE                   1
Employment Services     1


**Expected raw counts**

```text
Citizen Services    24
Employment          24
Transport           24
Waste               24
Housing             21

Additional inconsistent raw labels occur once each: `Citizen services`, `Employment Services`, `Transport ` and `WASTE`.
```

A frequency table answers:

> How many rows currently carry each stored category label?

It does not automatically answer:

> How many people belong to each category?

Again, the unit of observation matters.


## Example 3.9.4 — Percentages with normalize=True

[Open Example 3.9.4 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.4)


In [122]:
service_pct = (
    df["service_type"]
    .value_counts(normalize=True) * 100
)

print(service_pct.round(2))


service_type
Transport              19.83
Employment             19.83
Waste                  19.83
Citizen Services       19.83
Housing                17.36
Transport               0.83
Citizen services        0.83
WASTE                   0.83
Employment Services     0.83
Name: proportion, dtype: float64


Expected percentages:

```text
Citizen Services    19.83
Employment          19.83
Transport           19.83
Waste               19.83
Housing             17.36

Each inconsistent one-row label accounts for 0.83%.
```

The denominator is the set of non-missing `service_type` values used by `value_counts()`.


## Example 3.9.5 — Include missing values when relevant

[Open Example 3.9.5 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.5)


In [123]:
df["feedback"].value_counts(dropna=False)


feedback
Helpful guidance, but some users reported delayed follow-up.                             9
The issue was resolved quickly after the first contact.                                  7
The response was fast and the information was useful.                                    7
The response was quick, but route-change information was difficult to find online.       7
The guidance was clear, but the supporting-document requirements caused delays.          6
Friendly staff and a clear answer.                                                       6
The digital form was convenient and staff explained the process clearly.                 6
Fast response and useful guidance.                                                       5
The online application was useful, but several steps were difficult to understand.       5
Helpful staff explained the housing process, although the waiting time felt long.        5
Useful advice and a friendly response from staff.                                

For free text this table may be too detailed to be analytically useful, but the `dropna=False` principle is important.


## Example 3.9.6 — Mode

[Open Example 3.9.6 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.6)


In [124]:
df["service_type"].mode()


0    Citizen Services
1          Employment
2           Transport
3               Waste


Expected:

```text
Citizen Services
Employment
Transport
Waste
```

The four values tie at 24 rows each. A dataset can have more than one mode when several values tie for highest frequency.


## Example 3.9.7 — Introductory groupby()

**Lecture slide:** 31. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.9.7 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.7)


Waste includes the -4 count. Inconsistent labels split intended groups.


In [125]:
means = df.groupby("service_type")["cases_received"].mean()
display(means.round(2))


service_type
Citizen Services       129.92
Citizen services        99.00
Employment              88.04
Employment Services     97.00
Housing                115.86
Transport              102.54
Transport              107.00
WASTE                   90.00
Waste                   88.96


**Expected output on the raw course CSV**

```text
service_type
Citizen Services       129.92
Citizen services        99.00
Employment              88.04
Employment Services     97.00
Housing                115.86
Transport              102.54
Transport              107.00
WASTE                   90.00
Waste                   88.96
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Average received cases for each service label. |
| 2 | Show each mean, rounded for reading. |

### Conceptual model of `groupby()`

Think:

```text
SPLIT rows into groups
        ↓
APPLY a calculation to each group
        ↓
COMBINE the group results
```

This is often described as **split–apply–combine**.

#### Additional tutorial explanation


In [126]:
mean_by_service = (
    df.groupby("service_type")["cases_received"]
      .mean()
)

print(mean_by_service.round(2))


service_type
Citizen Services       129.92
Citizen services        99.00
Employment              88.04
Employment Services     97.00
Housing                115.86
Transport              102.54
Transport              107.00
WASTE                   90.00
Waste                   88.96
Name: cases_received, dtype: float64


Expected raw-data result (trailing spaces in a label are visually subtle):

```text
Citizen Services       129.92
Citizen services        99.00
Employment              88.04
Employment Services     97.00
Housing                115.86
Transport              102.54
Transport               107.00
WASTE                   90.00
Waste                   88.96
```

These are **preliminary** because the Waste group includes a negative raw value and inconsistent service labels form separate groups.


## Example 3.9.8 — Group totals

[Open Example 3.9.8 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.8)


In [127]:
total_by_service = (
    df.groupby("service_type")["cases_received"]
      .sum()
)

print(total_by_service)


service_type
Citizen Services       3118
Citizen services         99
Employment             2113
Employment Services      97
Housing                2433
Transport              2461
Transport               107
WASTE                    90
Waste                  2135
Name: cases_received, dtype: int64


Expected:

```text
Citizen Services       3118
Citizen services         99
Employment             2113
Employment Services      97
Housing                2433
Transport              2461
Transport               107
WASTE                    90
Waste                  2135
```

The raw duplicate record and invalid negative value can affect these totals.


## Example 3.9.9 — Several calculations at once with .agg()

[Open Example 3.9.9 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.9)


In [128]:
summary = (
    df.groupby("service_type")["cases_received"]
      .agg(["count", "sum", "mean", "median", "min", "max"])
)

print(summary.round(2))


                     count   sum    mean  median  min  max
service_type                                              
Citizen Services        24  3118  129.92   122.0   94  185
Citizen services         1    99   99.00    99.0   99   99
Employment              24  2113   88.04    86.5   62  129
Employment Services      1    97   97.00    97.0   97   97
Housing                 21  2433  115.86   113.0   86  157
Transport               24  2461  102.54    98.5   75  144
Transport                1   107  107.00   107.0  107  107
WASTE                    1    90   90.00    90.0   90   90
Waste                   24  2135   88.96    89.5   -4  138


Expected structure:

```text
                     count   sum    mean  median  min  max
service_type
Citizen Services        24  3118  129.92   122.0   94  185
Citizen services         1    99   99.00    99.0   99   99
Employment              24  2113   88.04    86.5   62  129
Employment Services      1    97   97.00    97.0   97   97
Housing                 21  2433  115.86   113.0   86  157
Transport               24  2461  102.54    98.5   75  144
Transport                1   107  107.00   107.0  107  107
WASTE                    1    90   90.00    90.0   90   90
Waste                   24  2135   88.96    89.5   -4  138
```

The `min = -4` in Waste is a visible warning. The split labels are a second warning not to interpret the group summaries uncritically.


## Example 3.9.10 — Grouping by a dirty category can mislead

[Open Example 3.9.10 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.10)


In [129]:
city_summary = (
    df.groupby("city")["cases_received"]
      .agg(["count", "sum", "mean"])
)

print(city_summary.round(2))


              count   sum    mean
city                             
 copenhagen       1    95   95.00
AALBORG           1    76   76.00
Aalborg          28  2386   85.21
Aarhus           30  3349  111.63
Copenhagen       29  3807  131.28
Koebenhavn        1    76   76.00
Odense           29  2642   91.10
Odense            1    78   78.00
aarhus            1   144  144.00


The raw city spellings produce separate groups such as:

```text
Copenhagen
 copenhagen 
Koebenhavn
Aalborg
AALBORG
```

This is a powerful demonstration of why **cleaning decisions affect analytical results**.

Do not merge them yet in Lecture 5. Document the problem.


## Example 3.9.11 — Cross-tabulation with pd.crosstab()

[Open Example 3.9.11 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.11)


In [130]:
service_by_city = pd.crosstab(
    df["city"],
    df["service_type"]
)

service_by_city


service_type  Citizen Services  Citizen services  Employment  Employment Services  Housing  Transport  Transport   WASTE  Waste
city                                                                                                                           
 copenhagen                  0                 0           0                    0        0          1           0      0      0
AALBORG                      0                 0           1                    0        0          0           0      0      0
Aalborg                      6                 1           5                    1        5          5           0      0      5
Aarhus                       6                 0           6                    0        6          6           0      0      6
Copenhagen                   6                 0           6                    0        6          5           0      0      6
Koebenhavn                   0                 0           0                    0        0          0   

Conceptually, rows are city labels and columns are service types.

The raw crosstab will again reveal split city spellings.

### Percentage crosstab — optional extension


## Example 3.9.12 — Percentage crosstab — optional extension

[Open Example 3.9.12 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.12)


In [131]:
service_by_city_pct = pd.crosstab(
    df["city"],
    df["service_type"],
    normalize="index"
) * 100

service_by_city_pct.round(1)


service_type  Citizen Services  Citizen services  Employment  Employment Services  Housing  Transport  Transport   WASTE  Waste
city                                                                                                                           
 copenhagen                0.0               0.0         0.0                  0.0      0.0      100.0         0.0    0.0    0.0
AALBORG                    0.0               0.0       100.0                  0.0      0.0        0.0         0.0    0.0    0.0
Aalborg                   21.4               3.6        17.9                  3.6     17.9       17.9         0.0    0.0   17.9
Aarhus                    20.0               0.0        20.0                  0.0     20.0       20.0         0.0    0.0   20.0
Copenhagen                20.7               0.0        20.7                  0.0     20.7       17.2         0.0    0.0   20.7
Koebenhavn                 0.0               0.0         0.0                  0.0      0.0        0.0   

`normalize="index"` makes each row sum to approximately 100%.

Always state what has been normalised. Row percentages and column percentages answer different questions.


## Example 3.9.13 — Compare satisfaction by service type

[Open Example 3.9.13 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.9/example-3.9.13)


In [132]:
satisfaction_by_service = (
    df.groupby("service_type")["satisfaction_score"]
      .agg(["count", "mean", "median", "min", "max"])
)

print(satisfaction_by_service.round(2))


                     count  mean  median  min  max
service_type                                      
Citizen Services        24  4.47     4.5  4.2  4.9
Citizen services         1  3.90     3.9  3.9  3.9
Employment              23  3.84     4.0  0.0  4.4
Employment Services      1  4.20     4.2  4.2  4.2
Housing                 20  3.67     3.7  3.5  3.9
Transport               23  4.14     4.2  3.9  4.4
Transport                1  3.50     3.5  3.5  3.5
WASTE                    1  3.80     3.8  3.8  3.8
Waste                   23  4.42     4.3  4.1  6.2


Before interpreting the output, ask:

1. Are there missing scores?
2. Are all scores within the expected 1–5 range?
3. Does each group contain enough observations to support a broad claim?
4. Is the dataset real or synthetic?

This checklist is more important than the code itself.


# Tutorial 3.10


## Example 3.10.1 — Missing values with isna()

[Open Example 3.10.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.1)


In [133]:
df.isna()


    record_id  report_month   city  service_type  cases_received  cases_resolved  resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours  feedback  unresolved_cases  case_gap  resolution_rate  resolved_pct_of_received
0       False         False  False         False           False           False            False               False          False            False            False                False        False     False             False     False            False                     False
1       False         False  False         False           False           False            False               False          False            False            False                False        False     False             False     False            False                     False
2       False         False  False         False           False           False            False               False          False            False     

returns a Boolean DataFrame indicating whether each cell is missing.

That is useful computationally but difficult to read as a complete table. Summarise by column:


In [134]:
missing_by_column = df.isna().sum()
print(missing_by_column)


record_id                   0
report_month                0
city                        0
service_type                0
cases_received              0
cases_resolved              0
resolution_days             0
satisfaction_score          4
digital_cases               0
in_person_cases             0
repeat_contacts             0
complaints_received         0
staff_hours                 0
feedback                    3
unresolved_cases            0
case_gap                    0
resolution_rate             0
resolved_pct_of_received    0
dtype: int64


For the supplied course dataset, pandas should recognise:

```text
satisfaction_score    4
feedback              3
```

with zero missing values in the other columns on the basic import.

### Total recognised missing cells


## Example 3.10.2 — Total recognised missing cells

[Open Example 3.10.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.2)


In [135]:
total_missing = df.isna().sum().sum()
print(total_missing)


7


Expected:

```text
7
```

This does **not** mean the dataset contains only seven problematic cells. Text such as `unknown` is a stored string, not a pandas missing value on basic import.


## Example 3.10.3 — Missing percentages

**Lecture slide:** 33. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.10.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.3)


Missing information needs an explanation before anyone replaces it.


In [136]:
columns = ["satisfaction_score", "feedback"]
display(df[columns].isna().sum())
missing_pct = df["satisfaction_score"].isna().mean() * 100
print("Missing scores (%):", round(missing_pct, 2))


satisfaction_score    4
feedback              3
Missing scores (%): 3.31


**Expected output on the raw course CSV**

```text
satisfaction_score    4
feedback              3
Missing scores (%): 3.31
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Choose two columns to check. |
| 2 | Mark missing cells and count them in each column. |
| 3 | The mean of True/False values gives the missing fraction. |
| 4 | Convert that fraction to a readable percentage. |

#### Additional tutorial explanation


In [137]:
missing_pct = df.isna().mean() * 100
print(missing_pct.round(2))


record_id                   0.00
report_month                0.00
city                        0.00
service_type                0.00
cases_received              0.00
cases_resolved              0.00
resolution_days             0.00
satisfaction_score          3.31
digital_cases               0.00
in_person_cases             0.00
repeat_contacts             0.00
complaints_received         0.00
staff_hours                 0.00
feedback                    2.48
unresolved_cases            0.00
case_gap                    0.00
resolution_rate             0.00
resolved_pct_of_received    0.00
dtype: float64


Because `True` is treated like 1 and `False` like 0, the mean of the Boolean missingness indicator becomes a proportion.

The raw missing percentages are approximately `2.48%` for `feedback` (3 of 121 rows) and `3.31%` for `satisfaction_score` (4 of 121 rows).


## Example 3.10.4 — Missing satisfaction score

[Open Example 3.10.4 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.4)


In [138]:
missing_satisfaction = df[df["satisfaction_score"].isna()]
display(missing_satisfaction)


       record_id report_month        city service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                           feedback  unresolved_cases  case_gap  resolution_rate  resolved_pct_of_received
21   SR2026-0022   2026-02-01  Copenhagen    Transport             126             118             4.8                 NaN             94               32                8                    7         54.7                Clear information and a helpful answer about the transport service.                 8         8        93.650794                 93.650794
48   SR2026-0049   2026-03-01      Aarhus        Waste             109             101             2.5                 NaN             84               25                5                    4         37.7                            The issue was resolved quickly after the first 

### Missing feedback


## Example 3.10.5 — Missing feedback

[Open Example 3.10.5 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.5)


In [139]:
missing_feedback = df[df["feedback"].isna()]
display(missing_feedback)


       record_id report_month     city service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours feedback  unresolved_cases  case_gap  resolution_rate  resolved_pct_of_received
17   SR2026-0018   2026-01-01  Aalborg   Employment              70              62             5.4                 4.1             42               28                8                    3         40.7      NaN                 8         8        88.571429                 88.571429
75   SR2026-0076   2026-04-01  Aalborg      Housing              96              88             5.6                 3.7             58               38               12                    7         67.5      NaN                 8         8        91.666667                 91.666667
117  SR2026-0118   2026-06-01  Aalborg   Employment              66              65             4.2                 4.2             42               24

Do not immediately drop these rows. First ask whether the missing value affects the analysis you want to perform.


## Example 3.10.6 — Exact duplicate rows

[Open Example 3.10.6 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.6)


In [140]:
duplicate_mask = df.duplicated()
print(duplicate_mask)


0      False
1      False
2      False
3      False
4      False
       ...  
116    False
117    False
118    False
119    False
120     True
Length: 121, dtype: bool


Count them:


In [141]:
print("Exact duplicate rows:", df.duplicated().sum())


Exact duplicate rows: 1


Expected:

```text
Exact duplicate rows: 1
```

Display the duplicate occurrence:


In [142]:
display(df[df.duplicated()])


       record_id report_month    city service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                  feedback  unresolved_cases  case_gap  resolution_rate  resolved_pct_of_received
120  SR2026-0027   2026-02-01  Aarhus    Transport             110             102             4.9                 4.2             79               31                6                    7         42.5  The digital form worked well, although some instructions were confusing.                 8         8        92.727273                 92.727273


### Why only one duplicate is counted

If two rows are identical, pandas normally treats the first occurrence as the original and flags the later occurrence as the duplicate when using the default settings.

To show **all members of duplicate groups**:


## Example 3.10.7 — Why only one duplicate is counted

[Open Example 3.10.7 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.7)


In [143]:
display(df[df.duplicated(keep=False)])


       record_id report_month    city service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                  feedback  unresolved_cases  case_gap  resolution_rate  resolved_pct_of_received
26   SR2026-0027   2026-02-01  Aarhus    Transport             110             102             4.9                 4.2             79               31                6                    7         42.5  The digital form worked well, although some instructions were confusing.                 8         8        92.727273                 92.727273
120  SR2026-0027   2026-02-01  Aarhus    Transport             110             102             4.9                 4.2             79               31                6                    7         42.5  The digital form worked well, although some instructions were confusing.                 8         8   

This makes it easier to compare the repeated rows.


## Example 3.10.8 — Duplicate identifiers are not the same as duplicate rows

**Lecture slide:** 34. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.10.8 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.8)


The same ID can appear in different rows. Check the records before deleting anything.


In [144]:
print("Extra exact copies:", df.duplicated().sum())
print("Repeated IDs:", df["record_id"].duplicated().sum())


Extra exact copies: 1
Repeated IDs: 2


**Expected output on the raw course CSV**

```text
Extra exact copies: 1
Repeated IDs: 2
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Count exact copies beyond their first occurrence. |
| 2 | Count repeated identifiers beyond their first occurrence. |

#### Additional tutorial explanation


In [145]:
id_duplicates = df["record_id"].duplicated(keep=False)

display(
    df.loc[
        id_duplicates,
        ["record_id", "report_month", "city", "service_type"]
    ]
)


       record_id report_month     city      service_type
26   SR2026-0027   2026-02-01   Aarhus         Transport
78   SR2026-0079   2026-04-01  Aalborg             Waste
79   SR2026-0079   2026-04-01  Aalborg  Citizen Services
120  SR2026-0027   2026-02-01   Aarhus         Transport


The repeated identifiers are `SR2026-0027` and `SR2026-0079`. The first belongs to an exact duplicate row; the second appears on two different service records.

A repeated identifier may indicate:

- a duplicated row;
- two legitimate records sharing an ID because the ID is not actually unique;
- an export problem;
- a version/history record;
- a data-entry error.

Therefore:

> **Repeated identifier ≠ automatically delete the row.**


## Example 3.10.9 — Category consistency

[Open Example 3.10.9 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.9)


In [146]:
print(df["city"].value_counts(dropna=False))


city
Aarhus          30
Copenhagen      29
Odense          29
Aalborg         28
 copenhagen      1
AALBORG          1
Odense           1
aarhus           1
Koebenhavn       1
Name: count, dtype: int64


The raw column contains labels such as:

```text
Copenhagen
 copenhagen 
AALBORG
Aalborg
Koebenhavn
```

Potential consistency issues include:

- leading/trailing whitespace;
- uppercase/lowercase differences;
- alternative spellings/transliterations;
- abbreviations;
- old/new category names.

Lecture 6 will standardise categories only after the intended equivalences are justified.


## Example 3.10.10 — Negative case counts

[Open Example 3.10.10 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.10)


In [147]:
negative_received = df[df["cases_received"] < 0]
display(negative_received)


      record_id report_month    city service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                      feedback  unresolved_cases  case_gap  resolution_rate  resolved_pct_of_received
53  SR2026-0054   2026-03-01  Odense        Waste              -4               0             3.0                 4.1              0                0                0                    0         29.7  Helpful guidance, but some users reported delayed follow-up.                -4        -4             -0.0                      -0.0


If counts should be zero or positive, this row violates the documented expectation.

### Out-of-range satisfaction


## Example 3.10.11 — Out-of-range satisfaction

[Open Example 3.10.11 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.11)


In [148]:
out_of_range_satisfaction = df[
    (df["satisfaction_score"] < 1) |
    (df["satisfaction_score"] > 5)
]

display(out_of_range_satisfaction)


      record_id report_month     city service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                    feedback  unresolved_cases  case_gap  resolution_rate  resolved_pct_of_received
38  SR2026-0039   2026-02-01  Aalborg        Waste              72              65             2.6                 6.2             48               24                5                    3         24.2                     The issue was resolved quickly after the first contact.                 7         7        90.277778                 90.277778
72  SR2026-0073   2026-04-01   Odense   Employment              77              74             4.4                 0.0             53               24                7                    2         41.0  The answer was useful, although the waiting time was longer than expected.                 3       

The raw file contains scores of `0.0` and `6.2`, which conflicts with the intended 1–5 teaching scale.

### Why not simply force 0.0 and 6.2 into the 1–5 range?

Because we do not know the cause. Clipping the value to the nearest allowed boundary invents a correction.

A defensible Lecture 5 note is:

> One non-missing satisfaction value falls outside the documented 1–5 range and should be investigated before final analysis.


## Example 3.10.12 — Resolved greater than received

**Lecture slide:** 35. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.10.12 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.12)


A flag identifies records to investigate. It does not explain their cause.


In [149]:
problem = df["cases_resolved"] > df["cases_received"]
columns = ["record_id", "cases_received", "cases_resolved"]
display(df.loc[problem, columns])


      record_id  cases_received  cases_resolved
11  SR2026-0012              80              87
53  SR2026-0054              -4               0
89  SR2026-0090             159             162


**Expected output on the raw course CSV**

```text
      record_id  cases_received  cases_resolved
11  SR2026-0012              80              87
53  SR2026-0054              -4               0
89  SR2026-0090             159             162
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Find rows where resolved exceeds received. |
| 2 | Keep the ID and both values for inspection. |
| 3 | Show the rows that pass this problem rule. |

#### Additional tutorial explanation


In [150]:
resolved_gt_received = df[
    df["cases_resolved"] > df["cases_received"]
]

display(
    resolved_gt_received[[
        "record_id",
        "cases_received",
        "cases_resolved"
    ]]
)


      record_id  cases_received  cases_resolved
11  SR2026-0012              80              87
53  SR2026-0054              -4               0
89  SR2026-0090             159             162


This may be logically impossible under one definition of the variables, but there are possible alternative explanations:

- cases resolved this month may include cases received in earlier months;
- the columns may use different time windows;
- one value may be erroneous.

This is why documentation matters.

Do not infer an error solely from intuition if the variable definitions are ambiguous.


## Example 3.10.13 — Detect a numeric-looking column containing text

[Open Example 3.10.13 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.13)


In [151]:
print(df["resolution_days"].unique())


['8.0' '5.1' '5.5' '4.9' '3.1' '7.5' '2.7' '3.0' '6.8' '4.2' '4.4'
 'unknown' '3.5' '5.4' '2.8' '7.3' '4.8' '6.1' '3.8' '2.9' '7.2' '3.9'
 '2.6' '4.6' '2.3' '6.5' '1.8' '5.2' '5.3' '6.9' '2.5' '4.0' '5.7' '1.5'
 '2.2' '1.4' '24.7' '4.5' '3.4' '1.7' '6.4' '5.6' '1.9' '7.7' '7.0' '3.6'
 '7.4' '5.0' '2.4' '2.1' '7.9' '4.7' '3.2' '3.7' '5.9']


A temporary conversion can help identify values that cannot be parsed numerically **without modifying the original column**:


In [152]:
resolution_numeric_preview = pd.to_numeric(
    df["resolution_days"],
    errors="coerce"
)


Then find rows where the raw value was present but the temporary numeric preview became missing:


In [153]:
conversion_problem = (
    df["resolution_days"].notna() &
    resolution_numeric_preview.isna()
)

display(
    df.loc[
        conversion_problem,
        ["record_id", "resolution_days"]
    ]
)


       record_id resolution_days
14   SR2026-0015         unknown
66   SR2026-0067         unknown
102  SR2026-0103         unknown


### Important

We have **not** changed:


## Example 3.10.14 — Important

[Open Example 3.10.14 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.14)


In [154]:
df["resolution_days"]


0         8.0
1         5.1
2         5.5
3         4.9
4         3.1
5         7.5
6         5.1
7         5.5
8         2.7
9         3.0
10        6.8
11        4.2
12        4.4
13        3.0
14    unknown
15        6.8
16        3.5
17        5.4
18        3.5
19        2.8
[121 rows in full result. Run the cell to display all rows.]


We created a temporary diagnostic Series. Permanent conversion belongs to Lecture 6.


## Example 3.10.15 — Detect invalid date-like values without overwriting the raw column

[Open Example 3.10.15 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.15)


In [155]:
report_month_preview = pd.to_datetime(
    df["report_month"],
    errors="coerce"
)


Rows that fail conversion become missing in the preview:


In [156]:
invalid_date_mask = report_month_preview.isna()

display(
    df.loc[
        invalid_date_mask,
        ["record_id", "report_month"]
    ]
)


      record_id report_month
43  SR2026-0044   2026-13-01


The raw course file contains an invalid month-like value:

```text
2026-13-01
```

Month 13 is not a valid calendar month.

Again, detect and document. Do not silently invent the intended month.


## Example 3.10.16 — Build a first data-quality summary

[Open Example 3.10.16 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.16)


In [157]:
quality_summary = {
    "rows": len(df),
    "columns": df.shape[1],
    "missing_cells": int(df.isna().sum().sum()),
    "exact_duplicate_rows": int(df.duplicated().sum()),
    "negative_cases_received": int((df["cases_received"] < 0).sum()),
    "out_of_range_satisfaction": int(
        ((df["satisfaction_score"] < 1) |
         (df["satisfaction_score"] > 5)).sum()
    )
}

for check, value in quality_summary.items():
    print(check, ":", value)


rows : 121
columns : 18
missing_cells : 7
exact_duplicate_rows : 1
negative_cases_received : 1
out_of_range_satisfaction : 2


This is a technical summary. It still needs human interpretation.


## Example 3.10.17 — Separate observation from action

[Open Example 3.10.17 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.17)


**Observation:** `record_id SR2026-0027` appears in two identical rows, while `SR2026-0079` labels two different rows.

**Premature action:** delete one row immediately.

**Better next step:** verify whether `record_id` is expected to be unique and whether repeated exports or legitimate repeated observations are possible.


## Example 3.10.18 — Quality problem changes a calculation

[Open Example 3.10.18 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.10/example-3.10.18)


The raw mean satisfaction score includes a value outside the documented range.

Therefore a good report should say:

> A preliminary mean was calculated for exploration, but the result requires re-evaluation after the out-of-range values are investigated and the cleaning rule is documented.

That is stronger than either ignoring the problem or secretly editing the value.


# Tutorial 3.11


## Example 3.11.1 — Start by reading the text

**Lecture slide:** 37. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.11.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.1)


A text column carries context that a numerical summary can miss.


In [158]:
feedback = df["feedback"].dropna()
print("Available comments:", len(feedback))
display(feedback.head(2))


Available comments: 118
0    The guidance was clear, but the supporting-doc...
1    Several users asked for clearer information ab...


**Expected output on the raw course CSV**

```text
Available comments: 118
0    The guidance was clear, but the supporting-doc...
1    Several users asked for clearer information ab...
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Keep the recorded feedback values. |
| 2 | Count the available comments. |
| 3 | Read the first two before defining a search rule. |

#### Additional tutorial explanation


In [159]:
display(df[["record_id", "feedback"]].head(10))


     record_id                                                                           feedback
0  SR2026-0001    The guidance was clear, but the supporting-document requirements caused delays.
1  SR2026-0002                 Several users asked for clearer information about service changes.
2  SR2026-0003                                  Useful advice and a friendly response from staff.
3  SR2026-0004                       Helpful guidance, but some users reported delayed follow-up.
4  SR2026-0005                              The response was fast and the information was useful.
5  SR2026-0006  Helpful staff explained the housing process, although the waiting time felt long.
6  SR2026-0007                 Several users asked for clearer information about service changes.
7  SR2026-0008         The answer was useful, although the waiting time was longer than expected.
8  SR2026-0009          Collection information was easy to understand and the response was quick.
9  SR2026-0010      

Do not begin by counting words you have never read.

A good first step is to inspect several non-missing comments:


In [160]:
feedback_non_missing = df["feedback"].dropna()

display(
    feedback_non_missing.sample(
        min(8, len(feedback_non_missing)),
        random_state=42
    )
)


57     The answer was useful, although the waiting ti...
91                    Fast response and useful guidance.
4      The response was fast and the information was ...
46     The response was quick, but route-change infor...
27     The guidance was clear but the process require...
119    The response was fast and the information was ...
70     The answer solved the problem, but repeated co...
10     The online application was useful, but several...


The code helps you select comments. The interpretation still requires reading them.


## Example 3.11.2 — Count available text responses

[Open Example 3.11.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.2)


In [161]:
print("Rows:", len(df))
print("Non-missing feedback:", df["feedback"].count())


Rows: 121
Non-missing feedback: 118


Expected:

```text
Rows: 121
Non-missing feedback: 118
```

Any text analysis using `feedback` therefore has at most 118 non-missing comments in the raw file.


## Example 3.11.3 — Character length

[Open Example 3.11.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.3)


In [162]:
feedback_length = df["feedback"].str.len()
print(feedback_length)


0      79.0
1      66.0
2      49.0
3      60.0
4      53.0
       ... 
116    72.0
117     NaN
118    73.0
119    53.0
120    72.0
Name: feedback, Length: 121, dtype: float64


Missing feedback remains missing.

Average character length:


In [163]:
print(round(feedback_length.mean(), 2))


63.78


Expected raw result:

```text
63.78
```

Character length does not measure quality or importance. It only measures stored text length.


## Example 3.11.4 — Approximate word count with pandas string methods

[Open Example 3.11.4 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.4)


In [164]:
word_count = df["feedback"].str.split().str.len()
print(word_count)


0      10.0
1       9.0
2       8.0
3       8.0
4       9.0
       ... 
116    10.0
117     NaN
118    11.0
119     9.0
120    10.0
Name: feedback, Length: 121, dtype: float64


This splits on whitespace. It is **not** the NLTK tokenisation process we will study later.

Use it as a basic descriptive measure, not a definitive linguistic analysis.


## Example 3.11.5 — Search for a literal word with .str.contains()

[Open Example 3.11.5 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.5)


In [165]:
helpful_mask = df["feedback"].str.contains(
    "helpful",
    case=False,
    na=False
)


### Explain each argument

- `"helpful"` is the search pattern;
- `case=False` ignores upper/lowercase differences;
- `na=False` treats missing feedback as not matching rather than returning a missing Boolean.

Count matches:


## Example 3.11.6 — Explain each argument

[Open Example 3.11.6 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.6)


In [166]:
print(helpful_mask.sum())


36


Expected raw result:

```text
36
```

Display the matching comments:


In [167]:
display(
    df.loc[
        helpful_mask,
        ["record_id", "service_type", "satisfaction_score", "feedback"]
    ]
)


      record_id      service_type  satisfaction_score                                                                               feedback
3   SR2026-0004             Waste                 4.2                           Helpful guidance, but some users reported delayed follow-up.
5   SR2026-0006           Housing                 3.6      Helpful staff explained the housing process, although the waiting time felt long.
13  SR2026-0014             Waste                 4.5                           Helpful guidance, but some users reported delayed follow-up.
20  SR2026-0021           Housing                 3.6      Helpful staff explained the housing process, although the waiting time felt long.
21  SR2026-0022         Transport                 NaN                    Clear information and a helpful answer about the transport service.
24  SR2026-0025  Citizen Services                 4.3                                     Quick and helpful service with clear instructions.
25  SR2026-00

The matching comments include different contexts. Some are positive overall; some combine helpfulness with a complaint about waiting.


## Example 3.11.7 — Search for alternatives with a simple pattern

**Lecture slide:** 38. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.11.7 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.7)


The output counts matches to this pattern. Read the matching comments.


In [168]:
mentions_wait = df["feedback"].str.contains(
    "wait|long", case=False, na=False, regex=True
)
print("Matching comments:", mentions_wait.sum())


Matching comments: 11


**Expected output on the raw course CSV**

```text
Matching comments: 11
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Search each recorded comment for a pattern. |
| 2 | Match wait OR long, ignore capitals, treat missing text as False. |
| 3 | Finish the True/False indicator. |
| 4 | Count the comments that match the rule. |

#### Additional tutorial explanation


In [169]:
wait_mask = df["feedback"].str.contains(
    "wait|long",
    case=False,
    na=False,
    regex=True
)


Here `|` means **OR** inside the regular-expression pattern.

Count:


In [170]:
print(wait_mask.sum())


11


Expected raw result:

```text
11
```

Display:


In [171]:
display(
    df.loc[
        wait_mask,
        ["record_id", "feedback", "satisfaction_score"]
    ]
)


       record_id                                                                           feedback  satisfaction_score
5    SR2026-0006  Helpful staff explained the housing process, although the waiting time felt long.                 3.6
7    SR2026-0008         The answer was useful, although the waiting time was longer than expected.                 3.9
20   SR2026-0021  Helpful staff explained the housing process, although the waiting time felt long.                 3.6
22   SR2026-0023         The answer was useful, although the waiting time was longer than expected.                 3.9
25   SR2026-0026  Helpful staff explained the housing process, although the waiting time felt long.                 3.6
30   SR2026-0031               The wait was not long, and the final response was clear and helpful.                 3.6
37   SR2026-0038         The answer was useful, although the waiting time was longer than expected.                 4.0
55   SR2026-0056  Helpful staff explaine

The raw course CSV has 11 matches to this pattern across several service labels. A match records the presence of the search wording. Read each full comment before interpreting it as a waiting or delay experience.


## Example 3.11.8 — Search for clarity-related wording

[Open Example 3.11.8 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.8)


In [172]:
clear_mask = df["feedback"].str.contains(
    "clear",
    case=False,
    na=False
)

print(clear_mask.sum())


40


Expected raw count:

```text
40
```

However, one of those comments is duplicated because the entire record is duplicated. A raw keyword count can therefore be affected by duplicate data.

This connects text analysis back to data quality.


## Example 3.11.9 — Search for speed-related wording

[Open Example 3.11.9 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.9)


In [173]:
speed_mask = df["feedback"].str.contains(
    "quick|fast",
    case=False,
    na=False,
    regex=True
)

print(speed_mask.sum())


32


Expected raw count:

```text
32
```

Again, do not treat `quick|fast` as a complete linguistic definition of “speed”. It is a transparent rule that finds some phrases and misses others.


## Example 3.11.10 — Literal versus regex search

[Open Example 3.11.10 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.10)


In [174]:
df["feedback"].str.contains(
    "some literal text",
    case=False,
    na=False,
    regex=False
)


0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
[121 rows in full result. Run the cell to display all rows.]


For this lecture, you only need to recognise the distinction. Advanced regular expressions are not part of the core course.


## Example 3.11.11 — Compare text presence with a numeric variable

[Open Example 3.11.11 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.11)


In [175]:
display(
    df.loc[
        wait_mask,
        ["feedback", "satisfaction_score"]
    ]
)


                                                                              feedback  satisfaction_score
5    Helpful staff explained the housing process, although the waiting time felt long.                 3.6
7           The answer was useful, although the waiting time was longer than expected.                 3.9
20   Helpful staff explained the housing process, although the waiting time felt long.                 3.6
22          The answer was useful, although the waiting time was longer than expected.                 3.9
25   Helpful staff explained the housing process, although the waiting time felt long.                 3.6
30                The wait was not long, and the final response was clear and helpful.                 3.6
37          The answer was useful, although the waiting time was longer than expected.                 4.0
55   Helpful staff explained the housing process, although the waiting time felt long.                 3.7
57          The answer was useful, al

You can inspect whether waiting-related comments coincide with lower scores.

But do not claim causation. The data are observational, tiny, imperfect and synthetic.


## Example 3.11.12 — Text length by service type

[Open Example 3.11.12 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.12)


Create a temporary word-count Series:


In [176]:
df["feedback_word_count_preview"] = (
    df["feedback"].str.split().str.len()
)


Then:


In [177]:
print(
    df.groupby("service_type")["feedback_word_count_preview"]
      .mean()
      .round(2)
)


service_type
Citizen Services        8.67
Citizen services        9.00
Employment              9.82
Employment Services    10.00
Housing                11.10
Transport               9.38
Transport              12.00
WASTE                  14.00
Waste                   8.71
Name: feedback_word_count_preview, dtype: float64


This asks whether feedback length differs across service categories in the raw teaching data.

It does **not** tell you that longer comments are more thoughtful or more negative.

Because this preview column is derived from raw text, it may be recreated later after cleaning rather than treated as a final analytical variable.


## Example 3.11.13 — Identify potentially difficult experiences

[Open Example 3.11.13 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.11/example-3.11.13)


In [178]:
difficulty_mask = df["feedback"].str.contains(
    "difficult|confusing",
    case=False,
    na=False,
    regex=True
)

print("Matches:", difficulty_mask.sum())

display(
    df.loc[
        difficulty_mask,
        ["record_id", "service_type", "feedback", "satisfaction_score"]
    ]
)


Matches: 19
       record_id      service_type                                                                            feedback  satisfaction_score
10   SR2026-0011        Transport   The online application was useful, but several steps were difficult to understand.                 3.5
11   SR2026-0012         Transport  The response was quick, but route-change information was difficult to find online.                 4.3
16   SR2026-0017         Transport            The digital form worked well, although some instructions were confusing.                 4.1
23   SR2026-0024             Waste                             Some users found the collection instructions confusing.                 4.1
26   SR2026-0027         Transport            The digital form worked well, although some instructions were confusing.                 4.2
40   SR2026-0041           Housing  The online application was useful, but several steps were difficult to understand.                 3.7
44   SR2026-004

Expected raw match count:

```text
19
```

Now read the two comments. Are both expressing the same kind of difficulty? A computational match begins the interpretation; it does not finish it.


# Tutorial 3.12


## Example 3.12.1 — From an idea to an operational rule

[Open Example 3.12.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.12/example-3.12.1)


In [179]:
df["mentions_wait"] = df["feedback"].str.contains(
    "wait|long",
    case=False,
    na=False,
    regex=True
)


The new column contains Boolean values:

```text
True
False
```

### Important terminology

The Boolean column is a **computational indicator based on a rule**.

It is safer to call it:

```text
mentions_wait
```

than:

```text
bad_service
```

because `mentions_wait` transparently states what was detected, whereas `bad_service` imposes a much broader interpretation.


## Example 3.12.2 — Count the indicator

[Open Example 3.12.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.12/example-3.12.2)


In [180]:
print(df["mentions_wait"].value_counts())


mentions_wait
False    110
True      11
Name: count, dtype: int64


Or count `True` directly:


In [181]:
print(df["mentions_wait"].sum())


11


Expected raw count:

```text
11
```


## Example 3.12.3 — Create several transparent indicators

[Open Example 3.12.3 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.12/example-3.12.3)


In [182]:
df["mentions_helpful"] = df["feedback"].str.contains(
    "helpful",
    case=False,
    na=False
)

df["mentions_clarity"] = df["feedback"].str.contains(
    "clear",
    case=False,
    na=False
)

df["mentions_difficulty"] = df["feedback"].str.contains(
    "difficult|confusing",
    case=False,
    na=False,
    regex=True
)


These are not final qualitative themes. They are explicit retrieval/coding rules that can be audited.


## Example 3.12.4 — Inspect the rule against the original text

[Open Example 3.12.4 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.12/example-3.12.4)


In [183]:
display(
    df[[
        "feedback",
        "mentions_wait",
        "mentions_helpful",
        "mentions_clarity",
        "mentions_difficulty"
    ]]
)


                                                                              feedback  mentions_wait  mentions_helpful  mentions_clarity  mentions_difficulty
0      The guidance was clear, but the supporting-document requirements caused delays.          False             False              True                False
1                   Several users asked for clearer information about service changes.          False             False              True                False
2                                    Useful advice and a friendly response from staff.          False             False             False                False
3                         Helpful guidance, but some users reported delayed follow-up.          False              True             False                False
4                                The response was fast and the information was useful.          False             False             False                False
5    Helpful staff explained the housing proce

Read the table and ask:

- Does every `True` match the intended concept?
- Are relevant comments marked `False` because they use different wording?
- Does one comment contain several ideas?
- Does negation change the meaning?

This is a basic validation step.


## Example 3.12.5 — Satisfaction by waiting mention

[Open Example 3.12.5 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.12/example-3.12.5)


In [184]:
wait_satisfaction = (
    df.groupby("mentions_wait")["satisfaction_score"]
      .agg(["count", "mean", "median", "min", "max"])
)

print(wait_satisfaction.round(2))


               count  mean  median  min  max
mentions_wait                               
False            107  4.18    4.20  3.5  6.2
True              10  3.39    3.65  0.0  4.0


This compares available satisfaction scores for comments that do and do not match the rule.

A cautious interpretation could say:

> In this raw synthetic dataset, comments matching the simple waiting rule can be compared descriptively with other comments, but the small number of matches, missing score, dirty data and simplistic coding rule prevent strong conclusions.

Do **not** say:

> Waiting causes low satisfaction.

The code does not establish causation.


## Example 3.12.6 — Compare indicator counts across service types

[Open Example 3.12.6 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.12/example-3.12.6)


In [185]:
wait_by_service = (
    df.groupby("service_type")["mentions_wait"]
      .sum()
)

print(wait_by_service)


service_type
Citizen Services       0
Citizen services       0
Employment             5
Employment Services    0
Housing                6
Transport              0
Transport              0
WASTE                  0
Waste                  0
Name: mentions_wait, dtype: int64


If all `True` values occur in Housing, that is an observation in this particular teaching dataset.

It is not evidence about Housing services in real cities because the dataset is synthetic.


## Example 3.12.7 — Cross-tabulate a code and category

[Open Example 3.12.7 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.12/example-3.12.7)


In [186]:
pd.crosstab(
    df["service_type"],
    df["mentions_wait"]
)


mentions_wait        False  True 
service_type                     
Citizen Services        24      0
Citizen services         1      0
Employment              19      5
Employment Services      1      0
Housing                 15      6
Transport               24      0
Transport                1      0
WASTE                    1      0
Waste                   24      0


This gives counts of matching/non-matching comments by service type.

A later visualisation could display such a table, but Lecture 7 will cover chart selection systematically.


## Example 3.12.8 — A transparent code is better than a vague label

[Open Example 3.12.8 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.12/example-3.12.8)


Less transparent:


In [187]:
df["negative"] = ...


Questions immediately arise:

- What counts as negative?
- Who defined it?
- How are mixed comments handled?
- Is “long” always negative?

More transparent:


In [188]:
df["mentions_wait_or_long"] = df["feedback"].str.contains(
    "wait|long",
    case=False,
    na=False,
    regex=True
)


The second name does not solve the validity problem, but it exposes the actual rule.


## Example 3.12.12 — Reading matched and unmatched feedback

**Lecture slide:** 39. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.12.12 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.12/example-3.12.12)


A keyword rule can count words successfully while representing an experience poorly. Inspect these two original course comments.

- **SR2026-0031:** “The wait was not long, and the final response was clear and helpful.” It matches `wait|long`, although the speaker describes a short wait. It could be a false positive if the intended code means a long delay.
- **SR2026-0085:** “The process took forever, although the staff member was helpful.” It does not match `wait|long`, although the wording may describe a delay. It could be a false negative for the same intended code.

Eleven matches means eleven comments matched the explicit search rule. Context determines whether that rule represents the intended experience.



#### Inspection code

Compare a comment that matches wait OR long with a comment the rule misses. Read the full wording before interpreting a match as a delay.


In [189]:
columns = ["record_id", "feedback"]
display(df.loc[df["record_id"].isin(["SR2026-0031", "SR2026-0085"]), columns])


      record_id                                                              feedback
30  SR2026-0031  The wait was not long, and the final response was clear and helpful.
84  SR2026-0085      The process took forever, although the staff member was helpful.


**Expected output on the raw course CSV**

```text
      record_id                                                              feedback
30  SR2026-0031  The wait was not long, and the final response was clear and helpful.
84  SR2026-0085      The process took forever, although the staff member was helpful.
```

**What each line does**

| Line | Explanation |
|---:|---|
| 1 | Choose the identifier and original feedback columns. |
| 2 | Display the two named records so you can compare the search rule with their meaning. |


# Tutorial 3.13


## Example 3.13.1 — Good provenance statement

[Open Example 3.13.1 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.13/example-3.13.1)


> The analysis uses the synthetic `E26_TAN7_service_experience_raw.csv` course dataset loaded from the E26 GitHub repository. One row is intended to represent one service category in one city during one reporting month. The dataset contains deliberate quality problems and should be used only for teaching, not as evidence about real municipal services.

This is much stronger than:

> I downloaded a CSV from GitHub.


## Example 3.13.2 — Good preliminary finding

**Lecture slide:** 40. The cells below use the same public example number. The slide links open the exact relevant cell.

[Open Example 3.13.2 on the website](https://asmrabbi.github.io/E26_TAN7_Scripting_CPH/#data-i/3.13/example-3.13.2)


> In the raw teaching data, the exact `Housing` label accounts for 21 of 121 rows (17.36%). This is a proportion of service-category-city-month records, not a proportion of citizens. The dataset also contains duplicate and category-consistency issues, so the result is preliminary.

Notice that the statement includes:

- numerator;
- denominator;
- unit meaning;
- limitation.



#### A received-case finding

**Observed:** The raw table contains 121 rows. Received-case counts sum to 12,653.

**Calculated:** We loaded the CSV and added the stored `cases_received` values.

**Limited by:** A negative count and an exact duplicate still need investigation.

**Next step:** Preserve the raw data, justify cleaning decisions, then rerun the summaries. The statement describes the synthetic teaching table and does not establish real service performance.
